
<h2 class="text-danger">
    <?php echo $this->exception->getMessage() ?>
</h2>

<div class="row">
    <div class="col-xs-2">
        <span class="label label-default">Type:</span>
    </div>
    <div class="col-xs-10">
        <?php echo $this->exception->type ?>
    </div>
</div>

<div class="row">
    <div class="col-xs-2">
        <span class="label label-default">Code:</span>
    </div>
    <div class="col-xs-10">
        <?php echo $this->exception->getCode() ?>
    </div>
</div>

<div class="row">
    <div class="col-xs-2">
        <span class="label label-default">Line:</span>
    </div>
    <div class="col-xs-10">
        <?php echo $this->exception->getLine() ?>
    </div>
</div>

<div class="row">
    <div class="col-xs-2">
        <span class="label label-default">File:</span>
    </div>
    <div class="col-xs-10">
        <?php echo $this->exception->getFile() ?>
    </div>
</div>
<?php echo $this->exception->getFileHighlight() ?>