<?php if($this->debug) : ?>
<h2 class="text-danger">
    <?php echo $this->exception->getMessage() ?>
</h2>

<div class="col-xs-4">Code: </div>
<div class="col-xs-8">
    <?php echo $this->exception->getCode() ?>
</div>


<div class="col-xs-4">Line: </div>
<div class="col-xs-8">
    <?php echo $this->exception->getLine() ?>
</div>

<div class="col-xs-4">File: </div>
<div class="col-xs-8">
    <?php echo $this->exception->getFile() ?>
</div>


<pre><?php echo $this->exception->getTraceAsString(); ?></pre>
<?php endif ?>