
<h1 class="text-danger ellipsis" title="<?php echo $this->exception->getMessage() ?>">
    <?php echo $this->exception->getMessage() ?>
</h1>

<div class="row">
    <div class="col-xs-3 col-sm-2 col-lg-1">
        <span class="label label-danger">Type:</span>
    </div>
    <div class="col-xs-9 col-sm-2 col-lg-11">
        <?php echo $this->exception->type ?>
    </div>
</div>

<div class="row">
    <div class="col-xs-3 col-sm-2 col-lg-1">
        <span class="label label-danger">Code:</span>
    </div>
    <div class="col-xs-9 col-sm-2 col-lg-11">
        <?php echo $this->exception->getCode() ?>
    </div>
</div>

<div class="row">
    <div class="col-xs-3 col-sm-2 col-lg-1">
        <span class="label label-danger">Line:</span>
    </div>
    <div class="col-xs-9 col-sm-2 col-lg-11">
        <?php echo $this->exception->getLine() ?>
    </div>
</div>

<div class="row">
    <div class="col-xs-3 col-sm-2 col-lg-1">
        <span class="label label-danger">File:</span>
    </div>
    <div class="col-xs-9 col-sm-2 col-lg-11 ellipsis" title="<?php echo $this->exception->getFile() ?>">
        <?php echo $this->exception->getFile() ?>
    </div>
</div>

<div class="row">
    <div class="col-xs-3 col-sm-2 col-lg-1">
        <span class="label label-danger">Time:</span>
    </div>
    <div class="col-xs-9 col-sm-2 col-lg-11">
        <?php echo $this->exception->getDate() ?>
    </div>
</div>

<fieldset>
    <legend class="text-danger text-bold">
        <i class="glyphicon glyphicon-chevron-up"></i>
        Code
    </legend>
    <div>
        <?php echo $this->exception->getFileHighlight() ?>
    </div>
</fieldset>

<fieldset>
    <legend class="text-danger text-bold">
        <i class="glyphicon glyphicon-chevron-down"></i>
        Stacktrace
    </legend>
    <div style="display:none">
        <?php echo $this->dump($this->exception->getStacktrace()) ?>
    </div>
</fieldset>

<script type="text/javascript">
    $(function () {
        $("legend").click(function () {
            $(this).next().slideToggle();
            $(this).find("i").toggleClass("glyphicon-chevron-down glyphicon-chevron-up");
        });
    });
</script>