<?php /** @var Phalcon\Mvc\View $this */ ?>

<div class="panel panel-success opcache chartist">
    <div class="panel-heading">
        <div class="btn-group pull-right">
            <button class="btn btn-default fa fa-chevron-left" title="Previous chart" aria-label="Previous chart"></button>
            <button class="btn btn-default fa fa-chevron-right" title="Next chart" aria-label="Next chart"></button>
            <a href="<?php echo $this->url->get('opcache/details') ?>" data-fancybox data-type="iframe" class="btn btn-default fa fa-chart-bar rounded-not-mobile" title="Details"></a>
            <?php $this->partial('index/default_widget_buttons', ['hasRefresh' => false, 'widget' => $widget]) ?>
        </div>
        <h4 class="truncate-text" title="Opcache">Opcache</h4>
    </div>
    <div class="panel-body hidden-xs">
        <div class="graph">
            <h4>Memory</h4>
        </div>
    </div>
</div>
