
<div class="panel panel-success with-nav-tabs">
    <div class="panel-heading ">
        <h4 class="pull-left">HyperVAdmin</h4>
        <ul class="nav nav-tabs pull-right">
            <li class="active">
                <a data-toggle="tab" href="#vms">VMs</a>
            </li>
            <li>
                <a data-toggle="tab" href="#sites">Sites</a>
            </li>
        </ul>
    </div>
    <div class="tab-content">
        <?php $this->partial('hyper_v_admin/partials/vms') ?>
        <?php $this->partial('hyper_v_admin/partials/sites') ?>
    </div>
</div>
