version: "3.7"

services:
  chell:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:80
    volumes:
      - /proc:/prochost:ro
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: chell
      MYSQL_USER: chell
      MYSQL_PASSWORD: example