version: "3.8"

services:
  chell:
    build: .
    # Host networking needed to do UDP broadcasts for WOL
    network_mode: host
    restart: unless-stopped
    ports:
      - 8094:8094
    volumes:
      # Needed for CPU widget to get the current CPU usage for the host
      - /proc:/prochost:ro
      # In order to have the disk widget work, add volumes for the mountpoints of each disk you want to get stats on here.
      # They need to be mounted in /mnt/<name>
      - /unraid:/var/www/portal
    environment:
      - SERVERNAME=Chell

  db:
    image: mysql:latest
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: chell
      MYSQL_USER: chell
      MYSQL_PASSWORD: example
      MYSQL_ROOT_HOST: '192.168.1.%'
    command: ["mysqld", "--bind-address=0.0.0.0"]
    ports:
      - 3306:3306