version: "3.8"

services:
  chell:
    image: gotgeeks/chell:latest
    ports:
      - 8080:80
    volumes:
      - /proc:/prochost:ro
  db:
    image: mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: chell
      MYSQL_USER: chell
      MYSQL_PASSWORD: example