<div id="doorwindow" class="tab-pane fade in active">
    <div class="table-responsive">
        <table class="table table-striped table-hover">
            <thead>
                <tr>
                    <th>Name</th>
                    <th>State</th>
                    <th>Time</th>
                </tr>
            </thead>
            <tbody>
                <?php foreach($overview->doorWindow->doorWindowDevice as $doorWindow) : ?>
                <tr>
                    <td>
                        <?php echo $doorWindow->area ?>
                    </td>
                    <td>
                        <?php echo ucfirst(strtolower($doorWindow->state)) ?>
                    </td>
                    <td>
                        <?php echo date('d-m-Y H:i', strtotime($doorWindow->reportTime)) ?>
                    </td>
                </tr>
                <?php endforeach ?>
            </tbody>
        </table>
    </div>
</div>