<div id="log" class="tab-pane fade">
    <div class="table-responsive">
        <table class="table table-striped table-hover">
            <thead>
                <tr>
                    <th>Name</th>
                    <th>Event</th>
                    <th>Time</th>
                </tr>
            </thead>
            <tbody>
                <?php foreach($log->data->installation->eventLog->pagedList as $eventLog) : ?>
                <tr>
                    <td>
                        <?php echo $eventLog->device->area ?>
                    </td>
                    <td>
                        <?php echo $eventLog->eventCategory ?>
                    </td>

                    <td>
                        <?php echo date('d-m-Y H:i', strtotime($eventLog->eventTime)) ?>
                    </td>
                </tr>
                <?php endforeach ?>
            </tbody>
        </table>
    </div>
</div>