<?php /** @var Phalcon\Mvc\View $this */ ?>

<div class="panel panel-success sonarr">
    <?php $this->partial('is-loading') ?>

    <div class="panel-heading">
        <div class="btn-group pull-right">
            <button class="btn btn-default fa fa-list" title="Show as list" aria-label="Show as list"></button>
            <?php $this->partial('index/default_widget_buttons', ['hasRefresh' => false, 'widget' => $widget]) ?>
        </div>
        <h4 class="truncate-text" title="Sonarr">Sonarr</h4>
    </div>
    <div class="panel-body hidden-xs no-gutter">
        <div id="sonarr-calendar"></div>

        <div class="hidden_not_important list">
            <ul class="list-group">
                <li class="list-group-item col-xs-12 clone hidden">
                    <div class="col-xs-4 col-lg-3 date"></div>
                    <div class="col-xs-8 col-lg-9 name"></div>
                </li>
            </ul>
        </div>
    </div>
</div>
