<?php /** @var Phalcon\Mvc\View $this */ ?>

<div class="panel panel-success sonarr">
    <?php $this->partial('is-loading') ?>

    <div class="panel-heading">
        <div class="btn-group pull-right">
            <?php $this->partial('index/default_widget_buttons', ['hasRefresh' => false, 'widget' => $widget]) ?>
        </div>
        <h4 class="truncate-text" title="Sonarr">Sonarr</h4>
    </div>
    <div class="panel-body hidden-xs no-gutter">
        <div id="sonarr-calendar"></div>
    </div>
</div>
