<?php /** @var Phalcon\Mvc\View $this */ ?>

<div class="panel panel-success with-nav-tabs" id="roborock-details">
    <div class="panel-heading">
        <h4 class="pull-left hidden-xs">Device</h4>
    </div>
    <div class="panel-body">
        <?php echo $architecture ?><br />
        <?php echo $cpuUsage ?><br />
        <br />
        <?php foreach($cores as $core => $values) : ?>
        <?php echo $core ?><br />
        <?php foreach($values as $name => $value) : ?>
        <?php echo $name . ':' . $value ?><br />
        <?php endforeach ?>
        <?php endforeach ?>
        <br />
        <?php foreach($info as $name => $value) : ?>
        <?php echo $name . ':' . $value ?><br />
        <?php endforeach ?>
    </div>
</div>