<ul class="list-group panel-success">
    <li class="row list-group-item list-group-item-success">
        <h4>Current stats</h4>
    </li>
    <li class="row list-group-item text-center">
        <img src="<?php echo $device->webtemp ?>/stats.png?t=<?php echo filemtime('/var/www/html/' . $device->webtemp . '/stats.png') ?>" />
    </li>

    <li class="row list-group-item list-group-item-success">
        <h4>24 hours</h4>
    </li>
    <li class="row list-group-item text-center">
        <img src="<?php echo $device->webtemp ?>/stats24.png?t=<?php echo filemtime('/var/www/html/' . $device->webtemp . '/stats24.png') ?>" />
    </li>

    <li class="row list-group-item list-group-item-success">
        <h4>Stats 7 days</h4>
    </li>
    <li class="row list-group-item text-center">
        <img src="<?php echo $device->webtemp ?>/stats7.png?t=<?php echo filemtime('/var/www/html/' . $device->webtemp . '/stats7.png') ?>" />
    </li>

    <li class="row list-group-item list-group-item-success">
        <h4>Stats 31 days</h4>
    </li>
    <li class="row list-group-item text-center">
        <img src="<?php echo $device->webtemp ?>/stats31.png?t=<?php echo filemtime('/var/www/html/' . $device->webtemp . '/stats31.png') ?>" />
    </li>
</ul>
