<?php /** @var Phalcon\Mvc\View $this */ ?>

<div class="panel panel-success devices" data-device-state-interval="<?php echo $this->settings->application->check_device_states_interval->value ?>">
    <div class="panel-heading">
        <div class="btn-group pull-right">
            <?php $this->partial('index/default_widget_buttons', ['hasRefresh' => true, 'widget' => $widget]) ?>
        </div>
        <h4 class="truncate-text" title="Devices">Devices</h4>
    </div>
    <ul class="list-group hidden-xs">
        <?php foreach($devices as $device) : ?>
        <li class="list-group-item col-xs-12<?php echo $device->show_on_dashboard ? null : ' hidden' ?>">
            <div class="col-xs-6 col-sm-5">
                <?php echo $device->name ?>
            </div>
            <div class="col-xs-6 col-sm-7">
                <div class="btn-group pull-right">
                    <?php if (!empty($device->hypervadmin_url)) : ?>
                    <a href="<?php echo $this->url->get('hyper_v_admin/index/' . $device->id) ?>" class="btn btn-default disabled hypervadmin" data-fancybox data-type="iframe" title="HyperVAdmin">
                        <span class="fa fa-server"></span>
                    </a>
                    <?php endif ?>
                    <?php if ($device->shutdown_method == 'adb') : ?>
                    <a href="<?php echo $this->url->get('devices/details/' . $device->id) ?>" class="btn btn-default adb-details" data-fancybox data-type="iframe" title="Details">
                        <span class="fa fa-wrench"></span>
                    </a>
                    <?php endif ?>

                    <a class="btn btn-default disabled devicestate"
                        data-id="<?php echo $device->id ?>"
                        data-shutdown-method="<?php echo $device->shutdown_method ?>">
                        <span class="fa fa-rotate fa-spin"></span>
                    </a>
                </div>
            </div>
        </li>
        <?php endforeach ?>
    </ul>
</div>
