<?php /** @var Phalcon\Mvc\View $this */ ?>

<div class="panel panel-success pull-left youless"
    data-updateinterval="<?php echo $this->settings->youless->update_interval ?>"
    data-primary="<?php echo $this->settings->youless->threshold_primary ?>"
    data-warn="<?php echo $this->settings->youless->threshold_warning ?>"
    data-danger="<?php echo $this->settings->youless->threshold_danger ?>">
    <?php $this->partial('is-loading') ?>

    <div class="panel-heading">
        <div class="btn-group pull-right">
            <a href="<?php echo $this->settings->youless->url ?>"
                target="_blank" class="btn btn-default fa fa-globe" rel="noreferrer" title="Youless"></a>
            <?php $this->partial('index/default_widget_buttons', ['hasRefresh' => true, 'widget' => $widget]) ?>
        </div>
        <h4 class="truncate-text" title="Youless">Youless</h4>
    </div>
    <ul class="list-group hidden-xs">
        <li class="list-group-item col-xs-12 counter">
            <div class="col-xs-4 col-sm-5 col-lg-4">
                Counter
            </div>
            <div class="col-xs-8 col-sm-7 col-lg-8 value">
                &hellip;
            </div>
        </li>
        <li class="list-group-item col-xs-12 power">
            <div class="col-xs-4 col-sm-5 col-lg-4">
                Current
            </div>
            <div class="col-xs-8 col-sm-7 col-lg-8">
                <div class="value">
                    <span>&hellip;</span>
                    <i class="fa fa-bolt"></i>
                </div>
            </div>
        </li>
    </ul>
</div>
