<?php /** @var Phalcon\Mvc\View $this */ ?>

<div class="panel panel-success pull-left docker"
    data-updateinterval="<?php echo $this->settings->docker->update_interval ?>">
    <?php $this->partial('is-loading') ?>

    <div class="panel-heading">
        <div class="btn-group pull-right">
            <?php $this->partial('index/default_widget_buttons', ['hasRefresh' => true, 'widget' => $widget]) ?>
        </div>
        <h4 class="truncate-text" title="Processes">Docker</h4>
    </div>
    <ul class="list-group hidden-xs">
        <li class="list-group-item col-xs-12 hidden docker-container">
            <div class="col-xs-6 name">
                <span class="bs-tooltip"></span>
            </div>
            <div class="col-xs-6 status">
            </div>
        </li>
    </ul>
</div>
