<?php /** @var Phalcon\Mvc\Controller $this */ ?>

<div class="panel panel-success pull-left pihole chartist" data-pihole-url="<?php echo $this->settings->pihole->url ?>">
    <div class="panel-heading">
        <div class="btn-group pull-right">
            <button class="btn btn-default fa fa-sync rounded-not-mobile" title="Refresh" aria-label="Refresh"></button>
            <button class="btn btn-default fa fa-plus visible-xs pull-right toggle-collapse" title="Collapse/expand" aria-label="Collapse/expand"></button>
        </div>
        <h4>PiHole</h4>
    </div>
    <div class="panel-body hidden-xs">
        <h4>DNS queries today</h4>
        <div class="graph"></div>
    </div>
</div>
