<?php /** @var Phalcon\Mvc\View $this */ ?>

<div class="panel panel-success pull-left pihole chartist" data-pihole-url="<?php echo $this->settings->pihole->url ?>">
    <div class="panel-heading">
        <div class="btn-group pull-right">
            <?php $this->partial('index/default_widget_buttons', ['hasRefresh' => true]) ?>
        </div>
        <h4>PiHole</h4>
    </div>
    <div class="panel-body hidden-xs">
        <h4>DNS queries today</h4>
        <div class="graph"></div>
    </div>
</div>
