<div id="config" class="tab-pane fade">
    <div class="table-responsive">
        <table class="table table-striped table-hover">
            <tbody>
                <?php
                $config = $opcache->getConfiguration();
                foreach ($config['directives'] as $key => $value): 
                ?>
                <tr>
                    <td>
                        <?php echo ucfirst(str_replace('_', ' ', $key)) ?>
                    </td>
                    <td>
                        <?php if (is_bool($value)) : ?>
                        <i class="fa <?php echo ($value === true ? 'fa-check text-success' : 'fa-times text-danger') ?>"></i>
                        <?php else : ?>
                        <?php echo $opcache->getFormattedData($key, $value) ?>
                        <?php endif ?>
                    </td>
                </tr>
                <?php endforeach ?>
            </tbody>
        </table>
    </div>
</div>