
<div id="scripts" class="tab-pane fade<?php echo ($activeTab == 'scripts' ? ' active in' : null) ?>">
    <div class="table-responsive">
        <table class="table table-striped table-hover">
            <thead>
                <tr>
                    <th>Hits</th>
                    <th>Memory</th>
                    <th style="max-width:300px">Path</th>
                </tr>
            </thead>
            <tbody>
                <?php foreach ($scripts as $dir => $info) : $count = count($info['files']); ?>
                <?php if($count > 1) :  ?>
                <tr>
                    <th colspan="3">
                        <?php echo $dir . ' (' . $count . ' files, '  . $opcache->getFormattedData('opcache.memory_consumption', $info['memory_usage']) . ')' ?>
                    </th>
                </tr>
                <?php endif ?>
                <?php foreach ($info['files'] as $file => $data) : ?>
                <tr>
                    <td>
                        <?php echo $data['hits'] ?>
                    </td>
                    <td>
                        <?php echo $opcache->getFormattedData('opcache.memory_consumption', $data['memory_consumption']) ?>
                    </td>
                    <td title="<?php echo ($path = $count > 1 ? $file : $dir . $file ) ?>">
                        <?php echo $path ?>
                    </td>
                </tr>
                <?php endforeach;
                      endforeach  ?>
            </tbody>
        </table>
    </div>
    <?php $this->partial('paginator') ?>
</div>