
<div id="status" class="tab-pane fade active in">
    <div class="table-responsive">
        <table class="table table-striped table-hover">
            <tbody>
                <?php foreach($opcache->status as $key => $value) : ?>
                <?php if ($key == 'scripts') continue ?>
                <?php if (is_array($value)) : ?>
                <?php foreach($value as $innerKey => $innerValue) : ?>
                <tr>
                    <td>
                        <?php echo ucfirst(str_replace('_', ' ', $innerKey)) ?>
                    </td>
                    <td>
                        <?php echo $opcache->getFormattedData($innerKey, $innerValue) ?>
                    </td>
                </tr>
                <?php endforeach ?>
                <?php continue;
                      endif ?>
                <tr>
                    <td>
                        <?php echo ucfirst(str_replace('_', ' ', $key)) ?>
                    </td>
                    <td>
                        <?php if(is_bool($value)) : ?>
                        <i class="fa <?php echo ($value === true ? 'fa-check text-success' : 'fa-times text-danger') ?>"></i>
                        <?php else : ?>
                        <?php echo $opcache->getFormattedData($key, $value) ?>
                        <?php endif ?>
                    </td>
                </tr>
                <?php endforeach ?>
            </tbody>
        </table>
    </div>
</div>