<?php /** @var Phalcon\Mvc\View $this */ ?>

<div class="col-xs-12 col-sm-6 col-md-4 col-lg-4">
    <div class="panel panel-success apache" data-update-interval="<?php echo $this->settings->apache->update_interval ?>">
        <?php $this->partial('is-loading') ?>

        <div class="panel-heading">
            <div class="btn-group pull-right">
                <button class="btn btn-default fa fa-sync rounded-not-mobile" title="Refresh" aria-label="Refresh"></button>
                <button class="btn btn-default fa fa-plus visible-xs pull-right toggle-collapse" title="Collapse/expand" aria-label="Collapse/expand"></button>
            </div>
            <h4>Apache</h4>
        </div>
        <ul class="list-group hidden-xs">
            <li class="list-group-item col-xs-12">
                <div class="col-xs-4 col-sm-5 col-lg-4">
                    Version
                </div>
                <div class="col-xs-8 col-sm-7 col-lg-8 version">&hellip;</div>
            </li>
            <li class="list-group-item col-xs-12">
                <div class="col-xs-4 col-sm-5 col-lg-4">
                    Server Built
                </div>
                <div class="col-xs-8 col-sm-7 col-lg-8 built">&hellip;</div>
            </li>
            <li class="list-group-item col-xs-12">
                <div class="col-xs-4 col-sm-5 col-lg-4">
                    CPU load
                </div>
                <div class="col-xs-8 col-sm-7 col-lg-8 load">&hellip;</div>
            </li>
            <li class="list-group-item col-xs-12">
                <div class="col-xs-4 col-sm-5 col-lg-4">
                    Req/s
                </div>
                <div class="col-xs-8 col-sm-7 col-lg-8 requests-s">&hellip;</div>
            </li>
            <li class="list-group-item col-xs-12">
                <div class="col-xs-4 col-sm-5 col-lg-4">
                    Bytes/s
                </div>
                <div class="col-xs-8 col-sm-7 col-lg-8 bytes-s">&hellip;</div>
            </li>
            <li class="list-group-item col-xs-12">
                <div class="col-xs-4 col-sm-5 col-lg-4">
                    Bytes/req
                </div>
                <div class="col-xs-8 col-sm-7 col-lg-8 bytes-requests">&hellip;</div>
            </li>

            <li class="list-group-item col-xs-12">
                <div class="col-xs-4 col-sm-5 col-lg-4">
                    Duration/req
                </div>
                <div class="col-xs-8 col-sm-7 col-lg-8 duration-request">&hellip;</div>
            </li>
        </ul>
    </div>
</div>