<div class="col-xs-12 col-sm-6 col-md-4 col-lg-4">
    <div class="panel panel-success pull-left couchpotato gallery"
        data-rotate-interval="<?php echo $this->config->couchpotato->rotateInterval ?>"
        data-base-url="<?php echo $this->config->application->baseUri ?>"
        data-couchpotato-apikey="<?php echo $this->config->couchpotato->APIKey ?>"
        data-couchpotato-url="<?php echo $this->config->application->baseUri . $this->config->couchpotato->URL ?>">
        <div class="panel-heading">
            <div class="backdrop"></div>
            <div class="btn-group pull-right">
                <button class="btn btn-default fa fa-chevron-left" title="Next movie"></button>
                <button class="btn btn-default fa fa-chevron-right" title="Previous movie"></button>
                <button class="btn btn-default fa fa-search" title="Search wanted movies now!"></button>
                <button class="btn btn-default fa fa-sync rounded-not-mobile" title="Refresh"></button>
                <button class="btn btn-default fa fa-plus visible-xs toggle-collapse"></button>
            </div>
            <h4>CouchPotato</h4>
        </div>

        <div class="panel-body hidden-xs">
            <?php if($couchpotato) : ?>
                <?php $i= 0; foreach($couchpotato as $movie) : ?>
                <a class="item <?php echo $i++ > 0 ? 'hidden' : 'show' ?>_not_important"
                    href="<?php echo $this->config->application->baseUri .'couchpotato/movie/' . $movie->_id ?>"
                    data-type="iframe"
                    data-fancybox="couchpotato"
                    style="background-image: url('<?php echo current($movie->info->images->poster) ?>')">
                    <div class="overlay"></div>
                    <div class="title">
                        <?php echo $movie->title ?>
                    </div>
                    <div class="subtitle">
                        <?php echo $movie->info->tagline ?>
                    </div>
                </a>
                <?php endforeach ?>
            <?php endif ?>
        </div>

        <a class="clone hidden_not_important">
            <div class="overlay"></div>
            <div class="title"></div>
            <div class="subtitle"></div>
        </a>
    </div>
</div>