<?php /** @var Phalcon\Mvc\View $this */ ?>

<div class="col-xs-12 col-sm-6 col-md-4 col-lg-4">
    <div class="panel panel-success database-stats" data-update-interval="<?php echo $this->settings->roborock->update_interval ?>">
        <?php $this->partial('is-loading') ?>

        <div class="panel-heading">
            <div class="btn-group pull-right">
                <button class="btn btn-default fa fa-sync rounded-not-mobile" title="Refresh" aria-label="Refresh"></button>
                <button class="btn btn-default fa fa-plus visible-xs pull-right toggle-collapse" title="Collapse/expand" aria-label="Collapse/expand"></button>
            </div>
            <h4>Database</h4>
        </div>
        <ul class="list-group hidden-xs">
            <li class="list-group-item col-xs-12">
                <div class="col-xs-4 col-sm-5 col-lg-4">
                    Uptime
                </div>
                <div class="col-xs-8 col-sm-7 col-lg-8 uptime time delayed">&hellip;</div>
            </li>
            <li class="list-group-item col-xs-12">
                <div class="col-xs-4 col-sm-5 col-lg-4">
                    Threads
                </div>
                <div class="col-xs-8 col-sm-7 col-lg-8 threads">&hellip;</div>
            </li>
            <li class="list-group-item col-xs-12">
                <div class="col-xs-4 col-sm-5 col-lg-4">
                    Questions
                </div>
                <div class="col-xs-8 col-sm-7 col-lg-8 questions">&hellip;</div>
            </li>
            <li class="list-group-item col-xs-12">
                <div class="col-xs-4 col-sm-5 col-lg-4">
                    Slow queries
                </div>
                <div class="col-xs-8 col-sm-7 col-lg-8 slow-queries">&hellip;</div>
            </li>
            <li class="list-group-item col-xs-12">
                <div class="col-xs-4 col-sm-5 col-lg-4">
                    Opens
                </div>
                <div class="col-xs-8 col-sm-7 col-lg-8 opens">&hellip;</div>
            </li>
            <li class="list-group-item col-xs-12">
                <div class="col-xs-4 col-sm-5 col-lg-4">
                    Flush tables
                </div>
                <div class="col-xs-8 col-sm-7 col-lg-8 flush-tables">&hellip;</div>
            </li>
            <li class="list-group-item col-xs-12">
                <div class="col-xs-4 col-sm-5 col-lg-4">
                    Open tables
                </div>
                <div class="col-xs-8 col-sm-7 col-lg-8 open-tables">&hellip;</div>
            </li>
            <li class="list-group-item col-xs-12">
                <div class="col-xs-4 col-sm-5 col-lg-4">
                    Queries/s
                </div>
                <div class="col-xs-8 col-sm-7 col-lg-8 queries-per-second">&hellip;</div>
            </li>
        </ul>
    </div>
</div>