<?php /** @var Phalcon\Mvc\Controller $this */ ?>

<div class="col-xs-12 col-sm-6 col-md-4 col-lg-4">
    <div class="panel panel-success kodi episodes gallery" data-rotate-interval="<?php echo $this->config->kodi->rotateEpisodesInterval ?>">
        <div class="panel-heading">
            <div class="backdrop"></div>
            <div class="btn-group pull-right">
                <button class="btn btn-default fa fa-chevron-left" title="Previous episode" aria-label="Previous episode"></button>
                <button class="btn btn-default fa fa-chevron-right rounded-not-mobile" title="Next episode" aria-label="Next episode"></button>
                <button class="btn btn-default fa fa-plus visible-xs toggle-collapse" title="Collapse/expand" aria-label="Collapse/expand"></button>
            </div>
            <h4>Latest episodes</h4>
        </div>
        <div class="panel-body hidden-xs">
            <?php $i = 0; foreach($tvshows as $tvshow) : ?>
            <a class="episode item <?php echo $i++ > 0 ? ' hidden' : 'show' ?>_not_important"
                data-fancybox="tvshows"
                data-type="iframe"
                data-nomaxwidth
                href="<?php echo $this->config->jellyfin->url .'/web/index.html#!/details?id=' . $tvshow['id'] . '&serverId=' . $tvshow['serverId'] ?>"
                title="<?php echo $tvshow['title'] ?>">
                <img src="<?php echo $this->config->jellyfin->url . '/Items/' . $tvshow['id'] . '/Images/Primary?maxHeight=377&maxWidth=348&quality=90' ?>" />
                <div class="overlay"></div>
                <div class="title" title="<?php echo $tvshow['title'] ?>">
                    <?php echo $tvshow['title'] ?>
                </div>
                <div class="subtitle">
                    <?php echo $tvshow['year'] ?>
                </div>
                <?php if ($tvshow['played']) : ?>
                <div class="fa fa-eye" title="Watched"></div>
                <?php endif ?>
            </a>
            <?php $i++;
                  endforeach ?>
        </div>
    </div>
</div>