<div class="col-xs-12 col-sm-6 col-md-4 col-lg-4">
    <div class="panel panel-success kodi movies gallery" data-rotate-interval="<?php echo $this->config->kodi->rotateMoviesInterval ?>">
        <div class="panel-heading">
            <div class="backdrop"></div>
            <div class="btn-group pull-right">
                <button class="btn btn-default fa fa-chevron-left"></button>
                <button class="btn btn-default fa fa-chevron-right rounded-not-mobile"></button>
                <button class="btn btn-default fa fa-plus visible-xs toggle-collapse"></button>
            </div>
            <h4>Latest movies</h4>
        </div>
        <div class="panel-body hidden-xs">
            <?php $i = 0; foreach($movies as $movie) : ?>
            <a class="movie item <?php echo $i++ > 0 ? 'hidden' : 'show' ?>_not_important"
                data-fancybox="movies"
                data-type="iframe"
                href="<?php echo $this->config->application->baseUri .'kodi/movie/' . $movie->idMovie ?>"
                title="<?php echo $movie->c00 ?>"
                style="background-image: url('<?php echo $this->config->application->baseUri . (!empty($movie->c08) ? 'kodi/getImage/movies/thumb/' . $movie->idMovie : 'img/icons/unknown.jpg')  ?>')">
                <div class="overlay"></div>
                <div class="title" title="<?php echo $movie->c00 ?>">
                    <?php echo $movie->c00 ?>
                </div>
                <div class="subtitle" title="<?php echo $movie->c03 ?>">
                    <?php echo $movie->c03 ?>
                </div>

                <?php if(!empty($movie->getFiles()[0]->lastPlayed)) : ?>
                <div class="fa fa-eye" title="Watched"></div>
                <?php endif ?>
            </a>
            <?php endforeach ?>
        </div>
    </div>
</div>