<div class="col-xs-12 col-sm-6 col-md-4 col-lg-4">
    <div class="panel panel-success kodi episodes gallery" data-rotate-interval="<?php echo $this->config->kodi->rotateEpisodesInterval ?>">
        <div class="panel-heading">
            <div class="backdrop"></div>
            <div class="btn-group pull-right">
                <button class="btn btn-default fa fa-chevron-left"></button>
                <button class="btn btn-default fa fa-chevron-right rounded-not-mobile"></button>
                <button class="btn btn-default fa fa-plus visible-xs toggle-collapse"></button>
            </div>
            <h4>Latest episodes</h4>
        </div>
        <div class="panel-body hidden-xs">
            <?php $i = 0; foreach($episodes as $episode) :
                       ?>
            <a class="episode item <?php echo $i++ > 0 ? ' hidden' : 'show' ?>_not_important"
                data-fancybox="episodes"
                data-type="iframe"
                href="<?php echo $this->config->application->baseUri .'kodi/episode/' . $episode->idEpisode ?>"
                title="<?php echo utf8_encode($episode->c00) ?>"
                style="background-image: url('<?php echo $this->config->application->baseUri . (!empty($episode->c06) ? 'kodi/getImage/episodes/thumb/' . $episode->idEpisode : 'img/icons/unknown.jpg')  ?>')">
                <div class="overlay"></div>
                <div class="title" title="<?php echo $title = utf8_encode($episode->strTitle) ?>">
                    <?php echo $title ?>
                </div>
                <div class="subtitle" title="<?php echo $title = sprintf('%02d', $episode->c12) . 'E' . sprintf('%02d', $episode->c13) . ' - ' . utf8_encode($episode->c00) ?>">
                    <?php echo $title ?>
                </div>

                <?php if(!empty($episode->getFiles()[0]->lastPlayed)) : ?>
                <div class="fa fa-eye" title="Watched"></div>
                <?php endif ?>
            </a>
            <?php $i++;
                  endforeach ?>
        </div>
    </div>
</div>