<div class="col-xs-12 col-sm-6 col-md-4 col-lg-4">
    <div class="panel panel-success kodi albums gallery" data-rotate-interval="<?php echo $this->config->kodi->rotateAlbumsInterval ?>">
        <div class="panel-heading">
            <div class="backdrop"></div>
            <div class="btn-group pull-right">
                <button class="btn btn-default fa fa-chevron-left"></button>
                <button class="btn btn-default fa fa-chevron-right rounded-not-mobile"></button>
                <button class="btn btn-default fa fa-plus visible-xs pull-right toggle-collapse"></button>
            </div>
            <h4>Latest albums</h4>
        </div>
        <div class="panel-body hidden-xs">
            <?php $i = 0; foreach($albums as $album) : ?>
            <a class="album item <?php echo $i++ > 0 ? ' hidden' : 'show' ?>_not_important"
                data-fancybox="albums"
                data-type="iframe"
                href="<?php echo $this->config->application->baseUri .'kodi/album/' . $album->idAlbum ?>"
                title="<?php echo $album->strAlbum ?>"
                style="background-image: url('<?php echo $this->config->application->baseUri . (!empty($album->strImage) ? 'kodi/getImage/albums/thumb/' . $album->idAlbum : 'img/icons/unknown.jpg')  ?>')">
                <div class="overlay"></div>
                <div class="title" title="<?php echo $album->strArtists ?>">
                    <?php echo $album->strAlbum ?>
                </div>
                <div class="subtitle" title="<?php echo $album->strAlbum ?>">
                    <?php echo $album->strAlbum ?>
                </div>
            </a>
            <?php $i++;
                  endforeach ?>
        </div>
    </div>
</div>