<?php /** @var Phalcon\Mvc\Controller $this */ ?>

<div class="col-xs-12 col-sm-6 col-md-4 col-lg-4">
    <div class="panel panel-success opcache chartist">
        <div class="panel-heading">
            <div class="btn-group pull-right">
                <button class="btn btn-default fa fa-chevron-left" title="Previous chart" aria-label="Previous chart"></button>
                <button class="btn btn-default fa fa-chevron-right" title="Next chart" aria-label="Next chart"></button>
                <a href="<?php echo $this->config->application->baseUri ?>opcache/details" data-fancybox data-type="iframe" class="btn btn-default fa fa-chart-bar rounded-not-mobile" title="Details"></a>
                <button class="btn btn-default fa fa-plus visible-xs pull-right toggle-collapse" title="Collapse/expand" aria-label="Collapse/expand"></button>
            </div>
            <h4>Opcache</h4>
        </div>
        <div class="panel-body hidden-xs">
            <div class="graph">
				<h4>Memory</h4>
			</div>
        </div>
    </div>
</div>