<?php /** @var Phalcon\Mvc\View $this */ ?>

<div class="col-xs-12 col-sm-6 col-md-4 col-lg-4">
    <div class="panel panel-success sysinfo" data-distro-icon-base="<?php echo $this->config->phpsysinfo->URL ?>">
        <div class="panel-heading">
            <div class="btn-group pull-right">
                <a href="javascript:;" data-fancybox data-src="#hardware" class="btn btn-default fa fa-wrench" title="Hardware"></a>
                <button class="btn btn-default fa fa-sync rounded-not-mobile" title="Refresh" aria-label="Refresh"></button>
                <button class="btn btn-default fa fa-minus visible-xs toggle-collapse" title="Collapse/expand" aria-label="Collapse/expand"></button>
            </div>
            <h4>System info</h4>
        </div>
        <ul class="list-group">
            <li class="list-group-item col-xs-12">
                <div class="col-xs-3">Host</div>
                <div class="col-xs-9 host">&hellip;</div>
            </li>

            <li class="list-group-item col-xs-12 col-lg-12 os">
                <div class="col-xs-3">OS</div>
                <div class="col-xs-9 distro">
                    <span class="pull-left">&hellip;</span>
                    <div class="icon pull-right"></div>
                </div>
            </li>

            <li class="list-group-item col-xs-12">
                <div class="col-xs-3">Uptime</div>
                <div class="col-xs-9 time delayed">&hellip;</div>
            </li>

            <li class="list-group-item col-xs-12">
                <div class="col-xs-3">Kernel</div>
                <div class="col-xs-9 kernel">&hellip;</div>
            </li>

            <li class="list-group-item col-xs-12">
                <div class="col-xs-3">Updates</div>
                <div class="col-xs-9 value update">
                    <span class="label label-default packages" title="Update packages">
                        Packages:
                        <span class="value">-</span>
                    </span>
                    <span class="label label-default security" title="Update security">
                        Security:
                        <span class="value">-</span>
                    </span>
                </div>
            </li>

            <li class="list-group-item col-xs-12">
                <div class="col-xs-3 ">RAM</div>
                <div class="col-xs-9">
                    <div class="progress ram">
                        <div class="progress-bar progress-bar-success progress-bar-striped" role="progressbar"></div>
                        <div class="percent">
                            <span></span>% used
                        </div>
                    </div>
                </div>
            </li>

            <li class="list-group-item col-xs-12">
                <div class="col-xs-3 ">Swap</div>
                <div class="col-xs-9">
                    <div class="progress swap">
                        <div class="progress-bar progress-bar-success progress-bar-striped" role="progressbar"></div>
                        <div class="percent">
                            <span></span>% used
                        </div>
                    </div>
                </div>
            </li>
        </ul>
    </div>
</div>

<?php $this->partial('index/partials/phpsysinfo_hardware') ?>