
<div class="col-xs-12 col-sm-4 col-lg-4">
    <div class="panel panel-success pull-left processes"
        data-phpsysinfo-url="<?php echo $this->config->phpsysinfo->URL ?>"
        data-phpsysinfo-username="<?php echo $this->config->phpsysinfo->username ?>"
        data-phpsysinfo-password="<?php echo $this->config->phpsysinfo->password ?>">
        <div class="panel-heading">
            <div class="btn-group pull-right">
                <button class="btn btn-default fa fa-sync rounded-not-mobile"></button>
                <button class="btn btn-default fa fa-plus visible-xs toggle-collapse"></button>
            </div>
            <h4>Processes</h4>
        </div>
        <ul class="list-group hidden-xs">
            <?php foreach($phpsysinfoData->Plugins->Plugin_PSStatus->Process as $process) : ?>
            <li class="list-group-item col-xs-12 col-md-12">
                <div class="col-xs-10">
                    <?php echo $process->{'@attributes'}->Name ?>
                </div>
                <div class="col-xs-2 text-right">
                    <?php if($process->{'@attributes'}->Status == '1') : ?>
                    <span class="label label-success">On</span>
                    <?php else : ?>
                    <span class="label label-danger">Off</span>
                    <?php endif ?>
                </div>
            </li>
            <?php endforeach ?>
        </ul>
    </div>
</div>
