<?php /** @var Phalcon\Mvc\Controller $this */ ?>

<div class="col-xs-12 col-sm-12 col-md-5 col-lg-5">
    <div class="panel panel-success harddisks">
        <?php $this->partial('is-loading') ?>

        <div class="panel-heading">
            <div class="btn-group pull-right">
                <button class="btn btn-default fa fa-sync rounded-not-mobile" title="Refresh" aria-label="Refresh"></button>
                <button class="btn btn-default fa fa-plus visible-xs toggle-collapse" title="Collapse/expand" aria-label="Collapse/expand"></button>
            </div>
            <h4>Disk usage</h4>
        </div>
        <ul class="list-group hidden-xs">
            <li class="list-group-item col-xs-12 hidden clone">
                <div class="col-xs-5 col-md-5 col-lg-3 name"></div>
                <div class="col-xs-7 col-md-7 col-lg-9">
                    <div class="progress">
                        <div class="progress-bar progress-bar-striped" role="progressbar"></div>
                        <div class="percent"></div>
                    </div>
                </div>
            </li>
        </ul>
    </div>
</div>
