<?php /** @var Phalcon\Mvc\View $this */ ?>

<div class="col-xs-12 col-sm-6 col-md-4 col-lg-4">
    <div class="panel panel-success pull-left pulseway"
        data-systems="<?php echo $this->config->pulseway->systems ?>"
        data-updateinterval="<?php echo $this->config->pulseway->updateInterval ?>">
        <?php $this->partial('is-loading') ?>

        <div class="panel-heading">
            <div class="btn-group pull-right">
                <button class="btn btn-default fa fa-sync rounded-not-mobile" title="Refresh" aria-label="Refresh"></button>
                <button class="btn btn-default fa fa-plus visible-xs pull-right toggle-collapse" title="Collapse/expand" aria-label="Collapse/expand"></button>
            </div>
            <h4>Pulseway</h4>
        </div>
        <ul class="list-group hidden-xs">
            <li class="list-group-item col-xs-12 hidden system">
                <div class="col-xs-1 icon">
                    <i></i>
                </div>
                <div class="col-xs-4 name">
                    <span class="bs-tooltip"></span>
                </div>
                <div class="col-xs-7 value">
                    Uptime:
                    <span></span>
                </div>
            </li>
        </ul>
    </div>
</div>