<?php /** @var Phalcon\Mvc\View $this */ ?>

<div class="col-xs-12 col-sm-8 col-lg-8">
    <div class="panel panel-success cpu">
        <?php $this->partial('is-loading') ?>

        <div class="panel-heading">
            <button class="btn btn-default fa fa-plus visible-xs pull-right toggle-collapse" title="Collapse/expand" aria-label="Collapse/expand"></button>
            <h4>CPU</h4>
        </div>
        <div class="panel-body hidden-xs">
            <iframe data-src="<?php echo $this->settings->rcpu->url ?>" title="rCPU"></iframe>
        </div>
    </div>
</div>