
<div class="col-xs-12 col-sm-6 col-md-4 col-lg-4">
    <div class="panel panel-success pull-left snmp">
        <div class="panel-heading">
            <div class="btn-group pull-right">
                <button class="btn btn-default fa fa-chevron-left"></button>
                <button class="btn btn-default fa fa-chevron-right"></button>
                <a href="<?php echo $this->config->application->baseUri ?>snmp/details" data-fancybox data-type="iframe" class="btn btn-default fa fa-chart-bar rounded-not-mobile"></a>
                <button class="btn btn-default fa fa-plus visible-xs pull-right toggle-collapse"></button>
            </div>
            <h4>
                <?php echo $snmpHosts[0]->name ?>
            </h4>
        </div>
        <div>
            <?php $i = 0; foreach($snmpHosts as $host) :?>
            <div class="host <?php echo $i++ > 0 ? 'hidden' : 'show' ?>_not_important" data-name="<?php echo $host->name ?>">
                <ul class="list-group hidden-xs">
                    <?php $records = $host->getValues(true); foreach($records as $record) : ?>
                    <li class="list-group-item col-xs-12 col-lg-12">
                        <div class="col-xs-4">
                            <?php echo  $record['label'] ?>
                        </div>
                        <?php list($type, $values) = $host->formatOidValues($record) ?>
                        <div class="col-xs-8 value <?php echo ($type == 'timeticks' ? 'time' : '') ?>">
                            <?php echo implode(', ', $values) ?>
                        </div>
                    </li>
                    <?php endforeach ?>
                </ul>
            </div>

            <?php endforeach ?>
        </div>
    </div>
</div>