<?php /** @var Phalcon\Mvc\Controller $this */ ?>

<div class="col-xs-12 col-sm-6 col-md-4 col-lg-4">
    <div class="panel panel-success pull-left snmp" data-update-interval="<?php echo $this->settings->snmp->update_interval ?>">
        <div class="panel-heading">
            <div class="btn-group pull-right">
                <button class="btn btn-default fa fa-chevron-left" title="Previous host" aria-label="Previous host"></button>
                <button class="btn btn-default fa fa-chevron-right" title="Next host" aria-label="Next host"></button>
                <a href="<?php echo $this->settings->application->base_uri ?>snmp/details/<?php echo $snmpHosts[0]->id ?>" data-fancybox data-type="iframe" class="btn btn-default fa fa-chart-bar" title="Details"></a>
                <button class="btn btn-default fa fa-sync rounded-not-mobile" title="Refresh" aria-label="Refresh"></button>
                <button class="btn btn-default fa fa-plus visible-xs pull-right toggle-collapse" title="Collapse/expand" aria-label="Collapse/expand"></button>
            </div>
            <h4>SNMP</h4>
        </div>
        <div>
            <?php $i = 0; foreach($snmpHosts as $host) :?>
            <div class="host pull-left <?php echo $i++ > 0 ? 'hidden' : 'show' ?>_not_important" data-name="<?php echo $host->name ?>" data-id="<?php echo $host->id ?>"></div>
            <?php endforeach ?>
        </div>
    </div>
</div>