<div class="col-xs-12 col-sm-6 col-md-4 col-lg-4">
    <div class="panel panel-success verisure" data-update-interval="<?php echo $this->config->verisure->updateInterval ?>">
        <div class="panel-heading">
            <div class="btn-group pull-right">
                <a href="<?php echo $this->config->application->baseUri ?>verisure/details/" data-fancybox data-type="iframe" class="btn btn-default fa fa-chart-bar" title="Details"></a>
                <a href="<?php echo $this->config->verisure->URL ?>" target="_blank" class="btn btn-default fa fa-globe" rel="noreferrer" title="MyPages"></a>
                <?php if($verisure_images->totalNumberOfImageSeries > 0) : ?>
                <button class="btn btn-default fa fa-camera" title="Photos" aria-label="Photos" data-photos='<?php echo json_encode($verisure_images) ?>'></button>
                <?php endif ?>
                <button class="btn btn-default fa fa-sync rounded-not-mobile" title="Refresh" aria-label="Refresh"></button>
                <button class="btn btn-default fa fa-plus visible-xs pull-right toggle-collapse" title="Collapse/expand" aria-label="Collapse/expand"></button>
            </div>
            <h4>Verisure</h4>
        </div>
        <div class="panel-body hidden-xs">
            <div class="top">
                <div class="text-center" id="amstate">
                    <?php if ($verisure->armState->statusType == 'DISARMED') : ?>
                    <i class="fa fa-verisure-disarmed text-danger"></i>
                    <?php elseif ($verisure->armState->statusType == 'ARMED') : ?>
                    <i class="fa fa-verisure-away text-success"></i>
                    <?php else : ?>
                    <i class="fa fa-verisure-stay text-warning"></i>
                    <?php endif ?>
                </div>
                <div>
                    <?php foreach($verisure->climateValues as $value) : ?>
                    <div class="temp text-right" id="<?php echo str_replace(' ', '_', $value->deviceLabel) ?>">
                        <span class="text-bold">
                            <?php echo $value->deviceArea ?>
                        </span> :
                        <span class="value">
                            <?php echo $value->temperature ?>&deg;
                        </span>
                        <i class="fa fa-thermometer-half <?php echo $value->cssClass ?>"></i>
                    </div>
                    <?php endforeach?>
                </div>
            </div>
            <ul class="list-group">
                <li class="list-group-item col-xs-12">
                    <div class="col-xs-4 col-sm-5 col-lg-4">
                        Status
                    </div>
                    <div class="col-xs-8 col-sm-7 col-lg-8 status">
                        <?php echo str_replace('_', ' ', ucfirst(strtolower($verisure->armState->statusType))) ?>
                    </div>
                </li>
                <li class="list-group-item col-xs-12">
                    <div class="col-xs-4 col-sm-5 col-lg-4">
                        Changed by
                    </div>
                    <div class="col-xs-8 col-sm-7 col-lg-8 name">
                        <?php echo (isset($verisure->armState->name) ? $verisure->armState->name : 'Unknown') ?>
                    </div>
                </li>
                <li class="list-group-item col-xs-12">
                    <div class="col-xs-4 col-sm-5 col-lg-4">
                        Changed on
                    </div>
                    <div class="col-xs-8 col-sm-7 col-lg-8 date">
                        <?php echo date('d-m-Y H:i', strtotime($verisure->armState->date)) ?>
                    </div>
                </li>
                <li class="list-group-item col-xs-12">
                    <div class="col-xs-4 col-sm-5 col-lg-4">
                        Changed with
                    </div>
                    <div class="col-xs-8 col-sm-7 col-lg-8 via">
                        <?php echo str_replace('_', ' ', ucfirst(strtolower($verisure->armState->changedVia))) ?>
                    </div>
                </li>
            </ul>
        </div>
    </div>
</div>