<?php /** @var Phalcon\Mvc\View $this */ ?>

<div class="col-xs-12 col-sm-6 col-md-4 col-lg-4">
    <div class="panel panel-success pull-left youless"
        data-max="2000"
        data-updateinterval="<?php echo $this->settings->youless->update_interval ?>"
        data-primary="<?php echo $this->settings->youless->threshold_primary ?>"
        data-warn="<?php echo $this->settings->youless->threshold_warning ?>"
        data-danger="<?php echo $this->settings->youless->threshold_danger ?>">
        <?php $this->partial('is-loading') ?>

        <div class="panel-heading">
            <div class="btn-group pull-right">
                <a href="<?php echo (!empty($this->settings->youless->charts_url) ? $this->settings->youless->charts_url : $this->settings->youless->url) ?>" 
                   target="_blank" class="btn btn-default fa fa-globe" rel="noreferrer" title="Youless"></a>
                <button class="btn btn-default fa fa-sync rounded-not-mobile" title="Refresh" aria-label="Refresh"></button>
                <button class="btn btn-default fa fa-plus visible-xs pull-right toggle-collapse" title="Collapse/expand" aria-label="Collapse/expand"></button>
            </div>
            <h4>Youless</h4>
        </div>
        <ul class="list-group hidden-xs">
            <li class="list-group-item col-xs-12 counter">
                <div class="col-xs-4 col-sm-5 col-lg-4">
                    Counter
                </div>
                <div class="col-xs-8 col-sm-7 col-lg-8 value">
                    &hellip;
                </div>

            </li>
            <li class="list-group-item col-xs-12 power">
                <div class="col-xs-4 col-sm-5 col-lg-4">
                    Current
                </div>
                <div class="col-xs-8 col-sm-7 col-lg-8">
                    <div class="value">
                        <span>&hellip;</span>
                        <i class="fa fa-bolt"></i>
                    </div>
                </div>
            </li>
        </ul>
    </div>
</div>