<?php /** @var Phalcon\Mvc\Controller $this */ ?>

<div class="col-xs-12 col-sm-6 col-md-4 col-lg-4">
    <div class="panel panel-success pull-left youless"
        data-max="2000"
        data-updateinterval="<?php echo $this->config->youless->updateInterval ?>"
        data-primary="<?php echo $this->config->youless->primaryThreshold ?>"
        data-warn="<?php echo $this->config->youless->warnThreshold ?>"
        data-danger="<?php echo $this->config->youless->dangerThreshold ?>">
        <div class="panel-heading">
            <div class="btn-group pull-right">
                <a href="<?php echo (!empty($this->config->youless->chartsURL) ? $this->config->youless->chartsURL : $this->config->youless->URL) ?>" target="_blank" class="btn btn-default fa fa-globe" rel="noreferrer" title="Youless"></a>
                <button class="btn btn-default fa fa-sync rounded-not-mobile" title="Refresh" aria-label="Refresh"></button>
                <button class="btn btn-default fa fa-plus visible-xs pull-right toggle-collapse" title="Collapse/expand" aria-label="Collapse/expand"></button>
            </div>
            <h4>
                <a href="<?php echo $this->config->youless->URL ?>" target="_blank">
                    Youless
                </a>
            </h4>
        </div>
        <ul class="list-group hidden-xs">
            <li class="list-group-item col-xs-12">
                <div class="col-xs-4 col-sm-5 col-lg-4">
                    Counter
                </div>
                <div class="col-xs-8 col-sm-7 col-lg-8">
                    <?php echo $youlessStats->cnt ?>
                </div>

            </li>
            <li class="list-group-item col-xs-12 power">
                <div class="col-xs-4 col-sm-5 col-lg-4">
                    Current
                </div>
                <div class="col-xs-8 col-sm-7 col-lg-8">
                    <div class="value <?php echo Chell\Models\Youless::getTextClass($this->config, $youlessStats->pwr) ?>">
                        <span><?php echo $youlessStats->pwr ?></span>
                        <i class="fa fa-bolt"></i>
                    </div>
                </div>
            </li>
        </ul>
    </div>
</div>