<?php /** @var $youlessPowerUsage string */ ?>

<div class="col-xs-12 col-sm-6 col-md-4 col-lg-4">
    <div class="panel panel-success pull-left youless"
        data-power="<?php echo $youlessPowerUsage ?>"
        data-max="2000"
        data-updateinterval="<?php echo $this->config->youless->updateInterval ?>"
        data-primary="<?php echo $this->config->youless->primaryThreshold ?>"
        data-warn="<?php echo $this->config->youless->warnThreshold ?>"
        data-danger="<?php echo $this->config->youless->dangerThreshold ?>">
        <div class="panel-heading">
            <div class="btn-group pull-right">
                <button class="btn btn-default fa fa-sync rounded-not-mobile" title="Refresh" aria-label="Refresh"></button>
                <button class="btn btn-default fa fa-plus visible-xs pull-right toggle-collapse" title="Collapse/expand" aria-label="Collapse/expand"></button>
            </div>
            <h4>
                <a href="<?php echo $this->config->youless->URL ?>" target="_blank">
                    Youless
                </a>
            </h4>
        </div>
        <div class="panel-body hidden-xs">
            Current power usage
            <div class="power <?php echo Chell\Models\Youless::getTextClass($this->config, $youlessPowerUsage) ?>">
                <span class="value"><?php echo $youlessPowerUsage ?></span>
                <i class="fa fa-bolt"></i>
            </div>
        </div>
    </div>
</div>