<?php
/**
 * @var Phalcon\Mvc\View $this
 * @var $motionModifiedTime string
 */
?>

<div class="panel panel-success motion gallery" data-motion-interval="<?php echo $this->settings->motion->update_interval ?>">
    <div class="panel-heading">
        <div class="backdrop"></div>
        <div class="btn-group pull-right">
            <?php $this->partial('index/default_widget_buttons', ['hasRefresh' => true, 'widgetId' => $widget->id]) ?>
        </div>
        <h4 class="truncate-text" title="Motion">Motion</h4>
    </div>
    <div class="panel-body hidden-xs">
        <a class="item" href="<?php echo $this->settings->motion->url ?>" target="_blank"
            style="background-image: url('<?php echo $this->url->get('motion/?t=' . time()) ?>')">
            <div class="overlay"></div>
            <div class="title">Modified on</div>
            <div class="subtitle">
                <?php echo $motionModifiedTime ?>
            </div>
        </a>
    </div>
</div>
