<?php /** @var Phalcon\Mvc\Controller $this */ ?>

<div id="hardware" class="tab-pane fade active in">
    <ul class="list-group panel-success cpu-model pull-left">
        <li class="list-group-item col-xs-12">
            <div class="col-xs-3">CPU</div>
            <div class="col-xs-9 value">
                &hellip;
            </div>
        </li>

        <li class="list-group-item col-xs-12 motherboard">
            <div class="col-xs-3">Motherboard</div>
            <div class="col-xs-9 value">
                &hellip;
            </div>
        </li>

        <li class="list-group-item col-xs-12 cpu-cores clone hidden">
            <div class="cpu-core col-xs-3">
                &hellip;
            </div>
            <div class="core-stats col-xs-9">
                <div class="col-xs-6 core-temp-label">Temp: </div>
                <div class="core-temp col-xs-6">
                    &hellip;
                </div>
                <div class="col-xs-6">Current: </div>
                <div class="core-current col-xs-6">
                    &hellip;
                </div>
                <div class="col-xs-6">Min: </div>
                <div class="core-min col-xs-6">
                    &hellip;
                </div>
                <div class="col-xs-6">Max: </div>
                <div class="core-max col-xs-6">
                    &hellip;
                </div>
            </div>
        </li>

        <li class="list-group-item col-xs-12 network">
            <div class="col-xs-3">Network</div>
            <div class="lan-stats col-xs-9">
                <div class="clone hidden">
                    <div class="col-xs-6">Name: </div>
                    <div class="lan-name col-xs-6">
                        &hellip;
                    </div>
                    <div class="col-xs-6">IP: </div>
                    <div class="lan-ip col-xs-6">
                        &hellip;
                    </div>
                    <div class="col-xs-6">MAC: </div>
                    <div class="lan-mac col-xs-6">
                        &hellip;
                    </div>
                    <div class="col-xs-6">Speed: </div>
                    <div class="lan-speed col-xs-6">
                        &hellip;
                    </div>
                    <div class="col-xs-6">Rx: </div>
                    <div class="lan-rx col-xs-6">
                        &hellip;
                    </div>
                    <div class="col-xs-6">Tx: </div>
                    <div class="lan-tx col-xs-6">
                        &hellip;
                    </div>
                </div>
            </div>
        </li>
    </ul>
</div>
