<?php $this->partial('index/partials/indexAction/phpsysinfo_sysinfo') ?>
<?php $this->partial('index/partials/indexAction/devices') ?>
<div class="clearfix visible-sm"></div>
<?php $this->partial('index/partials/indexAction/phpsysinfo_disks') ?>
<div class="clearfix visible-lg visible-md"></div>
<?php $this->partial('index/partials/indexAction/phpsysinfo_processes') ?>
<?php $this->partial('index/partials/indexAction/rcpu') ?>

<?php $this->partial('index/partials/indexAction/dialog-shutdown') ?>
<?php $this->partial('index/partials/indexAction/dialog-confirm') ?>
<div class="clearfix"></div>
<?php $this->partial('index/partials/indexAction/latest_movies') ?>
<?php $this->partial('index/partials/indexAction/latest_episodes') ?>
<?php $this->partial('index/partials/indexAction/latest_albums') ?>
<?php $this->partial('index/partials/indexAction/transmission') ?>