<?php
/** @var Phalcon\Mvc\Controller $this */
$themeColor = '#4f4f4f';
$faviconDir = 'img/icons/favicons/';
$screenshotDir = 'img/screenshots/';
?>
{
    "name": "<?php echo $this->settings->application->title ?>",
    "description": "A PHP portal to aggregate all your server services.",
    "short_name": "Server Portal",
    "start_url": "<?php echo $this->settings->application->base_uri ?>",
    "icons": [
        {
            "src": "<?php echo $this->settings->application->base_uri . $faviconDir ?>android-chrome-192x192.png",
            "sizes": "192x192",
            "type": "image/png"
        },
        {
            "src": "<?php echo $this->settings->application->base_uri . $faviconDir ?>android-chrome-512x512.png",
            "sizes": "512x512",
            "type": "image/png"
        },
        {
            "src": "<?php echo $this->settings->application->base_uri . $faviconDir ?>android-chrome-maskable-512x512.png",
            "sizes": "512x512",
            "type": "image/png",
            "purpose": "maskable"
        }
    ],
    "screenshots": [
        {
            "src": "<?php echo $this->settings->application->base_uri . $screenshotDir ?>home.png",
            "sizes": "360x642",
            "type": "image/png"
        },
        {
            "src": "<?php echo $this->settings->application->base_uri . $screenshotDir ?>settings.png",
            "sizes": "360x642",
            "type": "image/png"
        }
    ],
    "theme_color": "<?php echo $themeColor ?>",
    "background_color": "<?php echo $themeColor ?>",
    "display": "standalone"
}