<?php
/** @var Phalcon\Mvc\Controller $this */
$themeColor = '#4f4f4f';
$faviconDir = 'img/icons/favicons/';
$screenshotDir = 'img/screenshots/';
?>
{
    "name": "<?php echo $this->settings->application->title->value ?>",
    "short_name": "Server Portal",
    "description": "A PHP portal to aggregate all your server services.",
    "start_url": "<?php echo $this->url->get() ?>",
    "icons": [
        {
            "src": "<?php echo $this->url->get($faviconDir . 'android-chrome-192x192.png') ?>",
            "sizes": "192x192",
            "type": "image/png"
        },
        {
            "src": "<?php echo $this->url->get($faviconDir . 'android-chrome-512x512.png') ?>",
            "sizes": "512x512",
            "type": "image/png"
        },
        {
            "src": "<?php echo $this->url->get($faviconDir . 'android-chrome-maskable-512x512.png') ?>",
            "sizes": "512x512",
            "type": "image/png",
            "purpose": "maskable"
        }
    ],
    "screenshots": [
        {
            "src": "<?php echo $this->url->get($screenshotDir. 'mobile_home.png') ?>",
            "sizes": "360x640",
            "type": "image/png"
        },
        {
            "src": "<?php echo $this->url->get($screenshotDir . 'mobile_menu.png') ?>",
            "sizes": "360x640",
            "type": "image/png"
        }
    ],
    "shortcuts": [
        {
            "name": "Settings",
            "Description": "The settings of <?php echo $this->settings->application->title->value ?>",
            "url": "<?php echo $this->url->get('settings') ?>",
            "icons": [
                {
                    "type": "image/png",
                    "sizes": "96x96",
                    "src": "<?php echo $this->url->get('img/icons/settings.png') ?>",
                    "purpose": "any"
                }
            ]
        }
    ],
    "theme_color": "<?php echo $themeColor ?>",
    "background_color": "<?php echo $themeColor ?>",
    "display": "standalone"
}