<?php /** @var Phalcon\Mvc\Controller $this */ ?>

{
    "name": "<?php echo $this->config->application->title ?>",
    "short_name": "Server Portal",
    "start_url": "<?php echo $this->config->application->baseUri ?>",
    "icons": [
        {
            "src": "<?php echo $this->config->application->baseUri ?>img/icons/favicons/android-chrome-36x36.png",
            "sizes": "36x36",
            "type": "image/png"
        },
        {
            "src": "<?php echo $this->config->application->baseUri ?>img/icons/favicons/android-chrome-48x48.png",
            "sizes": "48x48",
            "type": "image/png"
        },
        {
            "src": "<?php echo $this->config->application->baseUri ?>img/icons/favicons/android-chrome-72x72.png",
            "sizes": "72x72",
            "type": "image/png"
        },
        {
            "src": "<?php echo $this->config->application->baseUri ?>img/icons/favicons/android-chrome-96x96.png",
            "sizes": "96x96",
            "type": "image/png"
        },
        {
            "src": "<?php echo $this->config->application->baseUri ?>img/icons/favicons/android-chrome-144x144.png",
            "sizes": "144x144",
            "type": "image/png"
        },
        {
            "src": "<?php echo $this->config->application->baseUri ?>img/icons/favicons/android-chrome-192x192.png",
            "sizes": "192x192",
            "type": "image/png",
            "purpose": "any maskable"
        },
        {
            "src": "<?php echo $this->config->application->baseUri ?>img/icons/favicons/android-chrome-256x256.png",
            "sizes": "256x256",
            "type": "image/png"
        },
        {
            "src": "<?php echo $this->config->application->baseUri ?>img/icons/favicons/android-chrome-384x384.png",
            "sizes": "384x384",
            "type": "image/png"
        },
        {
            "src": "<?php echo $this->config->application->baseUri ?>img/icons/favicons/android-chrome-512x512.png",
            "sizes": "512x512",
            "type": "image/png"
        }
    ],
    "theme_color": "#4f4f4f",
    "background_color": "#4f4f4f",
    "display": "standalone"
}