<?php /** @var Phalcon\Mvc\View $this */ ?>

<div class="panel panel-success with-nav-tabs" id="verisure-details">
    <div class="panel-heading">
        <h4 class="pull-left hidden-xs">Verisure</h4>
        <ul class="nav nav-tabs pull-right">
            <li class="active">
                <a data-toggle="tab" href="#doorwindow">
                    Doors &amp; windows
                </a>
            </li>
            <li>
                <a data-toggle="tab" href="#log">
                    Log
                </a>
            </li>
            <li>
                <a data-toggle="tab" href="#firmware">
                    Firmware
                </a>
            </li>
        </ul>
    </div>
    <div class="tab-content">
        <?php $this->partial('verisure/partials/doorwindow') ?>
        <?php $this->partial('verisure/partials/log') ?>
        <?php $this->partial('verisure/partials/firmware') ?>
    </div>
</div>