<?php /** @var Phalcon\Mvc\View $this */ ?>

<div class="panel panel-success verisure" data-update-interval="<?php echo $this->settings->verisure->update_interval ?>">
    <?php $this->partial('is-loading') ?>

    <div class="panel-heading">
        <div class="btn-group pull-right">
            <a href="<?php echo $this->url->get('verisure/details/') ?>" data-fancybox data-type="iframe" class="btn btn-default fa fa-chart-bar" title="Details"></a>
            <button class="btn btn-default fa fa-camera" title="Take photo" aria-label="Take photo"></button>
            <button class="btn btn-default fa fa-image hidden" title="Photos" aria-label="Photos"></button>
            <?php $this->partial('index/default_widget_buttons', ['hasRefresh' => true, 'widgetId' => $widget->id]) ?>
        </div>
        <h4 class="truncate-text" title="Verisure">Verisure</h4>
    </div>
    <div class="panel-body hidden-xs">
        <div class="top">
            <div class="text-center" id="armstate">
                <button class="fa fa-verisure-disarmed invisible"></button>
            </div>
            <div class="temps">
                <div class="temp text-right clone hidden">
                    <div class="text-bold area">
                        <span></span>
                        <i class="fa fa-thermometer-half"></i>
                    </div>
                    <div class="value"></div>
                </div>
            </div>
        </div>
        <ul class="list-group">
            <li class="list-group-item col-xs-12">
                <div class="col-xs-4 col-sm-5 col-lg-4">
                    Status
                </div>
                <div class="col-xs-8 col-sm-7 col-lg-8 status">&hellip;</div>
            </li>
            <li class="list-group-item col-xs-12">
                <div class="col-xs-4 col-sm-5 col-lg-4">
                    Changed by
                </div>
                <div class="col-xs-8 col-sm-7 col-lg-8 name">&hellip;</div>
            </li>
            <li class="list-group-item col-xs-12">
                <div class="col-xs-4 col-sm-5 col-lg-4">
                    Changed on
                </div>
                <div class="col-xs-8 col-sm-7 col-lg-8 date">&hellip;</div>
            </li>
            <li class="list-group-item col-xs-12">
                <div class="col-xs-4 col-sm-5 col-lg-4">
                    Changed with
                </div>
                <div class="col-xs-8 col-sm-7 col-lg-8 via">&hellip;</div>
            </li>
        </ul>
    </div>
</div>

<div class="hidden_not_important" id="verisure_device_select">
    <h2>Take photo</h2>
    <div>
        <button data-device-label="" class="btn btn-primary hidden"></button>
    </div>
</div>

<div class="hidden_not_important" id="verisure_set_armstate">
    <div class="text-center">
        <i id="current_disarmed" class="fa fa-verisure-disarmed text-danger hidden" title="Disarmed"></i>
        <i id="current_away" class="btn btn-success fa fa-verisure-away text-success hidden" title="Away"></i>
        <i id="current_stay" class="btn btn-warning fa fa-verisure-stay text-warning hidden" title="Stay"></i>
        <h2>Select new arm state </h2>

        <?php if (empty($this->settings->verisure->securitycode)): ?>
        <input type="password" id="verisure_pin" value="" class="form-control" placeholder="PIN" />
        <?php endif ?>

        <div class="button-wrapper">
            <div id="arm_away" class="pull-left state-change hidden">
                <button class="btn btn-success fa fa-verisure-away" data-state="<?php echo Chell\Models\Verisure::$statusArmedAwayCode ?>"></button>
                <h3>Arm away</h3>
            </div>
            <div id="arm_stay" class="pull-left state-change hidden">
                <button class="btn btn-warning fa fa-verisure-stay" data-state="<?php echo Chell\Models\Verisure::$statusArmedStayCode ?>"></button>
                <h3>Arm stay</h3>
            </div>
            <div id="disarm" class="pull-left state-change hidden">
                <button class="btn btn-danger fa fa-verisure-disarmed" data-state="<?php echo Chell\Models\Verisure::$statusDisarmedCode ?>"></button>
                <h3>Disarm</h3>
            </div>
        </div>
    </div>
</div>