<?php
/**
 * @var Phalcon\Mvc\View        $this
 * @var Chell\Models\Devices    $device
 */
?>

<div class="panel panel-success with-nav-tabs hypervadmin" data-deviceid="<?php echo $device->id ?>">
    <div class="panel-heading ">
        <h4 class="pull-left hidden-xs">HyperVAdmin</h4>
        <ul class="nav nav-tabs pull-right">
            <li class="active">
                <a data-toggle="tab" href="#vms">
                    VMs
                    <span class="btn btn-xs btn-success">
                        <i class="fa fa-rotate"></i>
                    </span>
                </a>
            </li>
            <li>
                <a data-toggle="tab" href="#sites">
                    Sites
                    <span class="btn btn-xs btn-success">
                        <i class="fa fa-rotate"></i>
                    </span>
                </a>
            </li>
        </ul>
    </div>
    <div class="tab-content">
        <?php $this->partial('hyper_v_admin/partials/vms') ?>
        <?php $this->partial('hyper_v_admin/partials/sites') ?>
    </div>
</div>

<div class="alert" role="alert" data-alert-timeout="<?php echo $this->settings->application->alert_timeout->value ?>"></div>