<div class="panel panel-success">
    <div class="panel-heading">
        <h4>Virtual machines</h4>
    </div>
    <div class="panel-body">
        <div class="table-responsive">
            <table class="table table-striped table-hover">
                <thead>
                    <tr>
                        <th>Name</th>
                        <th>RAM</th>
                        <th>Cores</th>
                        <th style="min-width:100px">Load</th>
                        <th>MAC</th>
                        <th>Ontime</th>
                        <th class="text-right">Actions</th>
                    </tr>
                </thead>
                <tbody>
                    <?php foreach($vms as $vm) :
                              $state = \Chell\Models\HyperVAdmin::getVMState($vm->State);
                              $toggleStateURL = $this->config->application->baseUri . 'hyper_v_admin/vmToggleState/' . $vm->Name . '/';
                              $toggleStateURL .=  $state == 'enabled' ? array_search('disabled', \Chell\Models\HyperVAdmin::vmStates) :
                                  array_search('enabled', \Chell\Models\HyperVAdmin::vmStates)
                    ?>
                    <tr>
                        <td><?php echo $vm->Name ?></td>
                        <td><?php echo $vm->MemoryTotal . ' ' . $vm->MemoryAllocationUnits ?></td>
                        <td><?php echo $vm->CoresAmount ?></td>
                        <td>
                            <div class="progress">
                                <div class="progress-bar progress-bar-striped progress-bar-success" role="progressbar" style="width:<?php echo $vm->CPULoad ?>%"></div>
                                <div class="percent">
                                    <?php echo $vm->CPULoad ?>%
                                </div>
                            </div>
                        </td>
                        <td><?php echo $vm->MAC ?></td>
                        <td><?php echo $vm->GetOnTimeFormatted ?></td>
                        <td>
                            <div class="btn-group pull-right">
                                <a href="<?php echo $toggleStateURL ?>" class="btn btn-default btn-<?php echo $state == 'enabled' ? 'success' : 'danger'  ?>">
                                    <i class="fa fa-power-off"></i>
                                </a>
                            </div>
                        </td>
                    </tr>
                    <?php endforeach ?>
                </tbody>
            </table>
        </div>
    </div>
</div>
