<?php /** @var Chell\Models\SnmpRecords $records */ ?>

<div class="panel panel-success snmp-details">
    <div class="panel-heading">
        <h4 class="pull-left">
            <?php echo $host->name ?>
        </h4>
    </div>
    <ul class="list-group">
        <?php $records = $host->getValues(false); foreach($records as $record) : ?>
        <li class="list-group-item col-xs-12">
            <div class="col-xs-4">
                <?php echo $record['label'] ?>
            </div>
            <?php list($type, $values) = $host->formatOidValues($record) ?>
            <div class="col-xs-8 value <?php echo ($type == 'timeticks' ? 'time hidden_not_important' : '') ?>">
                <?php echo implode(', ', $values) ?>
            </div>
        </li>
        <?php endforeach ?>
    </ul>
</div>
