<?php
/**
 * @var string                  $hidden
 * @var Chell\Models\SnmpHosts  $host
 */
?>

<ul class="list-group <?php echo $hidden ?>">
    <li class="list-group-item col-xs-12 col-lg-12">
        <div class="col-xs-4 col-sm-5 col-lg-4">Name</div>
        <div class="col-xs-8 col-sm-7 col-lg-8 name">
            <?php echo $host->name ?>
        </div>
    </li>

    <?php $records = $host->getValues(true); foreach($records as $record) : ?>
    <li class="list-group-item col-xs-12">
        <div class="col-xs-4 col-sm-5 col-lg-4">
            <?php echo $record['label'] ?>
        </div>
        <?php
        list($type, $values) = $host->formatOidValues($record);
        $value = implode(', ', $values);
        ?>
        <div class="col-xs-8 col-sm-7 col-lg-8 value truncate-text <?php echo ($type == 'timeticks' ? 'time hidden_not_important' : '') ?> <?php echo (strlen($value) > 30 ? 'bs-tooltip" title="' . $value . '"' : null) ?>" >
            <?php echo $value ?>
        </div>
    </li>
    <?php endforeach ?>
</ul>