<ul class="list-group <?php echo (isset($snmpHosts) ? 'hidden-xs': null) ?>">
    <li class="list-group-item col-xs-12 col-lg-12">
        <div class="col-xs-4 col-sm-5 col-lg-4">Name</div>
        <div class="col-xs-8 col-sm-7 col-lg-8 name">
            <?php echo $host->name ?>
        </div>
    </li>

    <?php $records = $host->getValues(true); foreach($records as $record) : ?>
    <li class="list-group-item col-xs-12">
        <div class="col-xs-4 col-sm-5 col-lg-4">
            <?php echo  $record['label'] ?>
        </div>
        <?php list($type, $values) = $host->formatOidValues($record) ?>
        <div class="col-xs-8 col-sm-7 col-lg-8 value <?php echo ($type == 'timeticks' ? 'time hidden_not_important' : '') ?>">
            <?php echo implode(', ', $values) ?>
        </div>
    </li>
    <?php endforeach ?>
</ul>