<?php
/**
 * @var Phalcon\Mvc\Controller  $this
 * @var Chell\Models\Devices    $device
 */
?>

<div class="panel panel-success" id="settings">
    <div class="panel-heading">
        <div class="btn-group pull-left back-btn">
            <a href="<?php echo $this->url->get('settings/devices') ?>" class="btn btn-default fa fa-chevron-left" title="Go back"></a>
        </div>
        <h4 class="pull-left">
            <?php echo !empty($device->name) ? 'Edit' : 'New' ?> device
        </h4>
    </div>
    <div class="panel-body">
        <?php echo $form->renderForm('device') ?>
    </div>
</div>
