<?php /** @var Phalcon\Mvc\View $this */ ?>

<div class="col-xs-12">
    <div id="settings" class="panel panel-success hidden_not_important with-nav-tabs" data-scrollto="<?php echo $scrollto ?>">
        <div class="panel-heading">
            <h4 class="pull-left">Settings</h4>

            <ul class="nav nav-tabs pull-right hidden-xs">
                <?php foreach ($forms AS $formId => $formContent) : ?>
                <li <?php echo $activeTab == $formId ? 'class="active"' : null ?>>
                    <a data-toggle="tab" href="#<?php echo strtolower($formId) ?>">
                        <?php echo $formId ?>
                    </a>
                </li>
                <?php endforeach ?>
                <li <?php echo $activeTab == 'Devices' ? 'class="active"' : null ?>>
                    <a data-toggle="tab" href="#devices">Devices</a>
                </li>
                <?php if ($this->settings->snmp->enabled) : ?>
                <li <?php echo $activeTab == 'SNMP' ? 'class="active"' : null ?>>
                    <a data-toggle="tab" href="#snmphosts">SNMP</a>
                </li>
                <?php endif ?>
                <li <?php echo $activeTab == 'Menu' ? 'class="active"' : null ?>>
                    <a data-toggle="tab" href="#menuitems" class="pull-left">Menu</a>
                </li>
                <li <?php echo $activeTab == 'Users' ? 'class="active"' : null ?>>
                    <a data-toggle="tab" href="#users" class="pull-left">Users</a>
                </li>
                <li <?php echo $activeTab == 'Logs' ? 'class="active"' : null ?>>
                    <a data-toggle="tab" href="#logs" class="pull-left">Logs</a>
                </li>
            </ul>
            <div class="visible-xs pull-right">
                <select class="no-selectpicker form-control">
                    <?php foreach ($forms AS $formId => $formContent) : ?>
                    <option value="#<?php echo strtolower($formId) ?>" <?php echo $activeTab == $formId ? 'selected' : null ?>><?php echo $formId ?></option>
                    <?php endforeach ?> 
                    <option value="#devices" <?php echo $activeTab == 'Devices' ? 'selected' : null ?>>Devices</option>
                    <option value="#snmphosts" <?php echo $activeTab == 'SNMP' ? 'selected' : null ?>>SNMP</option>
                    <option value="#menuitems" <?php echo $activeTab == 'Menu' ? 'selected' : null ?>>Menu</option>
                    <option value="#users" <?php echo $activeTab == 'Users' ? 'selected' : null ?>>Users</option>
                    <option value="#logs" <?php echo $activeTab == 'Logs' ? 'selected' : null ?>>Logs</option>
                </select>
             </div>
        </div>
        <div class="panel-body">
            <div class="tab-content pull-left">
                <?php foreach ($forms AS $formId => $formContent) : ?>
                <div id="<?php echo strtolower($formId) ?>" class="tab-pane fade<?php echo $activeTab == $formId ? ' in active' : null ?> panel panel-square">
                    <?php echo $formContent->renderForm($formId) ?>

                </div>
                <?php endforeach ?>

                <?php $this->partial('settings/partials/devices') ?>
                <?php $this->partial('settings/partials/snmp') ?>
                <?php $this->partial('settings/partials/menuitems') ?>
                <?php $this->partial('settings/partials/users') ?>
                <?php $this->partial('settings/partials/logs') ?>
            </div>
        </div>
    </div>
</div>