<div class="panel panel-success">
    <div class="panel-heading">
        <h4>Settings</h4>
    </div>
    <div class="panel-body">
        <ul class="nav nav-tabs">
            <?php $i = 0; foreach ($forms AS $formId => $formContent) : ?>
                <li<?php echo $i++ == 0 ? ' class="active"' : null ?>>
                    <a data-toggle="tab" href="#<?php echo strtolower($formId) ?>"><?php echo $formId ?></a>
                </li>
            <?php endforeach ?>
            <li>
                <a data-toggle="tab" href="#devices">Devices</a>
            </li>
            <li>
                <a data-toggle="tab" href="#menu">Menu</a>
            </li>
        </ul>

        <div class="tab-content">
            <?php $i = 0; foreach ($forms AS $formId => $formContent) : ?>
                <form id="<?php echo strtolower($formId) ?>" action="<?php echo $formContent->getAction() ?>" method="post"
                    class="tab-pane fade<?php echo $i++ == 0 ? ' in active' : null ?> panel panel-square">
                    <?php foreach($formContent AS $element) : ?>
                    <div class="form-group row">
                        <div class="col-lg-3 col-sm-4 col-xs-12 text-right-not-xs"><?php echo $element->label() ?></div>
                        <div class="col-lg-4 col-sm-6 col-xs-12">
                            <?php echo $element ?>
                        </div>
                    </div>
                    <?php endforeach ?>

                    <div class="row">
                        <div class="col-lg-4 col-lg-offset-3 col-xs-12">
                            <button type="submit" class="btn btn-success">
                                <i class="glyphicon glyphicon-floppy-disk"></i>
                            </button>
                        </div>
                    </div>
                </form>
            <?php endforeach ?>


            <?php $this->partial('settings/partials/devices') ?>
            <?php $this->partial('settings/partials/menu') ?>
        </div>
    </div>
</div>