<?php /** @var Phalcon\Mvc\Controller $this */ ?>

<div class="panel panel-success with-nav-tabs">
    <div class="panel-heading">
        <div class="btn-group pull-left back-btn">
            <a href="<?php echo $this->config->application->baseUri ?>settings/index#snmphosts" class="btn btn-default fa fa-chevron-left" title="Go back"></a>
        </div>
        <h4 class="pull-left">
            <?php echo ($edit = !empty($host->name)) ? 'Edit' : 'New' ?> SNMP host
        </h4>

        <?php if($edit) : ?>
        <ul class="nav nav-tabs pull-right hidden-xs">
            <li class="active">
                <a data-toggle="tab" href="#general">General</a>
            </li>
            <li>
                <a data-toggle="tab" href="#records">Records</a>
            </li>
        </ul>
        <?php endif ?>
    </div>
    <div class="panel-body">
        <div class="tab-content">
            <div id="general" class="tab-pane fade panel panel-square in active">
                <form action="<?php echo $form->getAction() ?>" method="post">
                    <?php foreach($form AS $element) : ?>
                    <div class="form-group row<?php echo ($hasErrors = $form->hasMessagesFor($element->getName())) ? ' has-error' : null ?>">
                        <div class="col-lg-3 col-sm-4 col-xs-12 text-right-not-xs">
                            <?php echo $element->label(['class' => 'text-bold']) ?>
                        </div>
                        <div class="col-lg-4 col-sm-5 col-xs-12">
                            <?php echo $element ?>
                        </div>
                        <div class="col-lg-5 col-sm-3 col-xs-12 error">
                            <?php if($hasErrors) : ?>
                            <?php echo $form->getMessagesFor($element->getName())[0]->getMessage() ?>
                            <?php endif ?>
                        </div>
                    </div>
                    <?php endforeach ?>

                    <div class="row">
                        <div class="col-lg-4 col-lg-offset-3 col-xs-12">
                            <button type="submit" class="btn btn-success fa fa-save" title="Save" aria-label="Save"></button>
                        </div>
                    </div>

                    <input type="hidden" name="<?php echo $this->security->getTokenKey() ?>" value="<?php echo $this->security->getToken() ?>" />
                </form>
            </div>

            <?php if($edit) : ?>
            <div id="records" class="tab-pane fade panel panel-square">
                <div class="table-responsive no-gutter col-lg-12 col-xs-12">
                    <table class="table table-striped table-hover success">
                        <thead>
                            <tr>
                                <th class="visible-xs">Actions</th>
                                <th>Id</th>
                                <th>Position</th>
                                <th>Label</th>
                                <th>Label OID</th>
                                <th>Value OID</th>
                                <th class="text-center">Dashboard</th>
                                <th class="text-right hidden-xs">Actions</th>
                            </tr>
                            <tr>
                                <td class="visible-xs">
                                    <a class="btn btn-primary" href="<?php echo $this->config->application->baseUri ?>settings/snmprecord/" title="Add record">
                                        <i class="fa fa-plus"></i>
                                    </a>
                                </td>
                                <td colspan="7" class="text-right hidden-xs">
                                    <a class="btn btn-primary" href="<?php echo $this->config->application->baseUri ?>settings/snmprecord/" title="Add record">
                                        <i class="fa fa-plus"></i>
                                    </a>
                                </td>
                            </tr>
                        </thead>
                        <tbody>
                            <?php foreach($host->getRecords(['order' => '-position DESC, label ASC']) as $record) : ?>

                            <tr>
                                <td class="visible-xs">
                                    <div class="btn-group">
                                        <a href="<?php echo $this->config->application->baseUri . 'settings/snmprecord/' . $record->id  ?>" class="btn btn-warning fa fa-edit"></a>
                                        <a href="<?php echo $this->config->application->baseUri . 'settings/delete/SnmpRecords/' . $record->id  ?>" class="btn btn-danger fa fa-trash-alt"></a>
                                    </div>
                                </td>
                                <td>
                                    <?php echo $record->id ?>
                                </td>
                                <td>
                                    <?php echo $record->position ?>
                                </td>
                                <td>
                                    <?php echo $record->label ?>
                                </td>
                                <td>
                                    <?php echo $record->label_oid ?>
                                </td>
                                <td>
                                    <?php echo $record->value_oid ?>
                                </td>
                                <td class="text-center">
                                    <i class="fa fa-star<?php echo !$record->show_dashboard ? '-o' : ' text-success'?>"></i>
                                </td>
                                <td class="hidden-xs">
                                    <div class="btn-group pull-right">
                                        <a href="<?php echo $this->config->application->baseUri . 'settings/snmprecord/' . $record->id  ?>" class="btn btn-warning fa fa-edit"></a>
                                        <a href="<?php echo $this->config->application->baseUri . 'settings/delete/SnmpRecords/' . $record->id  ?>" class="btn btn-danger fa fa-trash-alt"></a>
                                    </div>
                                </td>
                            </tr>
                            <?php endforeach ?>
                        </tbody>
                        <tfoot>
                            <tr class="visible-xs">
                                <td colspan="7">
                                    <a class="btn btn-primary" href="<?php echo $this->config->application->baseUri ?>settings/snmprecord/" title="Add record">
                                        <i class="fa fa-plus"></i>
                                    </a>
                                </td>
                            </tr>
                            <tr class="hidden-xs">
                                <td colspan="7" class="text-right">
                                    <a class="btn btn-primary" href="<?php echo $this->config->application->baseUri ?>settings/snmprecord/" title="Add record">
                                        <i class="fa fa-plus"></i>
                                    </a>
                                </td>
                            </tr>
                        </tfoot>
                    </table>
                </div>
            </div>
            <?php endif ?>
        </div>
    </div>
</div>
