<?php /** @var Phalcon\Mvc\Controller $this */ ?>

<div class="panel panel-success" id="settings">
    <div class="panel-heading">
        <div class="btn-group pull-left back-btn">
            <a href="<?php echo $this->settings->application->base_uri ?>settings/snmphost/<?php echo $record->snmp_host_id ?>#snmprecords" class="btn btn-default fa fa-chevron-left" title="Go back"></a>
        </div>
        <h4 class="pull-left">
            <?php echo isset($record->id) ? 'Edit' : 'New' ?> SNMP record
        </h4>
    </div>
    <div class="panel-body">
        <?php echo $form->renderForm('snmprecord') ?>
    </div>
</div>
