<?php /** @var Phalcon\Mvc\Controller $this */ ?>

<div class="panel panel-success" id="settings">
    <div class="panel-heading">
        <div class="btn-group pull-left back-btn">
            <a href="<?php echo $this->config->application->baseUri ?>settings/index#users" class="btn btn-default fa fa-chevron-left" title="Go back"></a>
        </div>
        <h4 class="pull-left">
            <?php echo !empty($user->username) ? 'Edit' : 'New' ?> user
        </h4>
    </div>
    <div class="panel-body">
        <form action="<?php echo $form->getAction() ?>" method="post" autocomplete="off">
            <?php foreach($form AS $element) : ?>
            <?php echo $form->renderDecorated($element) ?>
            <?php endforeach ?>

            <div class="row">
                <div class="col-lg-4 col-lg-offset-3 col-xs-12">
                    <button type="submit" class="btn btn-success fa fa-save" title="Save" aria-label="Save"></button>
                </div>
            </div>

            <input type="hidden" name="<?php echo $this->security->getTokenKey() ?>" value="<?php echo $this->security->getToken() ?>" />
        </form>
    </div>
</div>
