<?php /** @var Phalcon\Mvc\View $this */ ?>

<div class="panel panel-success database-stats" data-update-interval="<?php echo $this->settings->databasestats->update_interval ?>">
    <?php $this->partial('is-loading') ?>

    <div class="panel-heading">
        <div class="btn-group pull-right">
            <?php $this->partial('index/default_widget_buttons', ['hasRefresh' => true, 'widgetId' => $widget->id]) ?>
        </div>
        <h4 class="truncate-text" title="Database">Database</h4>
    </div>
    <ul class="list-group hidden-xs">
        <li class="list-group-item col-xs-12">
            <div class="col-xs-4 col-sm-5 col-lg-4">
                Uptime
            </div>
            <div class="col-xs-8 col-sm-7 col-lg-8 uptime time delayed">&hellip;</div>
        </li>
        <li class="list-group-item col-xs-12">
            <div class="col-xs-4 col-sm-5 col-lg-4">
                Threads
            </div>
            <div class="col-xs-8 col-sm-7 col-lg-8 threads">&hellip;</div>
        </li>
        <li class="list-group-item col-xs-12">
            <div class="col-xs-4 col-sm-5 col-lg-4">
                Questions
            </div>
            <div class="col-xs-8 col-sm-7 col-lg-8 questions">&hellip;</div>
        </li>
        <li class="list-group-item col-xs-12">
            <div class="col-xs-4 col-sm-5 col-lg-4">
                Slow queries
            </div>
            <div class="col-xs-8 col-sm-7 col-lg-8 slow-queries">&hellip;</div>
        </li>
        <li class="list-group-item col-xs-12">
            <div class="col-xs-4 col-sm-5 col-lg-4">
                Opens
            </div>
            <div class="col-xs-8 col-sm-7 col-lg-8 opens">&hellip;</div>
        </li>
        <li class="list-group-item col-xs-12">
            <div class="col-xs-4 col-sm-5 col-lg-4">
                Flush tables
            </div>
            <div class="col-xs-8 col-sm-7 col-lg-8 flush-tables">&hellip;</div>
        </li>
        <li class="list-group-item col-xs-12">
            <div class="col-xs-4 col-sm-5 col-lg-4">
                Open tables
            </div>
            <div class="col-xs-8 col-sm-7 col-lg-8 open-tables">&hellip;</div>
        </li>
        <li class="list-group-item col-xs-12">
            <div class="col-xs-4 col-sm-5 col-lg-4">
                Queries/s
            </div>
            <div class="col-xs-8 col-sm-7 col-lg-8 queries-per-second">&hellip;</div>
        </li>
    </ul>
</div>
