<div class="panel panel-success pull-left">
    <ul class="list-group panel-success">
        <li class="list-group-item list-group-item-success">
            <h4><?php echo utf8_encode($album->strArtists) ?></h4>
        </li>
        <li class="list-group-item col-xs-12 col-lg-12">
            <div class="col-xs-4 col-lg-2">Genre</div>
            <div class="col-xs-8 col-lg-10"><?php echo $album->strGenres ?></div>
        </li>
        <li class="list-group-item col-xs-12 col-lg-12">
            <div class="col-xs-4 col-lg-2">Year</div>
            <div class="col-xs-8 col-lg-10"><?php echo $album->iYear ?></div>
        </li>
        <?php if(!empty($album->strLabel)) : ?>
        <li class="list-group-item col-xs-12 col-lg-12">
            <div class="col-xs-4 col-lg-2">Label</div>
            <div class="col-xs-8 col-lg-10"><?php echo utf8_encode($album->strLabel) ?></div>
        </li>
        <?php endif ?>
    </ul>
</div>
