<div class="panel panel-success pull-left transparent">
    <ul class="list-group panel-success">
        <li class="list-group-item list-group-item-success">
            <h4>
                <?php echo $episode->strTitle ?>
            </h4>
        </li>

        <li class="list-group-item col-xs-12">
            <div class="col-xs-12 col-sm-3 text-bold">Plot</div>
            <div class="col-xs-12 col-sm-9">
                <?php echo $episode->c01 ?>
            </div>
        </li>

        <li class="list-group-item col-xs-12">
            <div class="col-xs-3 text-bold">Season</div>
            <div class="col-xs-9">
                <?php echo $episode->c12 ?>
            </div>
        </li>
        <li class="list-group-item col-xs-12">
            <div class="col-xs-3 text-bold">Episode</div>
            <div class="col-xs-9">
                <?php echo $episode->c13 ?>
            </div>
        </li>

        <?php if(!empty($episode->rating)) : ?>
        <li class="list-group-item col-xs-12">
            <div class="col-xs-3 text-bold">Rating</div>
            <div class="col-xs-9 rating">
                <?php for($i = 1; $i <= $episode->rating; $i++) : ?>
                <span class="fa fa-star text-success"></span>
                <?php endfor ?>

                <?php if($i -1 < $episode->rating) : ?>
                <span class="fa fa-star-half text-success"></span>
                <?php endif ?>

                <span class="label label-success pull-right">
                    <?php echo $episode->rating ?>
                </span>
            </div>
        </li>
        <?php endif ?>

        <?php if(!empty($lastPlayed = $episode->getFiles()[0]->lastPlayed)) : ?>
        <li class="list-group-item col-xs-12">
            <div class="col-xs-3 text-bold">Last played</div>
            <div class="col-xs-9">
                <?php echo $lastPlayed ?>
            </div>
        </li>
        <?php endif ?>

        <li class="list-group-item col-xs-12">
            <div class="col-xs-3 text-bold">Genre</div>
            <div class="col-xs-9">
                <?php echo $episode->genre ?>
            </div>
        </li>
        <li class="list-group-item col-xs-12">
            <div class="col-xs-3 text-bold">Date</div>
            <div class="col-xs-9">
                <?php echo $episode->c05 ?>
            </div>
        </li>
        <li class="list-group-item col-xs-12">
            <div class="col-xs-3 text-bold">Studio</div>
            <div class="col-xs-9">
                <?php echo $episode->studio ?>
            </div>
        </li>
        <li class="list-group-item col-xs-12">
            <div class="col-xs-3 text-bold">MPAA</div>
            <div class="col-xs-9">
                <?php echo $episode->mpaa ?>
            </div>
        </li>
    </ul>
</div>

<div class="panel-underlay"></div>