<div class="panel panel-success pull-left">
    <ul class="list-group panel-success">
        <li class="list-group-item list-group-item-success">
            <h4><?php echo utf8_encode($episode->getShow()->c00) ?></h4>
        </li>
        <li class="list-group-item col-xs-12">
            <div class="col-xs-4 col-lg-2">Episode</div>
            <div class="col-xs-8 col-lg-10"><?php echo $episode->c13 ?></div>
        </li>
        <li class="list-group-item col-xs-12">
            <div class="col-xs-4 col-lg-2">Season</div>
            <div class="col-xs-8 col-lg-10"><?php echo $episode->getSeason()->season ?></div>
        </li>
        <li class="list-group-item col-xs-12">
            <div class="col-xs-4 col-lg-2">Date</div>
            <div class="col-xs-8 col-lg-10"><?php echo $episode->c05 ?></div>
        </li>
        <?php if(!empty($episode->rating)) : ?>
        <li class="list-group-item col-xs-12">
            <div class="col-xs-4 col-lg-2">Rating</div>
            <div class="col-xs-8 col-lg-10">
                <?php for($i = 1; $i <= $episode->rating; $i++) : ?>
                <span class="glyphicon glyphicon-star text-success"></span>
                <?php endfor ?>

                <?php if($i -1 < $episode->rating) : ?>
                <span class="glyphicon glyphicon-half glyphicon-star text-success"></span>
                <?php endif ?>
            </div>
        </li>
        <?php endif ?>
        <li class="list-group-item col-xs-12">
            <div class="col-xs-4 col-lg-2">Plot</div>
            <div class="col-xs-8 col-lg-10"><?php echo utf8_encode($episode->c01) ?></div>
        </li>
    </ul>
</div>
