<div class="panel panel-success pull-left transparent kodi-movies">
    <ul class="list-group panel-success">
        <li class="list-group-item list-group-item-success">
            <h4 title="<?php echo $movie->c00 ?>"><?php echo $movie->c00 ?></h4>
        </li>
        <li class="list-group-item col-xs-12">
            <div class="col-xs-12 text-center">
                <?php if (!empty($movie->trailer)) : ?>
                <div class="embed-responsive embed-responsive-16by9">
                    <iframe class="embed-responsive-item" src="//www.youtube.com/embed/<?php echo $movie->trailer ?>" frameborder="0" allowfullscreen title="Trailer"></iframe>
                </div>
                <?php else : ?>
                Sorry, no trailer found
                <?php endif ?>
            </div>
        </li>

        <li class="list-group-item col-xs-12">
            <div class="col-xs-12 col-sm-3 text-bold">Plot</div>
            <div class="col-xs-12 col-sm-9"><?php echo $movie->c01 ?></div>
        </li>

        <?php if (!empty($movie->rating)) : ?>
        <li class="list-group-item col-xs-12">
            <div class="col-xs-3 text-bold">Rating</div>
            <div class="col-xs-9 rating">
                <?php for($i = 1; $i <= $movie->rating; $i++) : ?>
                <span class="fa fa-star text-success"></span>
                <?php endfor ?>

                <?php if ($i -1 < $movie->rating) : ?>
                <span class="fa fa-star-half text-success"></span>
                <?php endif ?>

                <span class="label label-success pull-right">
                    <?php echo $movie->rating ?>
                </span>
            </div>
        </li>
        <?php endif ?>

        <?php if (!empty($lastPlayed = $movie->getFiles()[0]->lastPlayed)) : ?>
        <li class="list-group-item col-xs-12">
            <div class="col-xs-3 text-bold">Last played</div>
            <div class="col-xs-9">
                <?php echo $lastPlayed ?>
            </div>
        </li>
        <?php endif ?>

        <?php if (!empty($movie->c14)) : ?>
        <li class="list-group-item col-xs-12">
            <div class="col-xs-3 text-bold">Genre</div>
            <div class="col-xs-9"><?php echo $movie->c14 ?></div>
        </li>
        <?php endif ?>

        <?php if (!empty($movie->c07)) : ?>
        <li class="list-group-item col-xs-12">
            <div class="col-xs-3 text-bold">Year</div>
            <div class="col-xs-9"><?php echo $movie->c07 ?></div>
        </li>
        <?php endif ?>

        <?php if (!empty($movie->c15)) : ?>
        <li class="list-group-item col-xs-12">
            <div class="col-xs-3 text-bold">Director</div>
            <div class="col-xs-9"><?php echo $movie->c15 ?></div>
        </li>
        <?php endif ?>

        <?php if (!empty($movie->c06)) : ?>
        <li class="list-group-item col-xs-12">
            <div class="col-xs-3 text-bold">Writers</div>
            <div class="col-xs-9"><?php echo $movie->c06 ?></div>
        </li>
        <?php endif ?>

        <?php if (!empty($movie->c18)) : ?>
        <li class="list-group-item col-xs-12">
            <div class="col-xs-3 text-bold">Studio</div>
            <div class="col-xs-9"><?php echo $movie->c18 ?></div>
        </li>
        <?php endif ?>

        <?php if (!empty($movie->c21)) : ?>
        <li class="list-group-item col-xs-12">
            <div class="col-xs-3 text-bold">Country</div>
            <div class="col-xs-9 "><?php echo $movie->c21 ?></div>
        </li>
        <?php endif ?>
    </ul>
</div>

<div class="panel-underlay"></div>