<div class="panel panel-success pull-left transparent">
    <ul class="list-group panel-success">
        <li class="list-group-item list-group-item-success">
            <h4><?php echo utf8_encode($movie->c00)?></h4>
        </li>
        <li class="list-group-item col-xs-12 col-lg-12">
            <div class="col-xs-12 text-center">
                <?php if(!empty($movie->trailer)) : ?>
                <div class="embed-responsive embed-responsive-16by9">
                    <iframe class="embed-responsive-item" src="//www.youtube.com/embed/<?php echo $movie->trailer ?>" frameborder="0" allowfullscreen></iframe>
                </div>
                <?php else : ?>
                Sorry, no trailer found
                <?php endif ?>
            </div>
        </li>

        <?php if(!empty($movie->rating)) : ?>
        <li class="list-group-item col-xs-12 col-lg-12">
            <div class="col-xs-12 col-sm-2 text-bold">Rating</div>
            <div class="col-xs-12 col-sm-10">
                <?php for($i = 1; $i <= $movie->rating; $i++) : ?>
                <span class="fa fa-star text-success"></span>
                <?php endfor ?>

                <?php if($i -1 < $movie->rating) : ?>
                <span class="fa fa-star-half text-success"></span>
                <?php endif ?>

                <span class="badge badge-success pull-right"><?php echo $movie->rating ?></span>
            </div>
        </li>
        <?php endif ?>

        <li class="list-group-item col-xs-12 col-lg-12">
            <div class="col-xs-12 col-sm-2 text-bold">Plot</div>
            <div class="col-xs-12 col-sm-10"><?php echo utf8_encode($movie->c01) ?></div>
        </li>

        <?php if(!empty($movie->c14)) : ?>
        <li class="list-group-item col-xs-12 col-lg-12">
            <div class="col-xs-12 col-sm-2 text-bold">Genre</div>
            <div class="col-xs-12 col-sm-10"><?php echo utf8_encode($movie->c14) ?></div>
        </li>
        <?php endif ?>

        <?php if(!empty($movie->c07)) : ?>
        <li class="list-group-item col-xs-12 col-lg-12">
            <div class="col-xs-12 col-sm-2 text-bold">Year</div>
            <div class="col-xs-12 col-sm-10"><?php echo $movie->c07 ?></div>
        </li>
        <?php endif ?>

        <?php if(!empty($movie->c15)) : ?>
        <li class="list-group-item col-xs-12 col-lg-12">
            <div class="col-xs-12 col-sm-2 text-bold">Director</div>
            <div class="col-xs-12 col-sm-10"><?php echo utf8_encode($movie->c15) ?></div>
        </li>
        <?php endif ?>

        <?php if(!empty($movie->c06)) : ?>
        <li class="list-group-item col-xs-12 col-lg-12">
            <div class="col-xs-12 col-sm-2 text-bold">Writers</div>
            <div class="col-xs-12 col-sm-10"><?php echo utf8_encode($movie->c06) ?></div>
        </li>
        <?php endif ?>

        <?php if(!empty($movie->c18)) : ?>
        <li class="list-group-item col-xs-12 col-lg-12">
            <div class="col-xs-12 col-sm-2 text-bold">Studio</div>
            <div class="col-xs-12 col-sm-10"><?php echo utf8_encode($movie->c18) ?></div>
        </li>
        <?php endif ?>

        <?php if(!empty($movie->c21)) : ?>
        <li class="list-group-item col-xs-12 col-lg-12">
            <div class="col-xs-12 col-sm-2 text-bold">Country</div>
            <div class="col-xs-12 col-sm-10"><?php echo utf8_encode($movie->c21) ?></div>
        </li>
        <?php endif ?>
    </ul>
</div>

<div class="panel-underlay"></div>