<?php /** @var Phalcon\Mvc\View $this */ ?>

<div class="panel panel-success kodi movies gallery" data-rotate-interval="<?php echo $this->settings->kodi->rotate_movies_interval ?>">
    <div class="panel-heading">
        <div class="backdrop"></div>
        <div class="btn-group pull-right">
            <button class="btn btn-default fa fa-chevron-left" title="Previous movie" aria-label="Previous movie"></button>
            <button class="btn btn-default fa fa-chevron-right rounded-not-mobile" title="Next movie" aria-label="Next movie"></button>
            <?php $this->partial('index/default_widget_buttons', ['hasRefresh' => false, 'widgetId' => $widget->id]) ?>
        </div>
        <h4 class="truncate-text" title="Latest movies">Latest movies</h4>
    </div>
    <div class="panel-body hidden-xs">
        <?php $i = 0; foreach($movies as $movie) :?>
        <a class="movie item <?php echo $i++ > 0 ? 'hidden' : 'show' ?>_not_important"
            data-fancybox="movies"
            data-type="iframe"
            href="<?php echo $this->url->get('kodi/movie/' . $movie->idMovie) ?>"
            title="<?php echo $movie->c00 ?>">
            <img src="<?php echo $movie->getImageUrl('thumb', 'c08', 'idMovie') ?>" loading="lazy" width="348" height="377" alt="<?php echo $movie->c00 ?>" />
            <div class="overlay"></div>
            <div class="title" title="<?php echo $movie->c00 ?>">
                <?php echo $movie->c00 ?>
            </div>
            <div class="subtitle" title="<?php echo $movie->c03 ?>">
                <?php echo $movie->c03 ?>
            </div>

            <?php if (!empty($movie->getFiles()[0]->lastPlayed)) : ?>
            <div class="fa fa-eye" title="Watched"></div>
            <?php endif ?>
        </a>
        <?php endforeach ?>
    </div>
</div>