<item>
    <title>
Uptime: 
<?php echo (gmdate('d', $phpsysinfoData->Vitals->{'@attributes'}->Uptime) - 1) . 'd ' . gmdate('H:i:s', $phpsysinfoData->Vitals->{'@attributes'}->Uptime) ?>
	</title>
    <pubDate><?php echo date('D, d M Y H:i:s') ?> +0200</pubDate>
    <category>Stats</category>
</item>

<item>
    <title>
Updates
Packages: <?php echo isset($phpsysinfoData->Plugins->Plugin_UpdateNotifier) ? trim($phpsysinfoData->Plugins->Plugin_UpdateNotifier->UpdateNotifier->packages) : '-' ?> 
Security: <?php echo isset($phpsysinfoData->Plugins->Plugin_UpdateNotifier) ? trim($phpsysinfoData->Plugins->Plugin_UpdateNotifier->UpdateNotifier->security) : '-' ?>
    </title>
    <pubDate><?php echo date('D, d M Y H:i:s') ?> +0200</pubDate>
    <category>Stats</category>
</item>

<item>
    <title>
RAM: <?php echo $phpsysinfoData->Memory->{'@attributes'}->Percent ?>%
Swap: <?php echo $phpsysinfoData->Memory->Swap->{'@attributes'}->Percent ?>%
<?php $i = 0; foreach($phpsysinfoData->Hardware->CPU->CpuCore as $core) : ?>
Core <?php echo $i++ . ': ' . $core->{'@attributes'}->CpuSpeed ?> GHz
<?php endforeach ?>
    </title>
    <pubDate><?php echo date('D, d M Y H:i:s') ?> +0200</pubDate>
    <category>Stats</category>
</item>

<item>
    <title>
<?php foreach($phpsysinfoData->FileSystem->Mount as $mount) : ?>
<?php echo $mount->Name . ': ' . $mount->Percent . '%' ?> 
<?php endforeach ?>
    </title>
    <pubDate><?php echo date('D, d M Y H:i:s') ?> +0200</pubDate>
    <category>Stats</category>
</item>