<?php /** @var Phalcon\Mvc\Controller $this */ ?>
<?php /** @var $baseURL string */ ?>
<?php echo '<?' ?>xml version="1.0" encoding="UTF-8"<?= "?>\n" ?>
<rss version="2.0" xmlns:atom="http://www.w3.org/2005/Atom">
    <channel>
        <copyright>Copyright 2015 - <?= date('Y') ?> | Jos Nienhuis</copyright>
        <language>en</language>
        <atom:link href="<?php echo $this->url->get('rss') ?>" rel="self" type="application/rss+xml" />
        <title><?php echo $this->settings->application->title ?></title>
        <description></description>
        <pubDate><?php echo date('D, d M Y H:i:s') ?> +0200</pubDate>

        <item>
 <title>Uptime:
<?php echo (gmdate('d', $sysinfoData['uptime']['uptime']) - 1) . 'd ' . gmdate('H:i:s', $sysinfoData['uptime']['uptime']) ?>

Refreshed on:
<?php echo date('d-m-Y H:i') ?>
</title>
            <pubDate><?php echo date('D, d M Y H:i:s') ?> +0200</pubDate>
            <category>Stats</category>
        </item>

        <item>
<title>
<?php foreach($disksData as $disk) : ?>
<?php echo $disk->mount . ': ' . $disk->usage ?>

<?php endforeach ?>
</title>
            <pubDate><?php echo date('D, d M Y H:i:s') ?> +0200</pubDate>
            <category>Stats</category>
        </item>
    </channel>
</rss>