<?php /** @var Phalcon\Mvc\View $this */ ?>

<div id="settings" class="tab-pane fade">
    <form class="panel-body" method="post">
        <div class="form-group row">
            <div class="col-lg-offset-2 col-sm-offset-1 col-lg-4 col-sm-4 col-xs-12">
                <label for="check-devicestate-interval" class="text-bold">Fan speed</label>
            </div>
            <div class="col-lg-4 col-sm-6 col-xs-12">
                <select name="fanspeed" class="form-control">
                    <?php foreach (Chell\Models\Roborock::fanspeedLevels as $key => $level) : ?>
                        <option value="<?php echo $key ?>" <?php echo $key == $fanspeed ? 'selected' : null ?>>
                            <?php echo $level ?>
                        </option>
                    <?php endforeach ?>
                </select>
            </div>
        </div>
        <div class="form-group row">
            <div class="col-lg-offset-2 col-sm-offset-1 col-lg-4 col-sm-4 col-xs-12">
                <label for="check-devicestate-interval" class="text-bold">Volume</label>
            </div>
            <div class="col-lg-4 col-sm-6 col-xs-12">
                <input type="number" name="volume" class="form-control" value="<?php echo $volume ?>">
            </div>
        </div>
        <div class="form-group row">
            <div class="col-lg-offset-2 col-sm-offset-1 col-lg-4 col-sm-4 col-xs-12">
                <label for="check-devicestate-interval" class="text-bold">Waterflow</label>
            </div>
            <div class="col-lg-4 col-sm-6 col-xs-12">
                <select name="waterflow" class="form-control">
                    <?php foreach (Chell\Models\Roborock::waterFlowLevels as $level) : ?>
                        <option value="<?php echo $level ?>" <?php echo $level == $waterflow ? 'selected' : null ?>>
                            <?php echo $level ?>
                        </option>
                    <?php endforeach ?>
                </select>
            </div>
        </div>
        <div class="row">
            <div class="col-lg-offset-2 col-sm-offset-1 col-lg-4 col-sm-4 col-xs-12">
                <button type="submit" class="btn btn-success fa fa-floppy-disk"></button>
            </div>
        </div>
    </form>
</div>