<div class="panel panel-success with-nav-tabs speedtest" style="max-height:800px">
    <div class="panel-heading ">
        <h4 class="pull-left hidden-xs">Speedtest</h4>
        <ul class="nav nav-tabs pull-right">
            <li class="<?php echo $activetab == 'chart' ? 'active' : null ?>">
                <a data-toggle="tab" href="#chart">
                    Chart
                </a>
            </li>
            <li class="<?php echo $activetab == 'records' ? 'active' : null ?>">
                <a data-toggle="tab" href="#records">
                    Records
                </a>
            </li>
        </ul>
    </div>
    <div class="tab-content">
        <?php $this->partial('speedtest/partials/chart') ?>
        <?php $this->partial('speedtest/partials/records') ?>
    </div>

    <?php $this->partial('paginator') ?>
</div>
