
<div class="panel panel-success with-nav-tabs speedtest" style="min-height:700px">
    <div class="panel-heading ">
        <h4 class="pull-left hidden-xs">Speedtest</h4>
        <ul class="nav nav-tabs pull-right">
            <li >
                <a data-toggle="tab" href="#records">
                    Records
                    <button class="btn btn-xs btn-success">
                        <span class="fa fa-bars"></span>
                    </button>
                </a>
            </li>
            <li class="active">
                <a data-toggle="tab" href="#chart">
                    Chart
                    <button class="btn btn-xs btn-success">
                        <span class="fa fa-chart-bar"></span>
                    </button>
                </a>
            </li>
        </ul>
    </div>
    <div class="tab-content">
        <?php $this->partial('speedtest/partials/records') ?>
        <?php $this->partial('speedtest/partials/chart') ?>
    </div>
</div>
