<?php /** @var Phalcon\Mvc\Controller $this */ ?>

<div id="devices" class="tab-pane fade panel panel-square">
    <div class="table-responsive no-gutter col-lg-12 col-xs-12">
        <table class="table table-striped table-hover success">
            <thead>
                <tr>
                    <th class="visible-xs">Actions</th>
                    <th>Name</th>
                    <th>IP</th>
                    <th>MAC</th>
                    <th>Shutdown</th>
                    <th class="text-center">Dashboard</th>
                    <th class="text-right hidden-xs">Actions</th>
                </tr>
                <tr>
                    <td class="visible-xs">
                        <a class="btn btn-primary" href="<?php echo $this->config->application->baseUri ?>settings/device/" title="Add device">
                            <i class="fa fa-plus"></i>
                        </a>
                    </td>
                    <td colspan="7" class="text-right hidden-xs">
                        <a class="btn btn-primary" href="<?php echo $this->config->application->baseUri ?>settings/device/" title="Add device">
                            <i class="fa fa-plus"></i>
                        </a>
                    </td>
                </tr>
            </thead>
            <tbody>
                <?php $i= 0; foreach($devices AS $device) : ?>
                <tr>
                    <td class="visible-xs">
                        <div class="btn-group">
                            <a href="<?php echo $this->config->application->baseUri . 'settings/device/' . $device->id  ?>" class="btn btn-warning fa fa-edit"></a>
                            <a href="<?php echo $this->config->application->baseUri . 'settings/delete/Devices/' . $device->id  ?>" class="btn btn-danger fa fa-trash-alt"></a>
                        </div>
                    </td>
                    <td>
                        <?php echo $device->name ?>
                    </td>
                    <td>
                        <?php echo $device->ip ?>
                    </td>
                    <td>
                        <?php echo $device->mac ?>
                    </td>
                    <td>
                        <?php echo $device->shutdown_method ?>
                    </td>
                    <td class="text-center">
                        <i class="fa fa-star<?php echo !$device->show_on_dashboard ? '-o' : ' text-success'?>"></i>
                    </td>
                    <td class="hidden-xs">
                        <div class="btn-group pull-right">
                            <a href="<?php echo $this->config->application->baseUri . 'settings/device/' . $device->id  ?>" class="btn btn-warning fa fa-edit"></a>
                            <a href="<?php echo $this->config->application->baseUri . 'settings/delete/Devices/' . $device->id  ?>" class="btn btn-danger fa fa-trash-alt"></a>
                        </div>
                    </td>
                </tr>
                <?php endforeach ?>
            </tbody>
            <tfoot>
                <tr class="visible-xs">
                    <td colspan="7">
                        <a class="btn btn-primary" href="<?php echo $this->config->application->baseUri ?>settings/device/" title="Add device">
                            <i class="fa fa-plus"></i>
                        </a>
                    </td>
                </tr>
                <tr class="hidden-xs">
                    <td colspan="7" class="text-right">
                        <a class="btn btn-primary" href="<?php echo $this->config->application->baseUri ?>settings/device/" title="Add device">
                            <i class="fa fa-plus"></i>
                        </a>
                    </td>
                </tr>
            </tfoot>
        </table>
    </div>
</div>
