<form id="devices" class="tab-pane fade panel panel-square" action="<?php echo $formDevices->getAction() ?>" method="post">
    <div class="table-responsive no-gutter col-lg-12 col-xs-12">
        <table class="table table-striped table-hover success">
            <thead>
                <tr>
                    <th>Name</th>
                    <th>IP</th>
                    <th>MAC</th>
                    <th>Webtemp</th>
                    <th>Shutdown</th>
                    <th> </th>
                </tr>
            </thead>
            <tbody>
                <tr>
                <?php $i= 0; foreach($formDevices AS $element) : ?>
                <?php if($i % 6 == 0) : ?>
                </tr>
                <tr>
                <?php endif ?>
                    <?php if(get_class($element) != 'Phalcon\Forms\Element\Hidden') : ?>
                     <td><?php echo $element ?></td>
                    <?php else : ?>
                    <td>
                        <a href="devices_delete?id=<?php echo $element->getValue() ?>" class="btn btn-danger glyphicon glyphicon-remove pull-right"></a>
                    </td>
                    <?php endif ?>
                <?php $i++;
                      endforeach ?> 
                </tr>
            </tbody>
        </table>
    </div>

    <div class="col-lg-12 col-xs-12 no-gutter actions">
        <button type="submit" class="btn btn-success pull-left" title="Save">
            <i class="glyphicon glyphicon-floppy-disk"></i>
        </button>
        <a class="btn btn-primary pull-left add" href="#new_device" title="Add device">
            <i class="glyphicon glyphicon-plus"></i>
        </a>
    </div>
</form>

<div class="hidden_not_important fancybox_form" id="new_device">
    <h2>New device</h2>
    <form action="<?php echo $formNewDevice->getAction() ?>" method="post">
        <?php foreach($formNewDevice AS $element) : ?>
        <div class="form-group col-lg-12 no-gutter">
            <div class="col-lg-6 no-gutter-left"><?php echo $element->label() ?></div>
            <div class="col-lg-6 no-gutter-right"><?php echo $element ?></div>
        </div>
        <?php endforeach ?>

        <button type="submit" class="btn btn-success" title="Save">
            <i class="glyphicon glyphicon-floppy-disk"></i>
        </button>
    </form>
</div>