<div id="devices" class="tab-pane fade panel panel-square<?php echo $activeForm == 'Devices' ? ' in active' : null ?>">
    <div class="table-responsive no-gutter col-lg-12 col-xs-12">
        <table class="table table-striped table-hover success">
            <thead>
                <tr>
                    <th>Name</th>
                    <th>IP</th>
                    <th>MAC</th>
                    <th>Webtemp</th>
                    <th>Shutdown</th>
                    <th class="text-center">Dashboard</th>
                    <th class="text-right">Actions</th>
                </tr>
                <tr>
                    <td colspan="7" class="text-right">
                        <a class="btn btn-primary" href="<?php echo $this->config->application->baseUri ?>settings/device/" title="Add device">
                            <i class="glyphicon glyphicon-plus"></i>
                        </a>
                    </td>
                </tr>
            </thead>
            <tbody>
                <?php $i= 0; foreach($devices AS $device) : ?>
                <tr>
                    <td>
                        <?php echo $device->name ?>
                    </td>
                    <td>
                        <?php echo $device->ip ?>
                    </td>
                    <td>
                        <?php echo $device->mac ?>
                    </td>
                    <td>
                        <?php echo $device->webtemp ?>
                    </td>
                    <td>
                        <?php echo $device->shutdown_method ?>
                    </td>
                    <td class="text-center">
                        <span class="glyphicon glyphicon-star<?php echo !$device->show_on_dashboard ? "-empty" : null ?>"></span>
                    </td>
                    <td>
                        <div class="btn-group pull-right">
                            <a href="<?php echo $this->config->application->baseUri . 'settings/device/' . $device->id  ?>" class="btn btn-warning glyphicon glyphicon-edit"></a>
                            <a href="<?php echo $this->config->application->baseUri . 'settings/device_delete/' . $device->id  ?>" class="btn btn-danger glyphicon glyphicon-remove"></a>
                        </div>
                    </td>
                </tr>
                <?php endforeach ?>
            </tbody>
            <tfoot>
                <tr>
                    <td colspan="7" class="text-right">
                        <a class="btn btn-primary" href="<?php echo $this->config->application->baseUri ?>settings/device/" title="Add device">
                            <i class="glyphicon glyphicon-plus"></i>
                        </a>
                    </td>
                </tr>
            </tfoot>
        </table>
    </div>
</div>
