<div id="logs" class="tab-pane fade panel panel-square">
    <?php if(count($logs) <= 2) : ?>
    <h3 class="text-success">No error logs found!</h3>
    <?php else :?>
    <div class="table-responsive col-lg-12 col-xs-12 no-gutter">
        <table class="table table-striped table-hover success">
            <thead>
                <tr>
                    <th class="visible-xs">Actions</th>
                    <th>Filename</th>
                    <th>Time</th>
                    <th class="text-right hidden-xs">Actions</th>
                </tr>
                <tr>
                    <td class="visible-xs">
                        <a class="btn btn-danger" href="<?php echo $this->config->application->baseUri ?>settings/delete/Logs/all" title="Remove all">
                            <i class="fa fa-trash"></i>
                        </a>
                    </td>
                    <td colspan="7" class="text-right hidden-xs">
                        <a class="btn btn-danger" href="<?php echo $this->config->application->baseUri ?>settings/delete/Logs/all" title="Remove all">
                            <i class="fa fa-trash"></i>
                        </a>
                    </td>
                </tr>
            </thead>
            <tbody>
                <?php foreach($logs AS $log) :
                          if($log == '.' || $log == '..') continue; ?>
                <tr>
                    <td class="visible-xs">
                        <div class="btn-group">
                            <a href="<?php echo $this->config->application->baseUri . 'settings/log/' . $log ?>" class="btn btn-default fa fa-eye" target="_blank"></a>
                            <a href="#" class="btn btn-danger fa fa-remove"></a>
                        </div>
                    </td>
                    <td>
                        <?php echo $log ?>
                    </td>
                    <td>
                        <?php echo date('d-m-Y H:i:s', filemtime(APP_PATH . 'app/logs/' . $log)) ?>
                    </td>
                    <td class="hidden-xs">
                        <div class="btn-group pull-right">
                            <a href="<?php echo $this->config->application->baseUri . 'settings/log/' . $log ?>" class="btn btn-default fa fa-eye" target="_blank"></a>
                            <a href="<?php echo $this->config->application->baseUri . 'settings/delete/Logs/' . $log  ?>" class="btn btn-danger fa fa-remove"></a>
                        </div>
                    </td>
                </tr>
                <?php endforeach ?>
            </tbody>
            <tfoot>
                <tr class="visible-xs">trrash
                    <td colspan="8">
                        <a class="btn btn-danger" href="<?php echo $this->config->application->baseUri ?>settings/delete/Logs/all" title="Remove all">
                            <i class="fa fa-trash"></i>
                        </a>
                    </td>
                </tr>
                <tr class="hidden-xs">
                    <td colspan="8" class="text-right">
                        <a class="btn btn-danger" href="<?php echo $this->config->application->baseUri ?>settings/delete/Logs/all" title="Remove all">
                            <i class="fa fa-trash"></i>
                        </a>
                    </td>
                </tr>
            </tfoot>
        </table>
    </div>
    <?php endif ?>
</div>
