<?php /** @var Phalcon\Mvc\View $this */ ?>

<div id="logs" class="tab-pane fade panel panel-square<?php echo $activeTab == 'Logs' ? ' in active' : null ?>">
    <?php if (count($logs) == 0) : ?>
    <h3 class="text-success">No error logs found!</h3>
    <?php else :?>
    <div class="table-responsive col-lg-12 col-xs-12 no-gutter">
        <table class="table table-striped table-hover success">
            <thead>
                <tr>
                    <th class="visible-xs">Actions</th>
                    <th>Filename</th>
                    <th>Time</th>
                    <th>Filesize</th>
                    <th class="text-right hidden-xs">Actions</th>
                </tr>
                <tr>
                    <td class="visible-xs">
                        <a class="btn btn-danger fa fa-trash-alt" href="<?php echo $this->config->application->baseUri ?>settings/delete/Logs/all" title="Remove all"></a>
                    </td>
                    <td colspan="4" class="text-right hidden-xs">
                        <a class="btn btn-danger fa fa-trash-alt" href="<?php echo $this->config->application->baseUri ?>settings/delete/Logs/all" title="Remove all"></a>
                    </td>
                </tr>
            </thead>
            <tbody>
                <?php foreach($logs AS $log => $time) : ?>
                <tr>
                    <td class="visible-xs">
                        <div class="btn-group">
                            <a href="<?php echo $this->config->application->baseUri . 'settings/log/' . $log ?>" class="btn btn-default fa fa-eye" target="_blank"></a>
                            <a href="<?php echo $this->config->application->baseUri . 'settings/delete/Logs/' . $log  ?>" class="btn btn-danger fa fa-trash-alt"></a>
                        </div>
                    </td>
                    <td>
                        <?php echo $log ?>
                    </td>
                    <td>
                        <?php echo $time ?>
                    </td>
                    <td>
                        <?php echo number_format(filesize($filePath = APP_PATH . 'app/logs/' . $log) / 1024, 2) ?> KB
                    </td>
                    <td class="hidden-xs">
                        <div class="btn-group pull-right">
                            <a href="<?php echo $this->config->application->baseUri . 'settings/log/' . $log ?>" class="btn btn-default fa fa-eye" target="_blank"></a>
                            <a href="<?php echo $this->config->application->baseUri . 'settings/delete/Logs/' . $log  ?>" class="btn btn-danger fa fa-trash-alt"></a>
                        </div>
                    </td>
                </tr>
                <?php endforeach ?>
            </tbody>
            <tfoot>
                <tr class="visible-xs">
                    <td colspan="5">
                        <a class="btn btn-danger fa fa-trash-alt" href="<?php echo $this->config->application->baseUri ?>settings/delete/Logs/all" title="Remove all"></a>
                    </td>
                </tr>
                <tr class="hidden-xs">
                    <td colspan="5" class="text-right">
                        <a class="btn btn-danger fa fa-trash-alt" href="<?php echo $this->config->application->baseUri ?>settings/delete/Logs/all" title="Remove all"></a>
                    </td>
                </tr>
            </tfoot>
        </table>
    </div>
    <?php endif ?>

    <?php $this->partial('paginator') ?>
</div>
