<form id="menu" class="tab-pane fade panel panel-square" action="<?php echo $formMenu->getAction() ?>" method="post">
    <div class="col-lg-12 col-xs-12 no-gutter actions">
        <button type="submit" class="btn btn-success pull-left" title="Save">
            <i class="glyphicon glyphicon-floppy-disk"></i>
        </button>
        <a class="btn btn-primary pull-left add" href="#new_menuitem" title="Add menu item">
            <i class="glyphicon glyphicon-plus"></i>
        </a>
    </div>

    <div class="table-responsive col-lg-12 col-xs-12 no-gutter">
        <table class="table table-striped table-hover success">
            <thead>
                <tr>
                    <th>Name</th>
                    <th>URL</th>
                    <th>Icon</th>
                    <th>Device</th>
                    <th> </th>
                </tr>
            </thead>
            <tbody>
                <tr>
                <?php $i= 0; foreach($formMenu AS $element) : ?>
                <?php if($i != 0 && $i % 5 == 0) : ?>
                </tr>
                <tr>
                <?php endif ?> 
                    <?php if(get_class($element) != 'Phalcon\Forms\Element\Hidden') : ?>
                     <td><?php echo $element ?></td>
                    <?php else : ?>
                    <td>
                        <a href="menuitem_delete?id=<?php echo $element->getValue() ?>" class="btn btn-danger glyphicon glyphicon-remove pull-right"></a>
                    </td>
                    <?php endif ?>
                <?php $i++;
                      endforeach ?>
                </tr>
            </tbody>
        </table>
    </div>

    <div class="col-lg-12 col-xs-12 no-gutter actions">
        <button type="submit" class="btn btn-success pull-left" title="Save">
            <i class="glyphicon glyphicon-floppy-disk"></i>
        </button>
        <a class="btn btn-primary pull-left add" href="#new_menuitem" title="Add menu item">
            <i class="glyphicon glyphicon-plus"></i>
        </a>
    </div>
</form>

<div class="hidden_not_important fancybox_form" id="new_menuitem">
    <h2>New menu item</h2>
    <form  action="<?php echo $formNewMenuItem->getAction() ?>" method="post">
        <?php foreach($formNewMenuItem AS $element) : ?>
        
            <?php if(get_class($element) != 'Phalcon\Forms\Element\Hidden') : ?>
            <div class="form-group col-lg-12 no-gutter">
                <div class="col-lg-4 no-gutter-left"><?php echo $element->label() ?></div>
                <div class="col-lg-8 no-gutter-right"><?php echo $element ?></div>
            </div>
            <?php else : ?>
            <?php echo $element ?>
            <?php endif ?>
        <?php endforeach ?>

        <button type="submit" class="btn btn-success" title="Save">
            <i class="glyphicon glyphicon-floppy-disk"></i>
        </button>
    </form>
</div>