<form id="menu" class="tab-pane fade panel panel-square" action="<?php echo $formMenu->getAction() ?>" method="post">
    <div class="table-responsive">
        <table class="table table-striped table-hover success">
            <thead>
                <tr>
                    <th>Name</th>
                    <th>URL</th>
                    <th>Icon</th>
                    <th>Device</th>
                    <th class="actions">
                        <button type="submit" class="btn btn-success pull-right">
                            <i class="glyphicon glyphicon-floppy-disk"></i>
                        </button>
                        <a class="btn btn-primary pull-right add" href="#new_menuitem">
                            <i class="glyphicon glyphicon-plus"></i>
                        </a>
                    </th>
                </tr>
            </thead>
            <tbody>
                <tr>
                <?php $i= 0; foreach($formMenu AS $element) : ?>
                <?php if($i != 0 && $i % 5 == 0) : ?>
                </tr>
                <tr>
                <?php endif ?> 
                    <?php if(get_class($element) != 'Phalcon\Forms\Element\Hidden') : ?>
                     <td><?php echo $element ?></td>
                    <?php else : ?>
                    <td>
                        <a href="menuitem_delete?id=<?php echo $element->getValue() ?>" class="btn btn-danger glyphicon glyphicon-remove pull-right"></a>
                    </td>
                    <?php endif ?>
                <?php $i++;
                      endforeach ?>
                </tr>
            </tbody>
            <tfoot>
                <tr>
                    <td colspan="5" class="actions">
                        <button type="submit" class="btn btn-success pull-right">
                            <i class="glyphicon glyphicon-floppy-disk"></i>
                        </button>
                        <button class="btn btn-primary pull-right add">
                            <i class="glyphicon glyphicon-plus"></i>
                        </button>
                    </td>
                </tr>
            </tfoot>
        </table>
    </div>
</form>

<div class="hidden_not_important" id="new_menuitem">
    <h2>New menu item</h2>
    <form  action="<?php echo $formNewMenuItem->getAction() ?>" method="post">
        <?php foreach($formNewMenuItem AS $element) : ?>
        <div class="form-group">
            <div class="input-group">
                <?php if(get_class($element) != 'Phalcon\Forms\Element\Hidden') : ?>
                <span class="input-group-addon"><?php echo $element->label() ?></span>
                <?php endif ?>
                <?php echo $element ?>
            </div>
        </div>
        <?php endforeach ?>

        <button type="submit" class="btn btn-success pull-right">
            <i class="glyphicon glyphicon-floppy-disk"></i>
        </button>
    </form>
</div>