<?php /** @var Phalcon\Mvc\Controller $this */ ?>

<div id="snmphosts" class="tab-pane fade panel panel-square">
    <div class="table-responsive no-gutter col-lg-12 col-xs-12">
        <table class="table table-striped table-hover success">
            <thead>
                <tr>
                    <th class="visible-xs">Actions</th>
                    <th>Name</th>
                    <th>IP</th>
                    <th class="text-center">Version</th>
                    <th>Community</th>
                    <th class="text-right hidden-xs">Actions</th>
                </tr>
                <tr>
                    <td class="visible-xs">
                        <a class="btn btn-primary" href="<?php echo $this->settings->application->base_uri ?>settings/snmphost/" title="Add device">
                            <i class="fa fa-plus"></i>
                        </a>
                    </td>
                    <td colspan="7" class="text-right hidden-xs">
                        <a class="btn btn-primary" href="<?php echo $this->settings->application->base_uri ?>settings/snmphost/" title="Add device">
                            <i class="fa fa-plus"></i>
                        </a>
                    </td>
                </tr>
            </thead>
            <tbody>
                <?php $i= 0; foreach($snmpHosts AS $host) : ?>
                <tr>
                    <td class="visible-xs">
                        <div class="btn-group">
                            <a href="<?php echo $this->settings->application->base_uri . 'settings/snmphost/' . $host->id  ?>" class="btn btn-warning fa fa-edit"></a>
                            <a href="<?php echo $this->settings->application->base_uri . 'settings/delete/SnmpHosts/' . $host->id  ?>" class="btn btn-danger fa fa-trash-alt"></a>
                        </div>
                    </td>
                    <td>
                        <?php echo $host->name ?>
                    </td>
                    <td>
                        <?php echo $host->ip ?>
                    </td>
                    <td class="text-center">
                        <?php echo $host->version ?>
                    </td>
                    <td>
                        <?php echo $host->community ?>
                    </td>
                    <td class="hidden-xs">
                        <div class="btn-group pull-right">
                            <a href="<?php echo $this->settings->application->base_uri . 'settings/snmphost/' . $host->id  ?>" class="btn btn-warning fa fa-edit"></a>
                            <a href="<?php echo $this->settings->application->base_uri . 'settings/delete/SnmpHosts/' . $host->id  ?>" class="btn btn-danger fa fa-trash-alt"></a>
                        </div>
                    </td>
                </tr>
                <?php endforeach ?>
            </tbody>
            <tfoot>
                <tr class="visible-xs">
                    <td colspan="8">
                        <a class="btn btn-primary" href="<?php echo $this->settings->application->base_uri ?>settings/snmphost/" title="Add device">
                            <i class="fa fa-plus"></i>
                        </a>
                    </td>
                </tr>
                <tr class="hidden-xs">
                    <td colspan="8" class="text-right">
                        <a class="btn btn-primary" href="<?php echo $this->settings->application->base_uri ?>settings/snmphost/" title="Add device">
                            <i class="fa fa-plus"></i>
                        </a>
                    </td>
                </tr>
            </tfoot>
        </table>
    </div>
</div>
