<?php /** @var Phalcon\Mvc\View $this */ ?>

<div class="panel panel-success sysinfo"
    data-updateinterval="<?php echo $this->settings->sysinfo->update_interval ?>">
    <?php $this->partial('is-loading') ?>

    <div class="panel-heading">
        <div class="btn-group pull-right">
            <?php $this->partial('index/default_widget_buttons', ['hasRefresh' => true, 'expanded' => true, 'widget' => $widget]) ?>
        </div>
        <h4 class="truncate-text" title="System info">System info</h4>
    </div>
    <ul class="list-group">
        <li class="list-group-item col-xs-12">
            <div class="col-xs-3">Host</div>
            <div class="col-xs-9 host">&hellip;</div>
        </li>

        <li class="list-group-item col-xs-12">
            <div class="col-xs-3">Uptime</div>
            <div class="col-xs-9 time delayed">&hellip;</div>
        </li>

        <li class="list-group-item col-xs-12">
            <div class="col-xs-3">Kernel</div>
            <div class="col-xs-9 kernel">&hellip;</div>
        </li>

        <li class="list-group-item col-xs-12">
            <div class="col-xs-3 ">RAM</div>
            <div class="col-xs-9">
                <div class="progress ram">
                    <div class="progress-bar progress-bar-success progress-bar-striped" role="progressbar" aria-label="RAM"></div>
                    <div class="percent">
                        <span></span>% used
                    </div>
                </div>
            </div>
        </li>
    </ul>
</div>