<?php /** @var Phalcon\Mvc\Controller $this */ ?>

<div id="records" class="tab-pane fade <?php echo $activetab == 'records' ? 'in active' : null ?>">
    <div class="table-responsive">
        <table class="table table-striped table-hover">
            <thead>
                <tr>
                    <th>Time</th>
                    <th>IP</th>
                    <th>Download</th>
                    <th>Upload</th>
                    <th>Ping</th>
                    <th>Jitter</th>
                    <th class="text-center">Browser</th>
                    <th class="text-center">Share</th>
                </tr>
            </thead>
            <tbody>
                <?php foreach($stats->items AS $stat) : ?>
                <tr>
                    <td class="text-nowrap">
                        <?php echo date('Y-m-d H:i', strtotime($stat['timestamp'])) ?>
                    </td>
                    <td>
                        <?php echo !empty($stat['ip']) ? $stat['ip'] : '&hellip;' ?>
                    </td>
                    <td>
                        <?php echo !empty($stat['dl']) ? $stat['dl'] . '&nbsp;Mbps' : '&hellip;' ?>
                    </td>
                    <td>
                        <?php echo !empty($stat['ul']) ? $stat['ul'] .'&nbsp;Mbps' : '&hellip;' ?>
                    </td>
                    <td>
                        <?php echo !empty($stat['ping']) ? $stat['ping'] . '&nbsp;ms' : '&hellip;' ?>
                    </td>
                    <td>
                        <?php echo !empty($stat['jitter']) ? $stat['jitter'] .'&nbsp;ms' : '&hellip;' ?>
                    </td>
                    <td class="text-center">
                        <?php $browser = json_decode($stat['extra'])->parse->software_name; ?>
                        <i class="text-success fa fa-<?php echo str_replace(' ', '-', strtolower($browser)) ?>" title="<?php echo $browser ?>"></i>
                    </td>
                    <td class="text-center">
                        <a href="<?php echo $this->settings->application->base_uri ?>Speedtest/share/<?php echo $stat['id'] ?>" target="_blank" class="btn btn-success btn-sm fa fa-share-alt" title="Share"></a>
                    </td>
                </tr>
                <?php endforeach ?>
            </tbody>
        </table>
    </div>
</div>
