
<div id="records" class="tab-pane fade <?php echo $activetab == 'records' ? 'in active' : null ?>">
    <div class="table-responsive">
        <table class="table table-striped table-hover">
            <thead>
                <tr>
                    <th>Time</th>
                    <th>IP</th>
                    <th>Download</th>
                    <th>Upload</th>
                    <th>Ping</th>
                    <th>Jitter</th>
                </tr>
            </thead>
            <tbody>
                <?php foreach($stats->items AS $stat) : ?>
                <tr>
                    <td class="text-left">
                        <?php echo $stat->timestamp ?>
                    </td>
                    <td class="text-left">
                        <?php echo !empty($stat->ip) ? $stat->ip : '...' ?>
                    </td>
                    <td class="text-left">
                        <?php echo !empty($stat->dl) ? $stat->dl . ' Mbps' : '...' ?>
                    </td>
                    <td class="text-left">
                        <?php echo !empty($stat->ul) ? $stat->ul .' Mbps' : '...' ?>
                    </td>
                    <td class="text-left">
                        <?php echo !empty($stat->ping) ? $stat->ping . ' ms ' : '...' ?>
                    </td>
                    <td class="text-left">
                        <?php echo !empty($stat->jitter) ? $stat->jitter .' ms' : '...' ?>
                    </td>
                </tr>
                <?php endforeach ?>
            </tbody>
        </table>
    </div>
</div>
