
<div class="panel panel-success pull-left transparent kodi-movies">
    <ul class="list-group panel-success">
        <li class="list-group-item list-group-item-success">
            <h4 title="<?php echo $movie->title ?>">
                <?php echo $movie->title ?>
            </h4>
        </li>

        <li class="list-group-item col-xs-12 col-lg-12">
            <div class="col-xs-12 text-center">
                <?php if(!empty($movie->trailer)) : ?>
                <div class="embed-responsive embed-responsive-16by9">
                    <iframe class="embed-responsive-item" src="//www.youtube.com/embed/<?php echo $movie->trailer ?>" frameborder="0" allowfullscreen></iframe>
                </div><?php else : ?>
                Sorry, no trailer found<?php endif ?>
            </div>
        </li>

        <li class="list-group-item col-xs-12 col-lg-12">
            <div class="col-xs-12 col-sm-3 text-bold">Plot</div>
            <div class="col-xs-12 col-sm-9">
                <?php echo $movie->info->plot ?>
            </div>
        </li>

        <li class="list-group-item col-xs-12 col-lg-12">
            <div class="col-xs-3 text-bold">Release date</div>
            <div class="col-xs-9">
                <?php echo $movie->info->released ?>
            </div>
        </li>

        <li class="list-group-item col-xs-12 col-lg-12">
            <div class="col-xs-3 text-bold">Runtime</div>
            <div class="col-xs-9">
                <?php echo $movie->info->runtime ?> minutes
            </div>
        </li>

        <li class="list-group-item col-xs-12 col-lg-12">
            <div class="col-xs-3 text-bold">Genres</div>
            <div class="col-xs-9">
                <?php echo implode(', ', $movie->info->genres) ?>
            </div>
        </li>

        <li class="list-group-item col-xs-12 col-lg-12">
            <div class="col-xs-3 text-bold">Actors</div>
            <div class="col-xs-9">
                <?php echo implode(', ', $movie->info->actors) ?>
            </div>
        </li>
    </ul>
</div>


<div class="panel-underlay"></div>