<?php /** @var Phalcon\Mvc\View $this */ ?>

<div class="panel panel-success couchpotato gallery"
    data-rotate-interval="<?php echo $this->settings->couchpotato->rotate_interval ?>"
    data-base-url="<?php echo $this->url->get() ?>"
    data-couchpotato-apikey="<?php echo $this->settings->couchpotato->api_key ?>"
    data-couchpotato-url="<?php echo $this->url->get($this->settings->couchpotato->url) ?>">
    <div class="panel-heading">
        <div class="backdrop"></div>
        <div class="btn-group pull-right">
            <button class="btn btn-default fa fa-chevron-left" title="Next movie" aria-label="Next movie"></button>
            <button class="btn btn-default fa fa-chevron-right" title="Previous movie" aria-label="Previous movie"></button>
            <button class="btn btn-default fa fa-search" title="Search wanted movies now!" aria-label="Search wanted movies now!"></button>
            <?php $this->partial('index/default_widget_buttons', ['hasRefresh' => true, 'widget' => $widget]) ?>
        </div>
        <h4 class="truncate-text" title="CouchPotato">CouchPotato</h4>
    </div>

    <div class="panel-body hidden-xs">
        <?php if ($couchpotato) : ?>
        <?php $i= 0; foreach($couchpotato as $movie) : ?>
        <a class="item <?php echo $i++ > 0 ? 'hidden' : 'show' ?>_not_important"
            href="<?php echo $this->url->get('couchpotato/movie/' . $movie->_id) ?>"
            data-type="iframe"
            data-fancybox="couchpotato"
            style="background-image: url('<?php echo current($movie->info->images->poster) ?>')">
            <div class="overlay"></div>
            <div class="title">
                <?php echo $movie->title ?>
            </div>
            <div class="subtitle">
                <?php echo $movie->info->tagline ?>
            </div>
        </a>
        <?php endforeach ?>
        <?php endif ?>
    </div>

    <a class="clone hidden_not_important">
        <div class="overlay"></div>
        <div class="title"></div>
        <div class="subtitle"></div>
    </a>
</div>
