
<div class="col-xs-12 col-sm-6 col-md-3 col-lg-3">
    <div class="panel panel-success pull-left devices" data-device-state-interval="<?php echo $this->config->dashboard->checkDeviceStatesInterval ?>">
        <div class="panel-heading">
            <div class="btn-group pull-right">
                <button class="btn btn-default fa fa-refresh rounded-not-mobile"></button>
                <button class="btn btn-default fa fa-plus visible-xs toggle-collapse"></button>
            </div>
            <h4>Devices</h4>
        </div>
        <ul class="list-group hidden-xs">
            <?php foreach($devices as $device) : ?>
            <li class="list-group-item col-xs-12<?php echo $device->show_on_dashboard ? null : ' hidden' ?>">
                <div class="col-xs-6 col-sm-5">
                    <?php echo $device->name ?>
                </div>
                <div class="col-xs-6 col-sm-7">
                    <div class="btn-group pull-right">
                        <?php if(!empty($device->webtemp)) : ?>
                        <a href="devices/webtemp/?id=<?php echo $device->id ?>" class="btn btn-default" data-fancybox data-type="iframe" title="Webtemp: <?php echo $device->name ?>">
                            <span class="fa fa-thermometer"></span>
                        </a>
                        <?php endif ?>

                        <?php if($device->id == $this->config->hypervadmin->device) : ?>
                        <a href="<?php echo $this->config->application->baseUri?>hyper_v_admin/" class="btn btn-default disabled" data-fancybox data-type="iframe" title="HyperVAdmin">
                            <span class="fa fa-server"></span>
                        </a>
                        <?php endif ?>

                        <a class="btn btn-default disabled devicestate"
                            data-ip="<?php echo $device->ip ?>"
                            data-mac="<?php echo $device->mac ?>"
                            data-shutdown-method="<?php echo $device->shutdown_method ?>"
                            data-shutdown-user="<?php echo $device->shutdown_user ?>"
                            data-shutdown-password="<?php echo $device->shutdown_password ?>">
                            <span class="fa fa-refresh fa-spin"></span>
                        </a>
                    </div>
                </div>
            </li>
            <?php endforeach ?>
        </ul>
    </div>
</div>