<div class="col-xs-12 col-sm-6 col-md-3 col-lg-3">
    <div class="panel panel-success pull-left devices" data-device-state-interval="<?php echo $this->config->dashboard->checkDeviceStatesInterval ?>">
        <div class="panel-heading">
            <div class="btn-group pull-right">
                <button class="btn btn-default glyphicon glyphicon-refresh"></button>
                <button class="btn btn-default glyphicon glyphicon-plus visible-xs toggle"></button>
            </div>
            <h4 class="pull-left">Devices</h4>
        </div>
        <ul class="list-group hidden-xs">
            <?php foreach($devices as $device) : ?>
            <li class="list-group-item col-xs-12 col-sm-12 col-lg-12<?php echo $device->show_on_dashboard ? null : ' hidden' ?>">
                <div class="col-xs-6 col-sm-5 col-lg-6">
                    <?php echo $device->name ?>
                </div>
                <div class="col-xs-6 col-sm-7 col-lg-6">
                    <div class="btn-group pull-right">
                        <?php if(!empty($device->webtemp)) : ?>
                        <a href="devices/webtemp/?id=<?php echo $device->id ?>" class="fancybox btn btn-default" data-fancybox-type="iframe" title="Webtemp: <?php echo $device->name ?>">
                            <span class="glyphicon glyphicon-dashboard"></span>
                        </a>
                        <?php endif ?>
                        <a class="btn btn-default disabled devicestate" 
                            data-ip="<?php echo $device->ip ?>" 
                            data-mac="<?php echo $device->mac ?>" 
                            data-shutdown-method="<?php echo $device->shutdown_method ?>"
                            data-shutdown-user="<?php echo $device->shutdown_user ?>"
                            data-shutdown-password="<?php echo $device->shutdown_password ?>"
                            >
                            <span class="glyphicon glyphicon-refresh icon-refresh-animate"></span>
                        </a>
                    </div>
                </div>
            </li>
            <?php endforeach ?>
        </ul>
    </div>
</div>