<div class="col-xs-12 col-sm-12 col-md-4 col-lg-5">
    <div class="panel panel-success pull-left harddisks">
        <div class="panel-heading">
            <a href="#" class="btn btn-default glyphicon glyphicon-refresh pull-right disabled"></a>
            <h4>Disk usage</h4>
        </div>
        <ul class="list-group">
            <?php foreach($disks as $disk => $content) : ?>
            <li class="list-group-item col-xs-12 col-sm-12 col-lg-12">
                <div class="col-xs-3">
                    <?php echo $disk ?>
                </div>
                <div class="col-xs-9">
                    <div class="progress">
                        <div class="progress-bar progress-bar-<?php echo $content['class'] ?> progress-bar-striped" role="progressbar" style="width:<?php echo $content['used_percentage'] ?>%"></div>
                        <div class="percent"><?php echo $content['used_percentage'] ?>% used</div>

                    </div>
                </div>
            </li>
            <?php endforeach ?>
        </ul>
    </div>
</div>