<div class="col-xs-12 col-sm-4 col-lg-4">
    <div class="panel panel-success pull-left <?php echo strtolower($title) ?>">
        <div class="panel-heading">
            <div class="btn-group pull-right">
                <a href="#" class="btn btn-default glyphicon glyphicon-refresh"></a>
                <a href="#" class="btn btn-default glyphicon glyphicon-plus visible-xs toggle"></a>
            </div>
            <h4><?php echo $title ?></h4>
        </div>
        <ul class="list-group hidden-xs"></ul>
    </div>
</div>