<div class="col-xs-12 col-sm-6 col-md-4 col-lg-4">
    <div class="panel panel-success kodi movies" data-rotate-interval="<?php echo $this->config->dashboard->rotateMoviesInterval ?>">
        <div class="panel-heading">
            <div class="btn-group pull-right">
                <button class="btn btn-default fa fa-chevron-left"></button>
                <button class="btn btn-default fa fa-chevron-right"></button>
                <button class="btn btn-default fa fa-plus visible-xs toggle-collapse"></button>
            </div>
            <h4>Latest movies</h4>
        </div>
        <div class="panel-body hidden-xs">
            <?php $i = 0; foreach($movies as $movie) : ?>
            <a class="movie item fancybox-iframe <?php echo $i++ > 0 ? 'hidden' : 'show' ?>_not_important" 
                href="<?php echo $this->config->application->baseUri .'kodi/movie/' . $movie->idMovie ?>"
                data-fancybox-maxwidth="600px"
                title="<?php echo utf8_encode($movie->c03) ?>"
                style="background-image: url('<?php echo $this->config->application->baseUri . (!empty($movie->c08) ? 'kodi/getImage?which=movies&id=' . $movie->idMovie : 'img/icons/unknown.jpg')  ?>')">
                <div class="overlay"></div>
                <div class="title" title="<?php echo $title = utf8_encode($movie->c00) ?>"><?php echo $title ?></div>
                <div class="subtitle" title="<?php echo $title = utf8_encode($movie->c03) ?>"><?php echo $title ?></div>
            </a>
            <?php endforeach ?> 
        </div>
    </div>
</div>