<div class="col-xs-12 col-sm-8 col-lg-4">
    <div class="panel panel-success albums">
        <div class="panel-heading">
            <h4>Latest albums</h4>
        </div>
        <div class="panel-body">
            <?php $i = 0; foreach($albums as $album) : ?>
            <img src="<?php echo $album['thumb'] ?>"<?php echo $i++ > 0 ? ' class="hidden_not_important"' : null ?> />
            <?php $i++;
                  endforeach ?> 

            <nav>
                <ul class="pagination pagination-sm success">
                    <?php for($i = 1; $i <= count($movies); $i++) : ?>
                    <li<?php echo $i == 1 ? ' class="active"' : null ?>>
                        <a href="#"><?php echo $i ?></a>
                    </li>
                    <?php endfor ?>
                </ul>
            </nav>
        </div>
    </div>
</div>