<div class="col-xs-12 col-sm-8 col-lg-4">
    <div class="panel panel-success movies">
        <div class="panel-heading">
            <a href="#" class="btn btn-default glyphicon glyphicon-plus visible-xs pull-right toggle"></a>
            <h4>Latest movies</h4>
        </div>
        <div class="panel-body hidden-xs">
            <?php $i = 0; foreach($movies as $movie) : ?>
            <div class="movie item<?php echo $i++ > 0 ? ' hidden_not_important' : null ?>" style="background-image: url('<?php echo $movie->c08 ?>')"></div>
            <?php $i++;
                  endforeach ?> 

            <nav>
                <ul class="pagination pagination-sm">
                    <?php for($i = 1; $i <= count($movies); $i++) : ?>
                    <li<?php echo $i == 1 ? ' class="active"' : null ?>>
                        <a href="#"><?php echo $i ?></a>
                    </li>
                    <?php endfor ?>
                </ul>
            </nav>
        </div>
    </div>
</div>