<div class="col-xs-12 col-sm-8 col-lg-4">
    <div class="panel panel-success albums">
        <div class="panel-heading">
            <h4>Latest albums</h4>
        </div>
        <div class="panel-body">
            <?php $i = 0; foreach($albums as $album) : ?>
            <div class="album item <?php echo $i++ > 0 ? ' hidden_not_important' : null ?>" 
                style="background-image: url('<?php echo !empty($album['thumb']) ? $album['thumb'] : 'img/icons/unknown.jpg'  ?>')">
                <div class="overlay"></div>
                <div class="artists"><?php echo $album['strArtists'] ?></div>
                <div class="title"><?php echo $album['strAlbum'] ?></div>
            </div>
            
            <?php $i++;
                  endforeach ?> 

            <nav>
                <ul class="pagination pagination-sm success">
                    <?php for($i = 1; $i <= count($albums); $i++) : ?>
                    <li<?php echo $i == 1 ? ' class="active"' : null ?>>
                        <a href="#"><?php echo $i ?></a>
                    </li>
                    <?php endfor ?>
                </ul>
            </nav>
        </div>
    </div>
</div>