<div class="col-xs-12 col-sm-6 col-md-4 col-lg-4">
    <div class="panel panel-success episodes">
        <div class="panel-heading">
            <div class="btn-group pull-right">
                <a href="#" class="btn btn-default glyphicon glyphicon-chevron-left"></a>
                <a href="#" class="btn btn-default glyphicon glyphicon-chevron-right"></a>
                <a href="#" class="btn btn-default glyphicon glyphicon-plus visible-xs toggle"></a>
            </div>
            <h4>Latest episodes</h4>
        </div>
        <div class="panel-body hidden-xs">
            <?php $i = 0; foreach($episodes as $episode) : ?>
            <div class="episode item <?php echo $i++ > 0 ? ' hidden_not_important' : null ?>" 
                style="background-image: url('<?php echo $this->config->application->baseUri . (!empty($episode->c06) ? 'index/getImage?url=' . $episode->c06 : 'img/icons/unknown.jpg')  ?>')">
                <div class="overlay"></div>
                <div class="title"><?php echo utf8_encode($episode->getShow()->c00) ?></div>
                <div class="subtitle"><?php echo utf8_encode($episode->c00) ?></div>
            </div>
            <?php $i++; endforeach ?> 
        </div>
    </div>
</div>