<div class="col-xs-12 col-sm-6 col-md-4 col-lg-4">
    <div class="panel panel-success albums">
        <div class="panel-heading">
            <div class="btn-group pull-right">
                <a href="#" class="btn btn-default glyphicon glyphicon-chevron-left"></a>
                <a href="#" class="btn btn-default glyphicon glyphicon-chevron-right"></a>
                <a href="#" class="btn btn-default glyphicon glyphicon-plus visible-xs pull-right toggle"></a>
            </div>
            <h4>Latest albums</h4>
        </div>
        <div class="panel-body hidden-xs">
            <?php $i = 0; foreach($albums as $album) : ?>
            <div class="album item <?php echo $i++ > 0 ? ' hidden_not_important' : null ?>" 
                style="background-image: url('<?php echo $this->config->application->baseUri . (!empty($album->strImage) ? 'index/getImage?url=' . $album->strImage : 'img/icons/unknown.jpg')  ?>')">
                <div class="overlay"></div>
                <div class="title"><?php echo utf8_encode($album->strArtists) ?></div>
                <div class="subtitle"><?php echo utf8_encode($album->strAlbum) ?></div>
            </div>
            <?php $i++; endforeach ?> 
        </div>
    </div>
</div>