<div class="col-xs-12 col-sm-8 col-lg-4">
    <div class="panel panel-success episodes">
        <div class="panel-heading">
            <h4>Latest episodes</h4>
        </div>
        <div class="panel-body">
            <?php $i = 0; foreach($episodes as $episode) : ?>
            <div class="episode item <?php echo $i++ > 0 ? ' hidden_not_important' : null ?>" 
                style="background-image: url('<?php echo !empty($episode->c06) ? $episode->c06 : 'img/icons/unknown.jpg'  ?>')">
                <div class="overlay"></div>
                <div class="title"><?php echo $episode->getShow()->c00 ?></div>
                <div class="subtitle"><?php echo $episode->c00 ?></div>
            </div>
            
            <?php $i++;
                  endforeach ?> 

            <nav>
                <ul class="pagination pagination-sm success">
                    <?php for($i = 1; $i <= count($episodes); $i++) : ?>
                    <li<?php echo $i == 1 ? ' class="active"' : null ?>>
                        <a href="#"><?php echo $i ?></a>
                    </li>
                    <?php endfor ?>
                </ul>
            </nav>
        </div>
    </div>
</div>