<div class="col-xs-12 col-sm-6 col-md-4 col-lg-4">
    <div class="panel panel-success movies" data-rotate-interval="<?php echo $this->config->dashboard->rotateMoviesInterval ?>">
        <div class="panel-heading">
            <div class="btn-group pull-right">
                <a href="#" class="btn btn-default glyphicon glyphicon-chevron-left"></a>
                <a href="#" class="btn btn-default glyphicon glyphicon-chevron-right"></a>
                <a href="#" class="btn btn-default glyphicon glyphicon-plus visible-xs toggle"></a>
            </div>
            <h4>Latest movies</h4>
        </div>
        <div class="panel-body hidden-xs">
            <?php $i = 0; foreach($movies as $movie) : ?>
            <div class="movie item<?php echo $i++ > 0 ? ' hidden_not_important' : null ?>" 
                style="background-image: url('<?php echo $this->config->application->baseUri . (!empty($movie->c08) ? 'index/getImage?which=movies&id=' . $movie->idMovie : 'img/icons/unknown.jpg')  ?>')">
                <div class="overlay"></div>
                <div class="title" title="<?php echo $title = utf8_encode($movie->c00) ?>"><?php echo $title ?></div>
                <div class="subtitle" title="<?php echo $title = utf8_encode($movie->c03) ?>"><?php echo $title ?></div>
            </div>
            <?php $i++; endforeach ?> 
        </div>
    </div>
</div>