<div class="col-xs-12 col-sm-12 col-md-4 col-lg-5">
    <div class="panel panel-success pull-left harddisks"
        data-phpsysinfo-url="<?php echo $this->config->dashboard->phpSysInfoURL ?>" 
        data-phpsysinfo-vcore="<?php echo $this->config->dashboard->phpSysInfoVCore ?>">
        <div class="panel-heading">
            <div class="btn-group pull-right">
                <a href="#" class="btn btn-default glyphicon glyphicon-refresh"></a>
                <a href="#" class="btn btn-default glyphicon glyphicon-plus visible-xs toggle"></a>
            </div>
            <h4>Disk usage</h4>
        </div>
        <ul class="list-group hidden-xs">            
            <?php foreach($phpsysinfoData->FileSystem->Mount as $mount) : ?>
            <li class="list-group-item col-xs-12 col-sm-12 col-lg-12">
                <div class="col-xs-3 name"><?php echo $mount->MountPoint ?></div>
                <div class="col-xs-9">
                    <div class="progress">
                        <div class="progress-bar progress-bar-striped progress-bar-<?php echo $mount->Class ?>" role="progressbar" style="width:<?php echo $mount->Percent ?>%"></div>
                        <div class="percent"><?php echo $mount->Percent ?>%</div>
                    </div>
                </div>
            </li>
            <?php endforeach ?>
        </ul>
    </div>
</div>
