<div class="col-xs-12 col-sm-6 col-md-5 col-lg-4">
    <div class="panel panel-success pull-left sysinfo" 
        data-phpsysinfo-url="<?php echo $this->config->dashboard->phpSysInfoURL ?>" 
        data-phpsysinfo-vcore="<?php echo $this->config->dashboard->phpSysInfoVCore ?>">
        <div class="panel-heading">
            <div class="btn-group pull-right">
                <a href="#hardware" class="btn btn-default glyphicon glyphicon-wrench fancybox disabled" data-fancybox-maxwidth="500" title="Hardware"></a>
                <a href="#" class="btn btn-default glyphicon glyphicon-refresh"></a>
                <a href="#" class="btn btn-default glyphicon glyphicon-minus visible-xs toggle"></a>
            </div>
            <h4>System info</h4>
        </div>
        <ul class="list-group">
            <li class="list-group-item col-xs-12 col-lg-12">
                <div class="col-xs-3">Host</div>
                <div class="col-xs-9 host value">&nbsp;</div>
            </li>

            <li class="list-group-item col-xs-12 col-lg-12 os">
                <div class="col-xs-3">OS</div>
                <div class="col-xs-9 distro value">
                    <span class="pull-left"></span>
                    <div class="icon pull-right"></div>
                </div>
            </li>

            <li class="list-group-item col-xs-12 col-lg-12">
                <div class="col-xs-3">Uptime</div>
                <div class="col-xs-9 uptime value">&nbsp;</div>
            </li>

            <li class="list-group-item col-xs-12 col-lg-12">
                <div class="col-xs-3">Kernel</div>
                <div class="col-xs-9 kernel value">&nbsp;</div>
            </li>

            <li class="list-group-item col-xs-12 col-lg-12">
                <div class="col-xs-3">Updates</div>
                <div class="col-xs-9 value update" data-phpsysinfo-url="<?php echo $this->config->dashboard->phpSysInfoURL ?>">
                    <span class="label label-default packages" title="Update packages">Packages: -</span>
                    <span class="label label-default security" title="Update security">Security: -</span>
                </div>
            </li>

            <li class="list-group-item col-xs-12 col-lg-12">
                <div class="col-xs-3 ">RAM</div>
                <div class="col-xs-9">
                    <div class="progress ram">
                        <div class="progress-bar progress-bar-success progress-bar-striped" role="progressbar"></div>
                        <div class="percent"><span>0</span>% used</div>
                    </div>
                </div>
            </li>

            <li class="list-group-item col-xs-12 col-lg-12">
                <div class="col-xs-3 ">Swap</div>
                <div class="col-xs-9">
                    <div class="progress swap">
                        <div class="progress-bar progress-bar-success progress-bar-striped" role="progressbar"></div>
                        <div class="percent"><span>0</span>% used</div>
                    </div>
                </div>
            </li>
        </ul>
    </div>
</div>

<?php $this->partial('index/partials/indexAction/phpsysinfo_hardware') ?>