<div class="col-xs-12 col-sm-12 col-md-4 col-lg-5">
    <div class="panel panel-success pull-left harddisks">
        <div class="panel-heading">
            <div class="btn-group pull-right">
                <a href="#" class="btn btn-default glyphicon glyphicon-refresh"></a>
                <a href="#" class="btn btn-default glyphicon glyphicon-plus visible-xs toggle"></a>
            </div>
            <h4>Disk usage</h4>
        </div>
        <ul class="list-group hidden-xs">
            <li class="list-group-item col-xs-12 col-sm-12 col-lg-12 hidden">
                <div class="col-xs-3 name"></div>
                <div class="col-xs-9">
                    <div class="progress">
                        <div class="progress-bar progress-bar-striped" role="progressbar"></div>
                        <div class="percent"></div>
                    </div>
                </div>
            </li>
        </ul>
    </div>
</div>