<div class="col-xs-12 col-sm-12 col-md-5 col-lg-5">
    <div class="panel panel-success pull-left harddisks"
        data-phpsysinfo-url="<?php echo $this->config->phpsysinfo->URL ?>"
        data-phpsysinfo-username="<?php echo $this->config->phpsysinfo->username ?>"
        data-phpsysinfo-password="<?php echo $this->config->phpsysinfo->password ?>">
        <div class="panel-heading">
            <div class="btn-group pull-right">
                <button class="btn btn-default fa fa-sync rounded-not-mobile"></button>
                <button class="btn btn-default fa fa-plus visible-xs toggle-collapse"></button>
            </div>
            <h4>Disk usage</h4>
        </div>
        <ul class="list-group hidden-xs">
            <?php foreach($phpsysinfoData->FileSystem->Mount as $mount) : ?>
            <li class="list-group-item col-xs-12">
                <div class="col-xs-5 col-md-5 col-lg-3 name">
                    <?php echo $mount->MountPoint ?>
                </div>
                <div class="col-xs-7 col-md-7 col-lg-9">
                    <div class="progress">
                        <div class="progress-bar progress-bar-striped progress-bar-<?php echo $mount->Class ?>" role="progressbar" style="width:<?php echo $mount->Percent ?>%"></div>
                        <div class="percent">
                            <?php echo $mount->Percent ?>%
                        </div>
                    </div>
                </div>
            </li>
            <?php endforeach ?>
        </ul>
    </div>
</div>
