<div class="hidden_not_important pull-left hardware">
    <div class="panel panel-success hardware">
        <div class="panel-heading">
            <a href="#" class="btn btn-default glyphicon glyphicon-refresh pull-right"></a>
            <h4>Hardware</h4>
        </div>
        <ul class="list-group  panel-success">
            <li class="list-group-item col-xs-12 col-lg-12">
                <div class="col-xs-3">CPU</div>
                <div class="col-xs-9 cpu-model-label value"></div>
            </li>
            <li class="list-group-item col-xs-12 col-lg-12 cpu-cores hidden_not_important">
                <div class="cpu-core col-xs-3"></div>
                <div class="core-stats col-xs-9">
                    <div class="col-xs-6">Temp: </div>
                    <div class="core-temp col-xs-6"></div>
                    <div class="col-xs-6">vCore: </div>
                    <div class="core-vcore col-xs-6"></div>
                    <div class="col-xs-6">Current: </div>
                    <div class="core-current col-xs-6"></div>
                    <div class="col-xs-6">Min: </div>
                    <div class="core-min col-xs-6"></div>
                    <div class="col-xs-6">Max: </div>
                    <div class="core-max col-xs-6"></div>
                </div>
            </li>

            <li class="list-group-item col-xs-12 col-lg-12">
                <div class="col-xs-3">Mobo</div>
                <div class="col-xs-9 motherboard value"></div>
            </li>

            <li class="list-group-item col-xs-12 col-lg-12">
                <div class="col-xs-3">Network</div>
                <div class="lan-stats col-xs-9">
                    <div class="col-xs-6">Name: </div>
                    <div class="lan-name col-xs-6"></div>
                    <div class="col-xs-6">IP: </div>
                    <div class="lan-ip col-xs-6"></div>
                    <div class="col-xs-6">MAC: </div>
                    <div class="lan-mac col-xs-6"></div>
                    <div class="col-xs-6">Speed: </div>
                    <div class="lan-speed col-xs-6"></div>
                    <div class="col-xs-6">Rx: </div>
                    <div class="lan-rx col-xs-6"></div>
                    <div class="col-xs-6">Tx: </div>
                    <div class="lan-tx col-xs-6"></div>
                </div>
            </li>

            <li class="list-group-item col-xs-12 col-lg-12 fans">
                <div class="col-xs-3">Fans</div>
                <div class="fan-stats col-xs-9">
                    <div>
                        <div class="col-xs-6 name"></div>
                        <div class="col-xs-6 value"></div>
                    </div>
                </div>
            </li>
        </ul>
    </div>
</div>