
<div class="hidden_not_important hardware" id="hardware"
    data-phpsysinfo-url="<?php echo $this->config->phpsysinfo->URL ?>"
    data-phpsysinfo-username="<?php echo $this->config->phpsysinfo->username ?>"
    data-phpsysinfo-password="<?php echo $this->config->phpsysinfo->password ?>">
    <div class="panel panel-success pull-left hw-panel">
        <div class="panel-heading">
            <button class="btn btn-default fa fa-refresh pull-right"></button>
            <h4 class="pull-left">Hardware</h4>
        </div>
        <ul class="list-group panel-success">
            <li class="list-group-item col-xs-12 col-lg-12">
                <div class="col-xs-3">CPU</div>
                <div class="col-xs-9 cpu-model-label value">
                    <?php echo $phpsysinfoData->Hardware->CPU->CpuCore[0]->{'@attributes'}->Model ?>
                </div>
            </li>

            <li class="list-group-item col-xs-12 col-lg-12">
                <div class="col-xs-3">Mobo</div>
                <div class="col-xs-9 motherboard value">
                    <?php echo $phpsysinfoData->Hardware->{'@attributes'}->Name ?>
                </div>
            </li>

            <?php $i = 0; foreach($phpsysinfoData->Hardware->CPU->CpuCore as $core) : ?>
            <li class="list-group-item col-xs-12 col-lg-12 cpu-cores">
                <div class="cpu-core col-xs-3">
                    Core <?php echo $i ?>
                </div>
                <div class="core-stats col-xs-9">
                    <div class="col-xs-6">Temp: </div>
                    <div class="core-temp col-xs-6">
                        <?php echo $core->Temp ?>
                    </div>
                    <div class="col-xs-6">Current: </div>
                    <div class="core-current col-xs-6">
                        <?php echo $core->{'@attributes'}->CpuSpeed ?> GHz
                    </div>
                    <div class="col-xs-6">Min: </div>
                    <div class="core-min col-xs-6">
                        <?php echo $core->{'@attributes'}->CpuSpeedMin ?> GHz
                    </div>
                    <div class="col-xs-6">Max: </div>
                    <div class="core-max col-xs-6">
                        <?php echo $core->{'@attributes'}->CpuSpeedMax ?> GHz
                    </div>
                </div>
            </li>
            <?php $i++;
                  endforeach ?>

            <li class="list-group-item col-xs-12 col-lg-12">
                <div class="col-xs-3">Network</div>
                <div class="lan-stats col-xs-9">
                    <?php $i = 0; foreach($phpsysinfoData->Network->NetDevice as $network) :

                              if(!isset($network->{'@attributes'})) continue;
                              $info = explode(';', $network->{'@attributes'}->Info) ?>
                    <div>
                        <div class="col-xs-6">Name: </div>
                        <div class="lan-name col-xs-6">
                            <?php echo $network->{'@attributes'}->Name ?>
                        </div>
                        <div class="col-xs-6">IP: </div>
                        <div class="lan-ip col-xs-6">
                            <?php echo count($info) > 1 ? $info[1] : $info[0] ?>
                        </div>
                        <?php if(count($info) > 1) : ?>
                        <div class="col-xs-6">MAC: </div>
                        <div class="lan-mac col-xs-6">
                            <?php echo $info[0] ?>
                        </div>
                        <?php if(isset($info[2])) : ?>
                        <div class="col-xs-6">Speed: </div>
                        <div class="lan-speed col-xs-6">
                            <?php echo $info[2] ?>
                        </div>
                        <?php endif ?>
                        <?php endif ?>
                        <div class="col-xs-6">Rx: </div>
                        <div class="lan-rx col-xs-6">
                            <?php echo round($network->{'@attributes'}->RxBytes / 1024 / 1024 / 1024 * 100) / 100 ?> GB
                        </div>
                        <div class="col-xs-6">Tx: </div>
                        <div class="lan-tx col-xs-6">
                            <?php echo round($network->{'@attributes'}->TxBytes / 1024 / 1024 / 1024 * 100) / 100 ?> GB
                        </div>
                        <?php if(++$i != count($phpsysinfoData->Network->NetDevice)) : ?>
                        <hr class="pull-left col-xs-12 no-gutter" />
                        <?php endif ?>
                    </div>
                    <?php endforeach ?>
                </div>
            </li>
        </ul>
    </div>
</div>
