<div class="col-xs-12 col-sm-8 col-lg-8">
    <div class="panel panel-success cpu">
        <div class="panel-heading">
            <button class="btn btn-default fa fa-plus visible-xs pull-right toggle-collapse"></button>
            <h4>CPU</h4>
        </div>
        <div class="panel-body hidden-xs">
            <iframe src="<?php echo $this->config->dashboard->rCpuURL ?>"></iframe>
        </div>
    </div>
</div>