<div class="shutdown">
    <h2>Shutdown <span></span></h2>

    <form>
        <div class="form-group">
            <label for="shutdown_user">User</label>
            <input type="text" name="user" id="shutdown_user" class="form-control" />
        </div>

        <div class="form-group">
            <label for="shutdown_password">Password</label>
            <input type="password" name="password" id="shutdown_password" class="form-control" />
        </div>

        <input type="hidden" name="ip" />
        <input type="submit" id="do_shutdown" class="btn btn-danger pull-right" value="Shutdown" />
    </form>
</div>