
<div class="col-xs-12 col-sm-6 col-md-4 col-lg-4">
    <div class="panel panel-success pull-left sickrage with-nav-tabs"
        data-sickrage-apikey="<?php echo $this->config->dashboard->sickrageAPIKey ?>"
        data-sickrage-url="<?php echo $this->config->dashboard->sickrageURL ?>">
        <div class="panel-heading">
            <ul class="nav nav-tabs pull-left">
                <li class="active">
                    <a data-toggle="tab" href="#today" class="pull-right">Sickrage today</a>
                </li>
                <li>
                    <a data-toggle="tab" href="#soon" class="pull-right">Sickrage soon</a>
                </li>
            </ul>

            <div class="btn-group pull-right">
                <button class="btn btn-default fa fa-refresh rounded-not-mobile"></button>
                <button class="btn btn-default fa fa-plus visible-xs toggle-collapse"></button>
            </div>
        </div>

        <div class="tab-content">
            <div id="today" class="tab-pane fade in active panel">
                <div class="list-group hidden-xs">
                    <a class="hidden list-group-item col-xs-12" href="#">
                        <div class="episode"></div>
                        <div data-fancybox="sickrage-today" class="hidden_not_important sickrage-detail">
                            <div class="panel panel-success">
                                <div class="panel-heading">
                                    <h4></h4>
                                </div>
                                <div class="panel-body"></div>
                            </div>
                        </div>
                    </a>
                </div>
            </div>

            <div id="soon" class="tab-pane panel">
                <div class="list-group hidden-xs hidden_not_important">
                    <a class="hidden list-group-item col-xs-12" href="#">
                        <div class="episode"></div>
                        <div data-fancybox="sickrage-soon" class="hidden_not_important sickrage-detail">
                            <div class="panel panel-success">
                                <div class="panel-heading">
                                    <h4></h4>
                                </div>
                                <div class="panel-body"></div>
                            </div>
                        </div>
                    </a>
                </div>
            </div>
        </div>
    </div>
</div>