
<div class="col-xs-12 col-sm-6 col-md-4 col-lg-4">
    <div class="panel panel-success pull-left sickrage"
        data-sickrage-apikey="<?php echo $this->config->sickrage->APIKey ?>"
        data-sickrage-url="<?php echo $this->config->sickrage->URL ?>">
        <div class="panel-heading">
            <div class="btn-group pull-right">
                <button class="btn btn-default fa fa-refresh rounded-not-mobile"></button>
                <button class="btn btn-default fa fa-plus visible-xs toggle-collapse"></button>
            </div>
            <h4>Sickrage</h4>
        </div>

        <div class="panel-body hidden-xs">
            <ul class="nav nav-tabs">
                <li class="active">
                    <a data-toggle="tab" href="#today" class="pull-right">Today</a>
                </li>
                <li>
                    <a data-toggle="tab" href="#soon" class="pull-right">Soon</a>
                </li>
            </ul>

            <div class="tab-content">
                <div id="today" class="tab-pane fade in active panel">
                    <div class="list-group">
                        <a class="hidden list-group-item col-xs-12" href="#">
                            <div class="episode"></div>

                        </a>
                    </div>
                </div>

                <div id="soon" class="tab-pane panel">
                    <div class="list-group">
                        <a class="hidden list-group-item col-xs-12" href="#">
                            <div class="episode"></div>
                        </a>
                    </div>
                </div>
            </div>
        </div>

        <div data-fancybox="sickrage-today" class="hidden_not_important sickrage-detail" style="width:800px">
            <div class="panel panel-success">
                <ul class="list-group panel-success">
                    <li class="list-group-item list-group-item-success">
                        <h4></h4>
                    </li>
                    <li class="list-group-item col-xs-12 col-lg-12">
                        <div class="col-xs-12 col-sm-3 text-bold">Plot</div>
                        <div class="col-xs-12 col-sm-9 plot"></div>
                    </li>
                    <li class="list-group-item col-xs-12 col-lg-12">
                        <div class="col-xs-3 text-bold">Season</div>
                        <div class="col-xs-9 season"></div>
                    </li>
                    <li class="list-group-item col-xs-12 col-lg-12">
                        <div class="col-xs-3 text-bold">Episode</div>
                        <div class="col-xs-9 episode"></div>
                    </li>
                    <li class="list-group-item col-xs-12 col-lg-12">
                        <div class="col-xs-3 text-bold">Episode name</div>
                        <div class="col-xs-9 episodename"></div>
                    </li>
                    <li class="list-group-item col-xs-12 col-lg-12">
                        <div class="col-xs-3 text-bold">Air date</div>
                        <div class="col-xs-9 airdate"></div>
                    </li>
                </ul>
            </div>
        </div>

    </div>
</div>