<div class="col-xs-12 col-sm-6 col-md-4 col-lg-4">
    <div class="panel panel-success subsonic pull-left"
        data-url="<?php echo $this->config->dashboard->subsonicURL ?>"
        data-username="<?php echo $this->config->dashboard->subsonicUsername ?>"
        data-password="<?php echo $this->config->dashboard->subsonicPassword ?>">
        <div class="panel-heading">
            <div class="btn-group pull-right">
                <a href="#" class="btn btn-default glyphicon glyphicon-chevron-left"></a>
                <a href="#" class="btn btn-default glyphicon glyphicon-chevron-right"></a>
                <a href="#" class="btn btn-default glyphicon glyphicon-refresh"></a>
                <a href="#" class="btn btn-default glyphicon glyphicon-plus visible-xs toggle"></a>
            </div>
            <h4>Subsonic</h4>
        </div>
        <div class="panel-body hidden-xs">
            <a class="item fancybox show_not_important" href="#subsonic_detail">
                <div class="overlay"></div>
                <div class="title"></div>
                <div class="subtitle"></div>
            </a>
        </div>

        <div class="hidden_not_important" id="subsonic_detail" style="width:400px">
            <div class="panel panel-success pull-left">
                <div class="panel-heading">
                    <a href="#" class="btn btn-default glyphicon glyphicon-refresh pull-right"></a>
                    <h4></h4>
                </div>
                <ul class="list-group panel-success">
                    <li class="list-group-item col-xs-12 col-lg-12">
                        <div class="col-xs-3">Track</div>
                        <div class="col-xs-9 track"></div>
                    </li>

                    <li class="list-group-item col-xs-12 col-lg-12">
                        <div class="col-xs-3">Album</div>
                        <div class="col-xs-9 album"></div>
                    </li>

                    <li class="list-group-item col-xs-12 col-lg-12">
                        <div class="col-xs-3">Year</div>
                        <div class="col-xs-9 year"></div>
                    </li>

                    <li class="list-group-item col-xs-12 col-lg-12">
                        <div class="col-xs-3">Genre</div>
                        <div class="col-xs-9 genre"></div>
                    </li>

                    <li class="list-group-item col-xs-12 col-lg-12">
                        <div class="col-xs-3">Duration</div>
                        <div class="col-xs-9 duration"></div>
                    </li>

                    <li class="list-group-item col-xs-12 col-lg-12">
                        <div class="col-xs-3">Bitrate</div>
                        <div class="col-xs-9 bitrate"></div>
                    </li>

                    <li class="list-group-item col-xs-12 col-lg-12">
                        <div class="col-xs-3">Playcount</div>
                        <div class="col-xs-9 playcount"></div>
                    </li>

                    <li class="list-group-item col-xs-12 col-lg-12">
                        <div class="col-xs-3">Last played</div>
                        <div class="col-xs-9 lastplayed"></div>
                    </li>
                </ul>
            </div>
        </div>
    </div>
</div>
