<div class="col-xs-12 col-sm-6 col-md-4 col-lg-4">
    <div class="panel panel-success subsonic"
        data-url="<?php echo $this->config->dashboard->subsonicURL ?>"
        data-username="<?php echo $this->config->dashboard->subsonicUsername ?>"
        data-password="<?php echo $this->config->dashboard->subsonicPassword ?>">
        <div class="panel-heading">
            <div class="btn-group pull-right">
                <a href="#" class="btn btn-default glyphicon glyphicon-refresh"></a>
                <a href="#" class="btn btn-default glyphicon glyphicon-minus visible-xs toggle"></a>
            </div>
            <h4>Subsonic</h4>
        </div>
        <div class="panel-body hidden-xs">
            <a class="subsonic item fancybox show_not_important">
                <div class="overlay"></div>
                <div class="title"></div>
                <div class="subtitle"></div>
            </a>
        </div>
    </div>
</div>