<div class="col-xs-12 col-sm-6 col-lg-4">
    <div class="panel panel-success pull-left sysinfo">
        <div class="panel-heading">
            <a href="#" class="btn btn-default glyphicon glyphicon-refresh pull-right"></a>
            <a href="#hardware" class="btn btn-default glyphicon glyphicon-wrench pull-right fancybox disabled" data-fancybox-maxwidth="500"></a>
            <h4>System info</h4>
        </div>
        <ul class="list-group">
            <li class="list-group-item col-xs-12 col-lg-12">
                <div class="col-xs-3">Host</div>
                <div class="col-xs-9 host value">&nbsp;</div>
            </li>

            <li class="list-group-item col-xs-12 col-lg-12 os">
                <div class="col-xs-3">OS</div>
                <div class="col-xs-9 distro value">
                    <span class="pull-left"></span>
                    <div class="icon pull-right"></div>
                </div>
            </li>

            <li class="list-group-item col-xs-12 col-lg-12">
                <div class="col-xs-3">Uptime</div>
                <div class="col-xs-9 uptime value">&nbsp;</div>
            </li>

            <li class="list-group-item col-xs-12 col-lg-12">
                <div class="col-xs-3">Kernel</div>
                <div class="col-xs-9 kernel value">&nbsp;</div>
            </li>

            <li class="list-group-item col-xs-12 col-lg-12">
                <div class="col-xs-3">Updates</div>
                <div class="col-xs-9 value">
                    <span class="label label-default update-packages" title="Update packages">Packages: -</span>
                    <span class="label label-default update-security" title="Update security">Security: -</span>
                </div>
            </li>

            <li class="list-group-item col-xs-12 col-lg-12">
                <div class="col-xs-3 ">RAM</div>
                <div class="col-xs-9">
                    <div class="progress ram">
                        <div class="progress-bar progress-bar-success progress-bar-striped" role="progressbar"></div>
                        <div class="percent"><span>0</span>% used</div>
                    </div>
                </div>
            </li>

            <li class="list-group-item col-xs-12 col-lg-12">
                <div class="col-xs-3 ">Swap</div>
                <div class="col-xs-9">
                    <div class="progress swap">
                        <div class="progress-bar progress-bar-success progress-bar-striped" role="progressbar"></div>
                        <div class="percent"><span>0</span>% used</div>
                    </div>
                </div>
            </li>
        </ul>
    </div>
</div>

<div class="hidden_not_important" id="hardware">
    <div class="panel panel-success pull-left hardware">
        <div class="panel-heading">
            <h4>Hardware</h4>
        </div>
        <ul class="list-group">
            <li class="list-group-item col-xs-12 col-lg-12">
                <div class="col-xs-3">CPU</div>
                <div class="col-xs-9 cpu-model-label value"></div>
            </li>
            <li class="list-group-item col-xs-12 col-lg-12 cpu-cores hidden_not_important">
                <div class="cpu-core col-xs-3"></div>
                <div class="core-stats col-xs-9">
                    <div class="col-xs-4">Temp: </div>
                    <div class="core-temp col-xs-8"></div>
                    <div class="col-xs-4">vCore: </div>
                    <div class="core-vcore col-xs-8"></div>
                    <div class="col-xs-4">Current: </div>
                    <div class="core-current col-xs-8"></div>
                    <div class="col-xs-4">Min: </div>
                    <div class="core-min col-xs-8"></div>
                    <div class="col-xs-4">Max: </div>
                    <div class="core-max col-xs-8"></div>
                </div>
            </li>

            <li class="list-group-item col-xs-12 col-lg-12">
                <div class="col-xs-3">Mobo</div>
                <div class="col-xs-9 motherboard value"></div>
            </li>

            <li class="list-group-item col-xs-12 col-lg-12">
                <div class="col-xs-3">Network</div>
                <div class="lan-stats col-xs-9">
                    <div class="col-xs-4">Name: </div>
                    <div class="lan-name col-xs-8"></div>
                    <div class="col-xs-4">IP: </div>
                    <div class="lan-ip col-xs-8"></div>
                    <div class="col-xs-4">MAC: </div>
                    <div class="lan-mac col-xs-8"></div>
                    <div class="col-xs-4">Speed: </div>
                    <div class="lan-speed col-xs-8"></div>
                    <div class="col-xs-4">Received: </div>
                    <div class="lan-rx col-xs-8"></div>
                    <div class="col-xs-4">Transmitted: </div>
                    <div class="lan-tx col-xs-8"></div>
                </div>
            </li>

            <li class="list-group-item col-xs-12 col-lg-12 fans">
                <div class="col-xs-3">Fans</div>
                <div class="fan-stats col-xs-9">
                    <div>
                        <div class="col-xs-4 name"></div>
                        <div class="col-xs-8 value"></div>
                    </div>
                </div>
            </li>
        </ul>
    </div>
</div>