<div class="col-xs-12 col-md-4">
    <div class="panel panel-success pull-left sysinfo">
        <div class="panel-heading">
            <h4>System info</h4>
        </div>
        <ul class="list-group">
            <li class="list-group-item col-xs-12 col-md-12">
                <div class="col-xs-3">Host</div>
                <div class="col-xs-9 host">&nbsp;</div>
            </li>
            <li class="list-group-item col-xs-12 col-md-12">
                <div class="col-xs-3">OS</div>
                <div class="col-xs-9 distro">&nbsp;</div>
            </li>
            <li class="list-group-item col-xs-12 col-md-12">
                <div class="col-xs-3">Kernel</div>
                <div class="col-xs-9 kernel">&nbsp;</div>
            </li>
            <li class="list-group-item col-xs-12 col-md-12">
                <div class="col-xs-3">Updates</div>
                <div class="col-xs-9">
                    <span class="label label-default update-packages" title="Update packages">Packages:</span>
                    <span class="label label-default update-security" title="Update security">Security:</span>
                </div>
            </li>
            <li class="list-group-item col-xs-12 col-md-12">
                <div class="col-xs-3">CPU</div>
                <div class="col-xs-9 cpu-model">
                    <a id="cpu-model-label" href="#"></a>
                    <div id="cpu-cores">
                        <div>
                            <a class="cpu-core" href="#"></a>
                            <div class="core-stats">
                                <div class="core-temp"></div>
                                <div class="core-current"></div>
                                <div class="core-min"></div>
                                <div class="core-max"></div>
                            </div>
                        </div>
                    </div>
                </div>
            </li>
        </ul>
    </div>
</div>