<div class="col-xs-12 col-sm-12 col-md-8 col-lg-8">
    <div class="panel panel-success pull-left transmission" 
         data-transmission-update-interval="<?php echo $this->config->dashboard->transmissionUpdateInterval ?>" 
         data-transmission-url="<?php echo $this->config->dashboard->transmissionURL ?>"
         data-transmission-username="<?php echo $this->config->dashboard->transmissionUsername ?>"
         data-transmission-password="<?php echo $this->config->dashboard->transmissionPassword ?>">
        <div class="panel-heading">
            <div class="btn-group pull-right">
                <button class="btn btn-default fa fa-pause"></button>
                <button class="btn btn-default fa fa-play"></button>
                <button class="btn btn-default fa fa-refresh"></button>
                <button class="btn btn-default fa fa-plus visible-xs toggle"></button>
            </div>
            <h4 class="pull-left">Transmission</h4>
        </div>
        <ul class="list-group hidden-xs">
            <li class="list-group-item col-xs-12 col-lg-12 torrent hidden">
                <div class="col-lg-5 col-md-5 col-sm-5 col-xs-4 torrentname"></div>
                <div class="col-lg-5 col-md-5 col-sm-5 col-xs-4 torrentprogress">
                    <div class="progress">
                        <div class="progress-bar progress-bar-success progress-bar-striped" role="progressbar"></div>
                        <div class="percent">0%</div>
                    </div>
                </div>
                <div class="col-lg-2 col-md-2 col-sm-2 col-xs-4 torrentactions">
                    <div class="btn-group pull-right">
                        <button class="btn btn-default fa fa-pause status"></button>
                        <button class="btn btn-danger fa fa-remove"></button>
                    </div>
                </div>
            </li>
        </ul>
    </div>
</div>
