<div class="col-xs-12 col-sm-6 col-md-12 col-lg-12">
    <div class="panel panel-success pull-left transmission" 
         data-transmission-update-interval="<?php echo $this->config->dashboard->transmissionUpdateInterval ?>" 
         data-transmission-url="<?php echo $this->config->dashboard->transmissionURL ?>"
         data-transmission-username="<?php echo $this->config->dashboard->transmissionUsername ?>"
         data-transmission-password="<?php echo $this->config->dashboard->transmissionPassword ?>">
        <div class="panel-heading">
            <div class="btn-group pull-right">
                <a href="#" class="btn btn-default glyphicon glyphicon-pause"></a>
                <a href="#" class="btn btn-default glyphicon glyphicon-play"></a>
                <a href="#" class="btn btn-default glyphicon glyphicon-refresh"></a>
                <a href="#" class="btn btn-default glyphicon glyphicon-plus visible-xs toggle"></a>
            </div>
            <h4>Transmission</h4>
        </div>
        <ul class="list-group hidden-xs">
            <li class="list-group-item col-xs-12 col-lg-12 torrent hidden">
                <div class="col-lg-6 torrentname"></div>
                <div class="col-xs-5 torrentprogress">
                    <div class="progress">
                        <div class="progress-bar progress-bar-success progress-bar-striped" role="progressbar"></div>
                        <div class="percent">0%</div>
                    </div>
                </div>
                <div class="col-lg-1 torrentactions">
                    <div class="btn-group pull-right">
                        <button class="btn btn-default glyphicon glyphicon-pause status"></button>
                        <button class="btn btn-danger glyphicon glyphicon-remove"></button>
                    </div>
                </div>
            </li>
        </ul>
    </div>
</div>
