<?php /** @var Chell\Forms\SettingsBaseForm $this */ ?>

<div class="form-group row <?php echo ($hasErrors ? ' has-error' : null) .  ($hidden ? ' hidden' : null) ?>">
    <div class="col-lg-offset-2 col-sm-offset-1 col-lg-4 col-sm-4 col-xs-12 text-right-not-xs">
        <?php echo $element->label(['class' => 'text-bold']) ?>

        <?php if ($hasErrors) : ?>
        <div class="pull-right">
            <i class="error fa fa-info-circle bs-tooltip" title="<?php echo $this->getAllErrorMessagesForElement($name) ?>"></i>
        </div>
        <?php endif ?>
    </div>
    <div class="col-lg-4 col-sm-6 col-xs-12">
        <div class="input-group">
            <?php
            echo $element;

            if (get_class($element) == 'Phalcon\Forms\Element\Password')
            {
                $this->includeButton('toggle_password');
            }

            $options = $element->getUserOptions();
            if (isset($options['buttons']))
            {
                foreach ($options['buttons'] as $button)
                {
                    $this->includeButton($button);
                }
            }

            $this->includeButton('help', $name, $element);
            ?>
        </div>
    </div>
</div>