<?php /** @var Chell\Forms\SettingsBaseForm $this */ ?>

<div class="form-group row <?php echo ($hasErrors ? ' has-error' : null) .  ($hidden ? ' hidden' : null) ?>">
    <div class="col-lg-offset-2 col-sm-offset-1 col-lg-4 col-sm-4 col-xs-12 text-right-not-xs">
        <?php echo $element->label(['class' => 'text-bold']) ?>

        <?php if ($hasErrors) :
            $messages = $this->getMessagesFor($name);
            $errorMessage = '';
            foreach ($messages as $message)
            {
                $errorMessage .= $message->getMessage() ."\n";
            }
        ?>
        <div class="pull-right">
            <i class="error fa fa-info-circle bs-tooltip" title="<?php echo $errorMessage ?>"></i>
        </div>
        <?php endif ?>
    </div>
    <div class="col-lg-4 col-sm-6 col-xs-12">
        <div class="input-group">
            <?php echo $element ?>
            <?php if (get_class($element) == 'Phalcon\Forms\Element\Password') : ?>
            <a class="btn btn-default input-group-addon toggle-password" title="Toggle password display">
                <i class="fa fa-eye"></i>
            </a>
            <?php elseif (strpos($class, 'location') !== false) : ?>
            <a class="btn btn-default input-group-addon" title="Get location">
                <i class="fa fa-map-marker-alt"></i>
            </a>
            <?php endif ?>

            <?php if($this->hasHelp($name)) : ?>
            <a class="btn btn-default <?php echo get_class($element) != 'Phalcon\Forms\Element\Check' ? 'input-group-addon' : 'pull-right' ?> " data-fancybox data-type="iframe" title="Help"
                href="<?php echo $this->config->application->baseUri . 'settings/help/' . $name ?>">
                <i class="fa fa-question"></i>
            </a>
            <?php endif ?>
        </div>
    </div>
</div>