<?php /** @var Phalcon\Mvc\View $this */ ?>

<div class="panel panel-success with-nav-tabs" id="roborock-details">
    <div class="panel-heading">
        <h4 class="pull-left hidden-xs">Roborock</h4>
        <ul class="nav nav-tabs pull-right">
            <li class="active">
                <a data-toggle="tab" href="#info">
                    Info
                </a>
            </li>
            <li>
                <a data-toggle="tab" href="#settings">
                    Settings
                </a>
            </li>
        </ul>
    </div>
    <div class="tab-content">
        <?php $this->partial('roborock/partials/info') ?>
        <?php $this->partial('roborock/partials/settings') ?>
    </div>
</div>