<?php /** @var Phalcon\Mvc\View $this */ ?>

<div class="panel panel-success roborock" data-update-interval="<?php echo $this->settings->roborock->update_interval ?>">
    <?php $this->partial('is-loading') ?>

    <div class="panel-heading">
        <div class="btn-group pull-right">
            <button class="btn btn-default fa fa-play start-stop" title="Start/Stop" aria-label="Start/Stop"></button>
            <a href="roborock/info" data-fancybox data-type="iframe" class="btn btn-default fa fa-info-circle" title="Info" aria-label="Info"></a>
            <?php $this->partial('index/default_widget_buttons', ['hasRefresh' => true]) ?>
        </div>
        <h4>Roborock</h4>
    </div>
    <ul class="list-group hidden-xs">
        <li class="list-group-item col-xs-12">
            <div class="col-xs-4 col-sm-5 col-lg-4">
                State
            </div>
            <div class="col-xs-8 col-sm-7 col-lg-8 state">&hellip;</div>
        </li>
        <li class="list-group-item col-xs-12">
            <div class="col-xs-4 col-sm-5 col-lg-4">
                Battery
            </div>
            <div class="col-xs-8 col-sm-7 col-lg-8 battery">&hellip;</div>
        </li>
        <li class="list-group-item col-xs-12">
            <div class="col-xs-4 col-sm-5 col-lg-4">
                Fan
            </div>
            <div class="col-xs-8 col-sm-7 col-lg-8 fan">&hellip;</div>
        </li>
        <li class="list-group-item col-xs-12">
            <div class="col-xs-4 col-sm-5 col-lg-4">
                Area
            </div>
            <div class="col-xs-8 col-sm-7 col-lg-8 area">&hellip;</div>
        </li>
        <li class="list-group-item col-xs-12">
            <div class="col-xs-4 col-sm-5 col-lg-4">
                Cleaning time
            </div>
            <div class="col-xs-8 col-sm-7 col-lg-8 cleaningtime">&hellip;</div>
        </li>
        <li class="list-group-item col-xs-12">
            <div class="col-xs-4 col-sm-5 col-lg-4">
                Waterbox
            </div>
            <div class="col-xs-8 col-sm-7 col-lg-8 waterbox">&hellip;</div>
        </li>
    </ul>
</div>
