<?php /** @var Phalcon\Mvc\View $this */ ?>

<div class="panel panel-success cpu">
    <?php $this->partial('is-loading') ?>

    <div class="panel-heading">
        <div class="btn-group pull-right">
            <?php $this->partial('index/default_widget_buttons', ['hasRefresh' => false, 'widget' => $widget]) ?>
        </div>
        <h4 class="truncate-text">CPU</h4>
    </div>
    <div class="panel-body hidden-xs">
        <iframe data-src="<?php echo $this->settings->rcpu->url ?>" title="rCPU"></iframe>
    </div>
</div>
