<?php /** @var Phalcon\Mvc\View $this */ ?>

<div class="panel panel-success cpu">
    <?php $this->partial('is-loading') ?>

    <div class="panel-heading">
        <?php $this->partial('index/default_widget_buttons') ?>
        <h4>CPU</h4>
    </div>
    <div class="panel-body hidden-xs">
        <iframe data-src="<?php echo $this->settings->rcpu->url ?>" title="rCPU"></iframe>
    </div>
</div>
