<?php /** @var Chell\Forms\SettingsBaseForm $this */ ?>

<div class="form-group row <?php echo ($hasErrors ? ' has-error' : null) .  ($hidden ? ' hidden' : null) ?>">
    <div class="col-lg-offset-2 col-sm-offset-1 col-lg-4 col-sm-4 col-xs-12">
        <?php echo $element->label(['class' => 'text-bold']) ?>

        <?php if ($hasErrors) : ?>
        <div class="pull-right">
            <i class="error fa fa-circle-info bs-tooltip" title="<?php echo $this->getAllErrorMessagesForElement($name) ?>"></i>
        </div>
        <?php endif ?>
    </div>
    <div class="col-lg-4 col-sm-6 col-xs-12">
        <div class="input-group">
            <?php

            $class = get_class($element);
            if($class == 'Phalcon\Forms\Element\Check') :?>
            <input type="checkbox" name="<?php echo $name ?>" id="<?php echo $name ?>" <?php echo $element->getAttribute('checked') ?>
                data-toggle="toggle" data-onstyle="success" data-offstyle="danger" data-size="small" value="1" />
            <?php else :
                echo $element;
           endif;

            if ($class == 'Phalcon\Forms\Element\Password')
            {
                $this->renderButton('toggle_password');
            }

            $options = $element->getUserOptions();
            if (isset($options['buttons']))
            {
                foreach ($options['buttons'] as $button)
                {
                    $this->renderButton($button, $name, $element);
                }
            }

            $this->renderButton('help', $name, $element);
            ?>
        </div>
    </div>
</div>