<?php /** @var Chell\Forms\SettingsBaseForm $this */ ?>

<fieldset>
    <legend class="row">
        <div class="col-lg-offset-2 col-sm-offset-1 col-lg-4 col-sm-4 col-xs-10">
            <input type="checkbox" name="<?php echo $name ?>" id="<?php echo $name ?>" <?php echo $element->getAttribute('checked') ?>
                data-toggle="toggle" data-onstyle="success" data-offstyle="danger" data-size="small" value="1" />
            <span><?php echo $fieldset ?></span>
        </div>
        <div class="col-lg-4 col-sm-6 col-xs-2">
            <?php $this->renderButton('help', $name, $element); ?>
        </div>
    </legend>