<?php /** @var Chell\Forms\SettingsBaseForm $this */ ?>

<?php $attributes = $this->getAttributes() ?>

<form id="form" action="<?php echo $this->getAction() ?>" method="post" <?php echo $attributes['enctype'] ?? null ?>>
    <?php foreach($this AS $element) : ?>
    <?php echo $this->renderElement($element) ?>
    <?php endforeach ?>

    <input type="hidden" name="<?php echo $this->session->get('auth')['csrf-key'] ?>" value="<?php echo $this->session->get('auth')['csrf-token'] ?>" />
</form>