<?php /** @var Phalcon\Mvc\View $this */ ?>

<div class="panel panel-success pull-left pulseway"
    data-systems="<?php echo $this->settings->pulseway->systems->value ?>"
    data-updateinterval="<?php echo $this->settings->pulseway->update_interval->value ?>">
    <?php $this->partial('is-loading') ?>

    <div class="panel-heading">
        <div class="btn-group pull-right">
            <?php $this->partial('index/default_widget_buttons', ['hasRefresh' => true, 'widget' => $widget]) ?>
        </div>
        <h4 class="truncate-text" title="Pulseway">Pulseway</h4>
    </div>
    <ul class="list-group hidden-xs">
        <li class="list-group-item col-xs-12 hidden system">
            <div class="col-xs-1 icon">
                <i></i>
            </div>
            <div class="col-xs-4 name">
                <span class="bs-tooltip"></span>
            </div>
            <div class="col-xs-7 value">
                <span class="uptimelabel">Uptime: </span>
                <span class="uptime"></span>
            </div>
        </li>
    </ul>
</div>
