<div class="vertical-center about">
    <div class="panel panel-success">
        <div class="panel-heading">
            <h4>About</h4>
        </div>
        <div class="panel-body">
            Version <?php echo $versionMajor . '.' . $versionMinor . '.' . $versionCommit . ' ' . $versionStability ?><br /><br />
            <a href="https://github.com/joszz/Chell-PHP-Portal" target="_blank" class="copyright">Copyright &copy; <?php echo '2015 - ' . (date('Y') != 2015 ? date('Y') : null) ?>
                Jos Nienhuis
            </a>
        </div>
    </div>
</div>