<div class="vertical-center about">
    <div class="panel panel-success">
        <div class="panel-heading">
            <h4>About</h4>
        </div>
        <div class="panel-body">
            Version <?php echo $versionMajor . '.' . $versionMinor . '.' . $versionCommit . ' ' . $versionStability ?>
            <hr />

            <a href="<?php echo $this->config->application->baseUri ?>documentation/phpdoc/" target="_blank">PHP documentation</a>
            <br />
            <small>
                Generated on: <?php echo $lastUpdatedPHPDoc ?>
            </small>
            <br />
            <br />
            <a href="<?php echo $this->config->application->baseUri ?>documentation/yuidoc/" target="_blank">Javascript documentation</a>
            <br />
            <small>
                Generated on: <?php echo $lastUpdatedYUIDoc ?>
            </small>
            <hr />

            <a href="https://github.com/joszz/Chell-PHP-Portal" target="_blank" class="copyright">
                Copyright &copy; <?php echo '2015 - ' . (date('Y') != 2015 ? date('Y') : null) ?>
                Jos Nienhuis
            </a>
        </div>

    </div>
</div>