<?php /** @var Phalcon\Mvc\View $this */ ?>

<div class="panel panel-success sonos gallery"
    data-updateinterval="<?php echo $this->settings->application->check_now_playing_interval ?>">
    <?php $this->partial('is-loading') ?>

    <div class="panel-heading">
        <div class="backdrop"></div>
        <div class="btn-group pull-right">
            <?php $this->partial('index/default_widget_buttons', ['hasRefresh' => true, 'widget' => $widget]) ?>
        </div>
        <h4 class="truncate-text" title="Now playing">Sonos</h4>
    </div>
    <div class="panel-body hidden-xs">
        <a class="album item"
            href="#">
            <img src="img/icons/unknown.jpg" alt="blur effect" class="blur" />
            <img src="img/icons/unknown.jpg" />
            <div class="overlay"></div>
            <div class="title"></div>
            <div class="subtitle"></div>
        </a>
    </div>
</div>
