
<div id="sites" class="tab-pane panel fade" data-togglestate-baseurl="<?php echo $this->config->application->baseUri . 'hyper_v_admin/siteToggleState/' ?>">
    <div class="table-responsive">
        <table class="table table-striped table-hover">
            <thead>
                <tr>
                    <th class="visible-xs">Actions</th>
                    <th>Name</th>
                    <th class="text-right hidden-xs">Actions</th>
                </tr>
            </thead>
            <tbody>
                <?php foreach($sites as $site) :
                        $state = \Chell\Models\HyperVAdmin::getSiteState($site->State);
                        $toggleStateURL = $this->config->application->baseUri . 'hyper_v_admin/siteToggleState/' . $site->Name . '/';
                        $toggleStateURL .= $site->State == \Chell\Models\HyperVAdmin::siteStateEnabed ? \Chell\Models\HyperVAdmin::siteStateDisabed : \Chell\Models\HyperVAdmin::siteStateEnabed;
                ?>
                <tr>
                    <td class="visible-xs actions">
                        <div class="btn-group">
                            <a href="<?php echo $toggleStateURL ?>" class="togglestate btn btn-default btn-<?php echo $state == 'enabled' ? 'success' : 'danger'  ?>">
                                <span class="fa fa-power-off"></span>
                            </a>
                        </div>
                    </td>
                    <td class="name"><?php echo $site->Name ?></td>
                    <td class="hidden-xs actions">
                        <div class="btn-group pull-right">
                            <a href="<?php echo $toggleStateURL ?>" class="togglestate btn btn-default btn-<?php echo $state == 'enabled' ? 'success' : 'danger'  ?>">
                                <span class="fa fa-power-off"></span>
                            </a>
                        </div>
                    </td>
                </tr>
                <?php endforeach ?>

                <tr class="hidden">
                    <td class="visible-xs actions">
                        <div class="btn-group">
                            <a class="togglestate btn btn-default">
                                <span class="fa fa-power-off"></span>
                            </a>
                        </div>
                    </td>
                    <td class="name"></td>
                    <td class="hidden-xs actions">
                        <div class="btn-group pull-right">
                            <a class="togglestate btn btn-default">
                                <span class="fa fa-power-off"></span>
                            </a>
                        </div>
                    </td>
                </tr>
            </tbody>
        </table>
    </div>
</div>