
<div id="vms" class="tab-pane in active panel">
    <div class="table-responsive">
        <table class="table table-striped table-hover">
            <thead>
                <tr>
                    <th class="visible-xs">Actions</th>
                    <th>Name</th>
                    <th>CPU Load</th>
                    <th>Cores</th>
                    <th>RAM</th>
                    <th>MAC</th>
                    <th>On time</th>
                    <th class="text-right hidden-xs">Actions</th>
                </tr>
            </thead>
            <tbody>
                <?php foreach($vms as $vm) :
                    $state = \Chell\Models\HyperVAdmin::getVMState($vm->State);
                    $toggleStateURL = $this->config->application->baseUri . 'hyper_v_admin/vmToggleState/' . $vm->Name . '/';
                    $toggleStateURL .=  $state == 'enabled' ? array_search('disabled', \Chell\Models\HyperVAdmin::vmStates) :
                        array_search('enabled', \Chell\Models\HyperVAdmin::vmStates);
                ?>
                <tr>
                    <td class="visible-xs">
                        <div class="btn-group">
                            <a href="<?php echo $toggleStateURL ?>" class="btn btn-default btn-<?php echo $state == 'enabled' ? 'success' : 'danger'  ?>">
                                <i class="fa fa-power-off"></i>
                            </a>
                        </div>
                    </td>
                    <td>
                        <?php echo $vm->Name ?>
                    </td>
                    <td>
                        <div class="progress">
                            <div class="progress-bar progress-bar-striped progress-bar-success" role="progressbar" style="width:<?php echo $vm->CPULoad ?>%"></div>
                            <div class="percent"><?php echo $vm->CPULoad ?>%
                            </div>
                        </div>
                    </td>
                    <td><?php echo $vm->CoresAmount ?>
                    </td>
                    <td>
                        <?php echo $vm->MemoryTotal . ' ' . $vm->MemoryAllocationUnits ?>
                    </td>
                    <td>
                        <?php echo $vm->MAC ?>
                    </td>
                    <td>
                        <?php echo $vm->GetOnTimeFormatted ?>
                    </td>
                    <td class="hidden-xs">
                        <div class="btn-group pull-right">
                            <a href="<?php echo $toggleStateURL ?>" class="btn btn-default btn-<?php echo $state == 'enabled' ? 'success' : 'danger'  ?>">
                                <i class="fa fa-power-off"></i>
                            </a>
                        </div>
                    </td>
                </tr><?php endforeach ?>
            </tbody>
        </table>
    </div>
</div>