
<div id="vms" class="tab-pane in active panel" data-togglestate-baseurl="<?php echo $this->config->application->baseUri . 'hyper_v_admin/vmToggleState/' ?>">
    <div class="table-responsive">
        <table class="table table-striped table-hover">
            <thead>
                <tr>
                    <th class="visible-xs">Actions</th>
                    <th>Name</th>
                    <th class="text-center">CPU Load</th>
                    <th class="text-center">Cores</th>
                    <th>RAM</th>
                    <th>MAC</th>
                    <th>On time</th>
                    <th class="text-right hidden-xs">Actions</th>
                </tr>
            </thead>
            <tbody>
                <?php foreach($vms as $vm) :
                    $state = \Chell\Models\HyperVAdmin::getVMState($vm->State);
                    $toggleStateURL = $this->config->application->baseUri . 'hyper_v_admin/vmToggleState/' . $vm->Name . '/';
                    $toggleStateURL .= $vm->State == \Chell\Models\HyperVAdmin::vmStateEnabed ? \Chell\Models\HyperVAdmin::vmStateDisabed : \Chell\Models\HyperVAdmin::vmStateEnabed;
                ?>
                <tr>
                    <td class="visible-xs actions">
                        <div class="btn-group">
                            <a href="<?php echo $toggleStateURL ?>" class="togglestate btn btn-default btn-<?php echo $state == 'enabled' ? 'success' : 'danger'  ?>">
                                <i class="fa fa-power-off"></i>
                            </a>
                        </div>
                    </td>
                    <td class="name"><?php echo $vm->Name ?></td>
                    <td class="load">
                        <div class="progress">
                            <div class="progress-bar progress-bar-striped progress-bar-success" role="progressbar" style="width:<?php echo $vm->CPULoad ?>%"></div>
                            <div class="percent"><?php echo (empty($vm->CPULoad) ? '0' : $vm->CPULoad) ?>%
                            </div>
                        </div>
                    </td>
                    <td class="text-center cores"><?php echo $vm->CoresAmount ?></td>
                    <td class="ram"><?php echo $vm->MemoryTotal . ' ' . $vm->MemoryAllocationUnits ?></td>
                    <td class="mac"><?php echo $vm->MAC ?></td>
                    <td class="ontime"><?php echo $vm->GetOnTimeFormatted ?></td>
                    <td class="hidden-xs actions">
                        <div class="btn-group pull-right">
                            <a href="<?php echo $toggleStateURL ?>" class="togglestate btn btn-default btn-<?php echo $state == 'enabled' ? 'success' : 'danger'  ?>">
                                <i class="fa fa-power-off"></i>
                            </a>
                        </div>
                    </td>
                </tr><?php endforeach ?>

                <tr class="hidden">
                    <td class="visible-xs actions">
                        <div class="btn-group">
                            <a class="togglestate btn btn-default">
                                <i class="fa fa-power-off"></i>
                            </a>
                        </div>
                    </td>
                    <td class="name"></td>
                    <td class="load">
                        <div class="progress">
                            <div class="progress-bar progress-bar-striped progress-bar-success" role="progressbar"></div>
                            <div class="percent"></div>
                        </div>
                    </td>
                    <td class="text-center cores"></td>
                    <td class="ram"></td>
                    <td class="mac"></td>
                    <td class="ontime"></td>
                    <td class="hidden-xs actions">
                        <div class="btn-group pull-right">
                            <a class="togglestate btn btn-default">
                                <i class="fa fa-power-off"></i>
                            </a>
                        </div>
                    </td>
                </tr>
            </tbody>
        </table>
    </div>
</div>