<?php /** @var Phalcon\Mvc\Controller $this */ ?>

<link rel="apple-touch-icon" sizes="180x180" href="<?php echo $this->config->application->baseUri ?>img/icons/favicons/apple-touch-icon.png" />
<link rel="icon" type="image/png" sizes="32x32" href="<?php echo $this->config->application->baseUri ?>img/icons/favicons/favicon-32x32.png" />
<link rel="icon" type="image/png" sizes="16x16" href="<?php echo $this->config->application->baseUri ?>img/icons/favicons/favicon-16x16.png" />
<link rel="icon" type="image/png" sizes="192x192" href="<?php echo $this->config->application->baseUri ?>img/icons/favicons/android-chrome-192x192.png" />
<link rel="mask-icon" href="<?php echo $this->config->application->baseUri ?>img/icons/favicons/safari-pinned-tab.svg" color="#4f4f4f" />
<meta name="apple-mobile-web-app-title" content="<?php echo $this->config->application->title ?>" />
<meta name="application-name" content="<?php echo $this->config->application->title ?>" />
<meta name="theme-color" content="#4f4f4f" />
<link rel="manifest" href="<?php echo $this->config->application->baseUri ?>index/manifest" />