<?php /** @var Phalcon\Mvc\Controller $this */ ?>

<footer class="navbar navbar-inverse">
    <div class="container text-muted">
        <div class="col-xs-6 col-md-6 col-sm-5">
            <a href="https://github.com/joszz/Chell-PHP-Portal" target="_blank" class="copyright" rel="noreferrer">
                &copy; <?php echo date('Y') ?>
                Jos Nienhuis
            </a>
        </div>
        <div class="col-xs-6 col-md-6 col-sm-7 text-right">
            <div class="btn-group pull-right actions">
                <?php if($this->dispatcher->getControllerName() == 'index') : ?>
                <button class="btn btn-dark toggle-all fa fa-expand visible-xs" title="Collapse/Expand all" aria-label="Collapse/Expand all"></button>
                <?php endif ?>
                <button class="btn btn-dark fa fa-arrows-alt rounded-not-mobile" title="Fullscreen" aria-label="Fullscreen"></button>
            </div>
            <div class="visible-sm visible-md visible-lg execution-time pull-right">
                Version: <?php echo $this->config->application->version ?> |
                Execution time: <?php echo round(($executionTime + microtime(true)), 2) ?>s
            </div>
        </div>
    </div>
</footer>
