<footer class="navbar navbar-inverse">
    <div class="container text-muted">
        <div class="col-xs-6 col-md-6 col-sm-5">
            <a href="https://github.com/joszz/Chell-PHP-Portal" target="_blank" class="copyright">
                &copy; <?php echo date('Y') ?>
                Jos Nienhuis
            </a>
        </div>
        <div class="col-xs-6 col-md-6 col-sm-7 text-right">
            <div class="btn-group pull-right actions">
                <?php if($this->dispatcher->getControllerName() == 'index') : ?>
                <button class="btn btn-dark toggle-all fa fa-expand visible-xs"></button>
                <?php endif ?>
                <button class="btn btn-dark fa fa-arrows-alt rounded-not-mobile"></button>
            </div>
            <div class="visible-sm visible-md visible-lg execution-time pull-right">
                Execution time | Total: <?php echo round(($executionTime + microtime(true)), 2) ?>s
                <?php if(isset($phpsysinfoExecutionTime) && is_string($phpsysinfoExecutionTime)) : ?>
                | PHPSysInfo: <?php echo $phpsysinfoExecutionTime ?>
                <?php endif ?>
            </div>
        </div>
    </div>
</footer>
