<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">

    <?php echo $this->tag->getTitle(); ?>
    <?php $this->assets->outputCss('header') ?>
    <link href="https://fonts.googleapis.com/css?family=Roboto:400,700italic,700,400italic,300,300italic" rel="stylesheet" type="text/css">

    <?php $this->partial('favicons') ?>
</head>

<body id="bootstrap">
    <?php $this->partial('navbar') ?>

    <div class="container">
        <?php echo $this->getContent() ?>
    </div>

    <div class="alert" role="alert"></div>

    <?php $this->partial('footer') ?>
    <?php $this->assets->outputJs('footer') ?>
</body>
</html>
