<!DOCTYPE html>
<html lang="en" class="<?php echo $this->config->application->background ?> <?php echo isset($containerFullHeight) ? 'full-height' : null ?>">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=1" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <link rel="alternate" title="RSS" type="application/rss+xml" href="<?php echo $this->config->application->baseUri ?>rss" />

    <?php echo $this->tag->getTitle(); ?>

    <?php if(isset($dnsPrefetchRecords)) : foreach ($dnsPrefetchRecords as $dnsRecord) : ?>
    <link rel="dns-prefetch" href="<?php echo $dnsRecord ?>" />
    <?php endforeach; endif ?>

    <?php $this->assets->outputCss('header') ?>
    <?php $this->partial('favicons') ?>
</head>

<body id="bootstrap">
    <?php $this->partial('navbar') ?>

    <div class="container <?php echo isset($containerFullHeight) ? 'full-height' : 'content' ?>">
        <?php echo $this->getContent() ?>
    </div>

    <div class="alert" role="alert" data-alert-timeout="<?php echo $this->config->application->alertTimeout ?>"></div>

    <?php $this->partial('dialog-confirm') ?>

    <?php
    $this->partial('footer');
    $this->assets->outputJs('footer');
    $controller = $this->dispatcher->getControllerName();

    if($controller == 'index')
    {
        $this->assets->outputJs('dashboard');
    }
    else if($controller == 'settings')
    {
        $this->assets->outputJs('settings');
    }
    ?>
</body>
</html>
