<?php
/**
 * @var Phalcon\Mvc\Controller          $this
 * @var Phalcon\Paginator\Repository    $menu
 */
?>

<nav class="navbar navbar-inverse navbar-fixed-top">
    <div class="container no-gutter-xs">
        <div class="col-xs-12">
            <div class="navbar-header">
                <?php if (isset($user)) : ?>
                <button type="button" id="menu_btn" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <?php endif ?>

                <button type="submit" class="btn btn-success fa fa-save hidden_not_important" title="Save" aria-label="Save" form="form_general"></button>

                <a class="navbar-brand" href="<?php echo $this->config->application->baseUri ?>">
                    <img src="<?php echo $this->config->application->baseUri ?>img/icons/favicons/android-chrome-72x72.png" alt="Logo" width="32" height="32" />
                    <span>
                        <?php echo $this->tag->getTitle(); ?>
                    </span>
                </a>
            </div>
        </div>
        <div class="col-xs-12 no-gutter-xs">
            <div id="navbar" class="collapse navbar-collapse">
                <?php if (isset($user)) : ?>
                <ul class="nav navbar-nav">
                    <?php foreach($user->getMenuItems(['order' => 'name ASC']) as $menuItem) : ?>
                    <?php if (strpos($menuItem->url, $this->config->network->broadcast) !== false && strpos($_SERVER['REMOTE_ADDR'], $this->config->network->broadcast) === false) continue ?>

                    <li class="col-xs-6 col-sm-3 col-lg-2 no-gutter hover<?php echo $menuItem->device != null ? ' disabled" data-id="' . $menuItem->device->id : '' ?>">
                        <a href="<?php echo $menuItem->url ?>" target="_blank" rel="noreferrer">
                            <img src="<?php echo $menuItem->getIconFilePath($this->config->application->baseUri) ?>" width="16"
                                alt="<?php echo $menuItem->name ?>" loading="lazy" />
                            <?php echo $menuItem->name ?>
                        </a>
                    </li>
                    <?php endforeach ?>
                </ul>
                <div class="col-xs-12">
                    <div class="btn-group pull-right">
                        <a class="btn btn-dark" href="<?php echo $this->config->application->baseUri ?>settings/">
                            <span class="fa fa-cog"></span>
                        </a>
                        <a class="btn btn-dark" href="<?php echo $this->config->application->baseUri ?>about/">
                            <span class="fa fa-info-circle"></span>
                        </a>
                        <a class="btn btn-dark" href="<?php echo $this->config->application->baseUri ?>session/logout/">
                            <span class="fa fa-sign-out-alt" title="Logout <?php echo $this->session->get('auth')['username'] ?>"></span>
                        </a>
                    </div>
                </div>
                <?php endif ?>
            </div>
        </div>
    </div>
</nav>
