<?php if($paginator->total > 1) : ?>
<nav class="paginator">
    <ul class="pagination">
        <li>
            <a href="<?php echo $paginator->current == 1 ? '#' : $this->config->application->baseUri . 'opcache/details/' . ($paginator->current - 1) ?>/scripts"
                class="fa fa-backward <?php echo $paginator->current == 1 ? 'disabled': null ?>"></a>
        </li>

        <?php for($i = $paginator->start; $i <= $paginator->end; $i++ ) : ?>
        <li class="hidden-xs <?php echo $paginator->current == $i ? 'active' : null ?>">
            <a href="<?php echo $this->config->application->baseUri . 'opcache/details/' . $i ?>/scripts">
                <?php echo $i ?>
            </a>
        </li>
        <?php endfor ?>

        <li>
            <a href="<?php echo $paginator->current == $paginator->total ? '#' : $this->config->application->baseUri . 'opcache/details/' . ($paginator->current + 1) ?>/scripts"
                class="fa fa-forward <?php echo $paginator->current == $paginator->total ? 'disabled': null ?>"></a>
        </li>
    </ul>
</nav>
<?php endif ?>