<?php /** @var array $php */ ?>

<div id="php" class="tab-pane fade in">
    <div class="table-responsive">
        <table class="table table-striped table-hover">
            <thead>
                <tr>
                    <th>Name</th>
                    <th>Value</th>
                </tr>
            </thead>
            <tbody>
                <?php foreach($php as $key => $value) : ?>
                <tr>
                    <td>
                        <?php echo $key ?>
                    </td>
                    <td>
                        <?php echo $value ?>
                    </td>
                </tr>
                <?php endforeach ?>
            </tbody>
        </table>
    </div>
</div>