<?php /** @var Phalcon\Mvc\View $this */ ?>

<div class="panel panel-success pull-left processes">
    <?php $this->partial('is-loading') ?>

    <div class="panel-heading">
        <div class="btn-group pull-right">
            <?php $this->partial('index/default_widget_buttons', ['hasRefresh' => true, 'widgetId' => $widget->id]) ?>
        </div>
        <h4 class="truncate-text" title="Processes">Processes</h4>
    </div>
    <ul class="list-group hidden-xs"></ul>
</div>
