<?php /** @var Phalcon\Mvc\View $this */ ?>

<div class="panel panel-success harddisks">
    <?php $this->partial('is-loading') ?>

    <div class="panel-heading">
        <div class="btn-group pull-right">
            <?php $this->partial('index/default_widget_buttons', ['hasRefresh' => true, 'widgetId' => $widget->id]) ?>
        </div>
        <h4 class="truncate-text" title="Disk usage">Disk usage</h4>
    </div>
    <ul class="list-group hidden-xs">
        <li class="list-group-item col-xs-12 hidden clone">
            <div class="col-xs-5 col-md-5 col-lg-4 name truncate-text"></div>
            <div class="col-xs-7 col-md-7 col-lg-8">
                <div class="progress">
                    <div class="progress-bar progress-bar-striped" role="progressbar" aria-label="Disk space"></div>
                    <div class="percent"></div>
                </div>
            </div>
        </li>
    </ul>
</div>