<?php 
/** @var Phalcon\Mvc\View $this */ 
$hasRefresh = true;
?>

<div class="panel panel-success pull-left processes">
    <?php $this->partial('is-loading') ?>

    <div class="panel-heading">
        <div class="btn-group pull-right">
            <?php $this->partial('index/default_widget_buttons') ?>
        </div>
        <h4>Processes</h4>
    </div>
    <ul class="list-group hidden-xs"></ul>
</div>
