<?php /** @var Phalcon\Mvc\View $this */ ?>

<div class="panel panel-success pull-left torrents"
    data-update-interval="<?php echo $this->settings->torrents->update_interval ?>">
    <div class="panel-heading">
        <div class="btn-group pull-right">
            <button class="btn btn-default fa fa-pause" title="Start all" aria-label="Start all"></button>
            <button class="btn btn-default fa fa-play" title="Stop all" aria-label="Stop all"></button>
            <a href="<?php echo $this->settings->torrents->url ?>" target="_blank" class="btn btn-default fa fa-globe" title="Open WebUI"></a>
            <?php $this->partial('index/default_widget_buttons', ['hasRefresh' => true, 'widget' => $widget]) ?>
        </div>
        <h4 class="truncate-text" title="Torrents">Torrents</h4>
    </div>
    <ul class="list-group hidden-xs">
        <li class="list-group-item col-xs-12 col-lg-12 torrent hidden">
            <div class="col-lg-6 col-md-5 col-sm-5 col-xs-4 torrentname"></div>
            <div class="col-lg-5 col-md-5 col-sm-5 col-xs-4 torrentprogress">
                <div class="progress">
                    <div class="progress-bar progress-bar-success progress-bar-striped" role="progressbar"></div>
                    <div class="percent">0%</div>
                </div>
            </div>
            <div class="col-lg-1 col-md-2 col-sm-2 col-xs-4 torrentactions">
                <div class="btn-group pull-right">
                    <button class="btn btn-default fa fa-pause status"></button>
                    <button class="btn btn-danger fa fa-trash-alt"></button>
                </div>
            </div>
        </li>
    </ul>
</div>
