<?php /** @var Phalcon\Mvc\View $this */ ?>

<div class="panel panel-success nowplaying gallery"
    data-nowplaying-intveral="<?php echo $this->settings->application->check_now_playing_interval ?>"
    data-kodi-url="<?php echo $this->settings->kodi->url ?>"
    data-kodi-username="<?php echo $this->settings->kodi->username ?>"
    data-kodi-password="<?php echo $this->settings->kodi->password ?>"
    data-kodi-enable="<?php echo $this->settings->kodi->enabled ?>"
    data-subsonic-url="<?php echo $this->settings->subsonic->url ?>"
    data-subsonic-username="<?php echo $this->settings->subsonic->username ?>"
    data-subsonic-password="<?php echo $this->settings->subsonic->password ?>">

    <div class="panel-heading">
        <div class="backdrop"></div>
        <div class="btn-group pull-right">
            <button class="btn btn-default fa fa-chevron-left" title="Previous player" aria-label="Previous player"></button>
            <button class="btn btn-default fa fa-chevron-right" title="Next player" aria-label="Next player"></button>
            <?php $this->partial('index/default_widget_buttons', ['hasRefresh' => true, 'widget' => $widget]) ?>
        </div>
        <h4 class="truncate-text" title="Now playing">Now playing</h4>
    </div>
    <div class="panel-body hidden-xs">
        <div class="player nothing-playing">
            <a class="item show_not_important">
                <div class="image"></div>
                <div class="overlay"></div>
                <div class="title">Nothing playing</div>
                <div class="subtitle"></div>
            </a>

            <div class="hidden_not_important nowplaying_detail" id="nowplaying_detail">
                <div class="panel panel-success pull-left">
                    <div class="panel-heading">
                        <button class="btn btn-default fa fa-rotate pull-right"></button>
                        <h4></h4>
                    </div>
                    <ul class="list-group panel-success">
                        <li class="list-group-item col-xs-12 col-lg-12">
                            <div class="col-xs-3">Track</div>
                            <div class="col-xs-9 track"></div>
                        </li>

                        <li class="list-group-item col-xs-12 col-lg-12">
                            <div class="col-xs-3">Album</div>
                            <div class="col-xs-9 album"></div>
                        </li>

                        <li class="list-group-item col-xs-12 col-lg-12">
                            <div class="col-xs-3">Year</div>
                            <div class="col-xs-9 year"></div>
                        </li>

                        <li class="list-group-item col-xs-12 col-lg-12">
                            <div class="col-xs-3">Genre</div>
                            <div class="col-xs-9 genre"></div>
                        </li>

                        <li class="list-group-item col-xs-12 col-lg-12">
                            <div class="col-xs-3">Duration</div>
                            <div class="col-xs-9 duration"></div>
                        </li>

                        <li class="list-group-item col-xs-12 col-lg-12">
                            <div class="col-xs-3">Bitrate</div>
                            <div class="col-xs-9 bitrate"></div>
                        </li>

                        <li class="list-group-item col-xs-12 col-lg-12">
                            <div class="col-xs-3">Playcount</div>
                            <div class="col-xs-9 playcount"></div>
                        </li>

                        <li class="list-group-item col-xs-12 col-lg-12">
                            <div class="col-xs-3">Last played</div>
                            <div class="col-xs-9 lastplayed"></div>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
</div>
