<?php /** @var Phalcon\Mvc\View $this */ ?>

<div class="panel panel-success with-nav-tabs apache-details">
    <div class="panel-heading">
        <h4 class="pull-left hidden-xs">Apache</h4>
        <ul class="nav nav-tabs pull-right">
            <li class="active">
                <a data-toggle="tab" href="#apache">
                    Apache
                </a>
            </li>
            <?php if(isset($php)) : ?>
            <li>
                <a data-toggle="tab" href="#php">
                    PHP
                </a>
            </li>
            <?php endif ?>
        </ul>
    </div>
    <div class="tab-content">
        <?php $this->partial('apache/partials/apache') ?>
        <?php if(isset($php)) : ?>
        <?php $this->partial('apache/partials/php') ?>
        <?php endif ?>
    </div>
</div>
