<?php /** @var Phalcon\Mvc\View $this */ ?>

<div class="panel panel-success apache" data-update-interval="<?php echo $this->settings->apache->update_interval->value ?>">
    <?php $this->partial('is-loading') ?>

    <div class="panel-heading">
        <div class="btn-group pull-right">
            <a href="<?php echo $this->url->get('apache/details/') ?>" data-fancybox data-type="iframe" class="btn btn-default fa fa-chart-bar" title="Details"></a>
            <?php $this->partial('index/default_widget_buttons', ['hasRefresh' => true, 'widget' => $widget]) ?>
        </div>
        <h4 class="truncate-text" title="Apache">Apache</h4>
    </div>
    <ul class="list-group hidden-xs">
        <li class="list-group-item col-xs-12">
            <div class="col-xs-4 col-sm-5 col-lg-4">
                Version
            </div>
            <div class="col-xs-8 col-sm-7 col-lg-8 version truncate-text bs-tooltip">&hellip;</div>
        </li>
        <li class="list-group-item col-xs-12">
            <div class="col-xs-4 col-sm-5 col-lg-4">
                Uptime
            </div>
            <div class="col-xs-8 col-sm-7 col-lg-8 uptime">&hellip;</div>
        </li>
        <li class="list-group-item col-xs-12">
            <div class="col-xs-4 col-sm-5 col-lg-4">
                Server Built
            </div>
            <div class="col-xs-8 col-sm-7 col-lg-8 built">&hellip;</div>
        </li>
        <li class="list-group-item col-xs-12">
            <div class="col-xs-4 col-sm-5 col-lg-4">
                CPU load
            </div>
            <div class="col-xs-8 col-sm-7 col-lg-8 load">&hellip;</div>
        </li>
        <li class="list-group-item col-xs-12">
            <div class="col-xs-4 col-sm-5 col-lg-4">
                Req/s
            </div>
            <div class="col-xs-8 col-sm-7 col-lg-8 requests-s">&hellip;</div>
        </li>
        <li class="list-group-item col-xs-12">
            <div class="col-xs-4 col-sm-5 col-lg-4">
                Bytes/s
            </div>
            <div class="col-xs-8 col-sm-7 col-lg-8 bytes-s">&hellip;</div>
        </li>
        <li class="list-group-item col-xs-12">
            <div class="col-xs-4 col-sm-5 col-lg-4">
                Bytes/req
            </div>
            <div class="col-xs-8 col-sm-7 col-lg-8 bytes-requests">&hellip;</div>
        </li>

        <li class="list-group-item col-xs-12">
            <div class="col-xs-4 col-sm-5 col-lg-4">
                Duration/req
            </div>
            <div class="col-xs-8 col-sm-7 col-lg-8 duration-request">&hellip;</div>
        </li>
    </ul>
</div>
