<div id="sites" class="tab-pane panel">
    <div class="table-responsive">
        <table class="table table-striped table-hover">
            <thead>
                <tr>
                    <th class="visible-xs">Actions</th>
                    <th>Name</th>
                    <th class="text-right hidden-xs">Actions</th>
                </tr>
            </thead>
            <tbody><?php foreach($sites as $site) : ?>
                <tr>
                    <td class="visible-xs">
                        <div class="btn-group">

                        </div>
                    </td>
                    <td><?php echo $site->Name ?>
                    </td>
                    <td class="hidden-xs">
                        <div class="btn-group pull-right">

                        </div>
                    </td>
                </tr><?php endforeach ?>
            </tbody>
        </table>
    </div>
</div>