<?php
/**
 * @var Phalcon\Mvc\View    $this
 * @var string              $bgImage
 * @var bool                $overflow
 */

use Phalcon\Tag;
?>
<!DOCTYPE html>
<html lang="en" id="iframe">
<head>
    <meta charset="utf-8" />
    <meta name="description" content="Chell PHP Portal - Aggregate all your webserver services" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <meta name="color-scheme" content="dark light" />

    <?php
    echo Tag::renderTitle();
    $this->assets->outputCss('styles');
    $this->assets->outputJs('scripts');
    $this->partial('favicons');
    ?>
</head>

<body data-bg-image="<?php echo $bgImage ?? null ?>"
    class="<?php echo isset($overflow) && $overflow == true ? 'overflow' : null ?> <?php echo $this->settings->application->demo_mode ? 'demo-mode' : null ?>">
    <div class="container-fluid no-gutter container-relative">
        <?php echo $this->getContent() ?>
    </div>

    <?php $this->partial('dialog-confirm') ?>
</body>
</html>