<?php
/**
 * @var Phalcon\Mvc\View    $this
 * @var string              $bgImage
 * @var bool                $overflow
 */
?>

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="description" content="Chell PHP Portal - Aggregate all your webserver services" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <?php echo $this->tag->renderTitle();  ?>
    <?php
    $this->assets->outputCss('header');
    $this->assets->outputJs('general');
    $this->partial('favicons');
    if ($this->assets->collection('dashboard')->count())
    {
        $this->assets->outputJs('dashboard');
    }
    ?>
</head>

<body id="iframe" data-bg-image="<?php echo $bgImage ?>"
    class="<?php echo isset($overflow) && $overflow == true ? 'overflow' : null ?> <?php echo $this->config->application->demoMode ? 'demo-mode' : null ?>">
    <div class="container-fluid no-gutter container-relative">
        <?php echo $this->getContent() ?>
    </div>

    <?php $this->partial('dialog-confirm') ?>
</body>
</html>