<?php /** @var Phalcon\Mvc\Controller $this */ ?>

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="description" content="Chell PHP Portal - Aggregate all your webserver services" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <?php echo $this->tag->renderTitle(); ?>
    <?php $this->assets->outputCss('header') ?>
    <?php $this->assets->outputJs('general'); ?>
    <?php //todo: below needed for HyperVAdmin, but not ideal solution.. ?>
    <?php $this->assets->outputJs('dashboard'); ?>
    <?php $this->partial('favicons') ?>
</head>

<body id="iframe" <?php echo isset($bgImage) ? 'style="background: url(\'' . $bgImage . '\') no-repeat center center / cover"' : null ?>
    class="<?php echo isset($overflow) && $overflow == true ? 'overflow' : null ?> <?php echo $this->config->application->demoMode ? 'demo-mode' : null ?>">
    <div class="container-fluid no-gutter container-relative">
        <?php echo $this->getContent() ?>
    </div>

    <?php $this->partial('dialog-confirm') ?>
</body>
</html>