<!DOCTYPE html>
<html lang="en" class="<?php echo $this->config->application->background ?> <?php echo isset($containerFullHeight) ? 'full-height' : null ?>">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=1" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />

    <link rel="stylesheet" href="css/compressed/<?php echo $this->css ?>" />
</head>

<body>
    <div id="error" class="container"><?php echo $this->content ?></div>
</body>
</html>
