<?php /** @var Phalcon\Mvc\Controller $this */ ?>

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=1" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />

    <?php foreach($this->css as $css) : ?>
    <link rel="stylesheet" href="<?php echo $css ?>" />
    <?php endforeach ?>

    <?php foreach($this->js as $js) : ?>
    <script type="text/javascript" <?php echo 'src="' . $js .'"' ?> defer="defer"></script>
    <?php endforeach ?>

    <?php if ($this->config->application->debug) : ?>
    <title>ChellException: "<?php echo $this->exception->getMessage() ?>"</title>
    <?php else : ?>
    <title>Oops! An error occurred</title>
    <?php endif ?>
</head>

<body>
    <div class="container">
        <?php echo $this->content ?>
    </div>
</body>
</html>
