<?php
/**
 * @var Phalcon\Mvc\View                $this
 * @var Phalcon\Paginator\Repository    $menu
 * @var Chell\Models\Users              $user
 * @var bool                            $setSaveButton
 */
?>

<nav class="navbar navbar-inverse navbar-fixed-top">
    <div class="container no-gutter-xs">
        <div class="col-xs-12">
            <div class="navbar-header">
                <div class="btn-group pull-right">
                    <?php if(isset($setSaveButton) && $setSaveButton) : ?>
                    <button type="submit" class="btn btn-success fa fa-floppy-disk pull-left" title="Save" aria-label="Save" form="form"></button>
                    <?php endif ?>

                    <?php if (isset($user)) : ?>
                    <button type="button" id="menu_btn" class="btn navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <?php endif ?>
                </div>

                <a class="navbar-brand" href="<?php echo $this->url->get() ?>">
                    <img src="<?php echo $this->url->get('img/icons/favicons/android-chrome-192x192.png') ?>" alt="Logo" width="32" height="32" />
                    <span>
                        <?php echo Phalcon\Tag::getTitle(); ?>
                    </span>
                </a>
            </div>
        </div>
        <div class="col-xs-12 no-gutter-xs">
            <div id="navbar" class="collapse navbar-collapse">
                <?php if (isset($user)) : ?>
                <ul class="nav navbar-nav">
                    <?php foreach($user->getMenuItems(['order' => 'name ASC']) as $menuItem) : ?>
                    <li class="col-xs-6 col-sm-3 col-lg-2 no-gutter hover<?php echo $menuItem->device != null ? ' disabled" data-id="' . $menuItem->device->id : '' ?>">
                        <a href="<?php echo $menuItem->url ?>" target="_blank" rel="noreferrer">
                            <img src="<?php echo $this->url->get('img/icons/menu/' . $menuItem->id . '.png') ?>" width="16"
                                alt="<?php echo $menuItem->name ?>" loading="lazy" />
                            <?php echo $menuItem->name ?>
                        </a>
                    </li>
                    <?php endforeach ?>
                </ul>
                <div class="col-xs-12">
                    <div class="btn-group pull-right">
                        <a class="btn btn-dark" id="move_widgets" href="#" title="Move widgets">
                            <span class="fa fa-arrows-up-down-left-right"></span>
                        </a>
                        <a class="btn btn-dark" href="<?php echo $this->url->get('settings/') ?>" title="Settings">
                            <span class="fa fa-gear"></span>
                        </a>
                        <a class="btn btn-dark" href="<?php echo $this->url->get('about/') ?>" title="About">
                            <span class="fa fa-circle-info"></span>
                        </a>
                        <a class="btn btn-dark" href="<?php echo $this->url->get('session/logout/') ?>" title="Logout">
                            <span class="fa fa-right-from-bracket" title="Logout <?php echo $this->session->get('auth')['username'] ?>"></span>
                        </a>
                    </div>
                </div>
                <?php endif ?>
            </div>
        </div>
    </div>
</nav>

<?php echo $this->getContent() ?>