<?php
/*
* The layout used for RSS feeds.
*
* @package 		Views
* @subpackage	Layouts
*/
?>
<?php echo '<?' ?>xml version="1.0" encoding="UTF-8"<?= "?>\n" ?>
<rss version="2.0" xmlns:atom="http://www.w3.org/2005/Atom">
  <channel>
    <copyright>Copyright 2015 - <?= date('Y') ?> | Jos Nienhuis</copyright>
    <language>en</language>
    <atom:link href="<?php echo $baseURL ?>index/rss" rel="self" type="application/rss+xml" />
    <link><?php echo $baseURL ?></link>
    <title><?php echo $this->config->application->title ?></title>
    <description></description>
    <pubDate><?php echo date('D, d M Y H:i:s') ?> +0200</pubDate>
    <?php echo $this->getContent() ?>
    </channel>
</rss>
