<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <?php echo $this->tag->getTitle(); ?>
    <?php $this->assets->outputCss('header') ?>

    <link rel="apple-touch-icon" sizes="57x57" href="/portal/img/icons/apple-touch-icon-57x57.png">
    <link rel="apple-touch-icon" sizes="60x60" href="/portal/img/icons/apple-touch-icon-60x60.png">
    <link rel="apple-touch-icon" sizes="72x72" href="/portal/img/icons/apple-touch-icon-72x72.png">
    <link rel="apple-touch-icon" sizes="76x76" href="/portal/img/icons/apple-touch-icon-76x76.png">
    <link rel="apple-touch-icon" sizes="114x114" href="/portal/img/icons/apple-touch-icon-114x114.png">
    <link rel="apple-touch-icon" sizes="120x120" href="/portal/img/icons/apple-touch-icon-120x120.png">
    <link rel="apple-touch-icon" sizes="144x144" href="/portal/img/icons/apple-touch-icon-144x144.png">
    <link rel="apple-touch-icon" sizes="152x152" href="/portal/img/icons/apple-touch-icon-152x152.png">
    <link rel="apple-touch-icon" sizes="180x180" href="/portal/img/icons/apple-touch-icon-180x180.png">
    <link rel="icon" type="image/png" href="/portal/img/icons/favicon-32x32.png" sizes="32x32">
    <link rel="icon" type="image/png" href="/portal/img/icons/android-chrome-192x192.png" sizes="192x192">
    <link rel="icon" type="image/png" href="/portal/img/icons/favicon-96x96.png" sizes="96x96">
    <link rel="icon" type="image/png" href="/portal/img/icons/favicon-16x16.png" sizes="16x16">
    <link rel="manifest" href="/portal/img/icons/manifest.json">
    <link rel="shortcut icon" href="/portal/img/icons/favicon.ico">
    <meta name="apple-mobile-web-app-title" content="Homeserver Portal">
    <meta name="application-name" content="Homeserver Portal">
    <meta name="msapplication-TileColor" content="#2b5797">
    <meta name="msapplication-TileImage" content="/portal/img/icons/mstile-144x144.png">
    <meta name="theme-color" content="#ffffff">
</head>

<body class="nopadding">
    <div class="container">
        <?php echo $this->getContent() ?>
    </div>

    <?php $this->assets->outputJs('footer') ?>
</body>
</html>